### ISSUE TITLE
Keras

### ISSUE THREAD

**Issue by sayan-sen** [piwheels/packages#100]
Package name: Keras-2.3.1
Link to PyPI page: NA
Link to piwheels page: NA
Version: 2.3
Python version: 3.7
I am the maintainer: No
More information: Raspbian Buster 

```bash
pip3 install Keras-2.3.1-py2.py3-none-any.whl 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./Keras-2.3.1-py2.py3-none-any.whl
Processing ./.cache/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653/PyYAML-5.3.1-cp37-cp37m-linux_aarch64.whl
Collecting scipy>=0.14
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting keras-preprocessing>=1.0.5
  Using cached Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41 kB)
Processing ./.cache/pip/wheels/58/e7/f7/d9385040f9b6919de4a5c05625c4e655999412f12c96d3c7c3/h5py-2.10.0-cp37-cp37m-linux_aarch64.whl
Requirement already satisfied: numpy>=1.9.1 in ./venv/lib/python3.7/site-packages (from Keras==2.3.1) (1.18.2)
Collecting keras-applications>=1.0.6
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python3.7/site-packages (from Keras==2.3.1) (1.14.0)
Building wheels for collected packages: scipy
  Building wheel for scipy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/venv/bin/python /home/pi/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpi31xbqrc
       cwd: /tmp/pip-install-azwn3tdl/scipy
  Complete output (4782 lines):
...
 ERROR: Failed building wheel for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
```

**Comment by bennuttall** [comment]
That's weird. It's trying to build scipy 1.4.1 from source from PyPI. But we have that version on piwheels.

Can you run the following command and post the contents of `scipy.txt`:

```bash
pip3 install -v scipy > scipy.txt
```

Also please edit your original comment to complete the issue template to give us the info we need. And are you using Raspbian? Anything else out of the ordinary we need to know?

Hang on - why are you installing Keras from a file?

**Comment by sayan-sen** [comment]
> That's weird. It's trying to build scipy 1.4.1 from source from PyPI. But we have that version on piwheels.
> 
> Can you run the following command and post the contents of `scipy.txt`:
> 
> ```shell
> pip3 install -v scipy > scipy.txt
> ```
> 
> Also please edit your original comment to complete the issue template to give us the info we need. And are you using Raspbian? Anything else out of the ordinary we need to know?
> 
> Hang on - why are you installing Keras from a file?

Am using a file to install keras because pypi/pip install is also giving me the same error as above.

**Comment by bennuttall** [comment]
Just need to know what happens when you run `pip3 -v` as above
