### ISSUE TITLE
Missing package:  opencv-python==3.4.2.17

### ISSUE THREAD

**Issue by Anastassiades** [piwheels/packages#101]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
#95
