### ISSUE TITLE
Missing package: igtools

### ISSUE THREAD

**Issue by JustAHackers** [piwheels/packages#104]
Package name: igtools
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/igtools
Link to piwheels page: https://www.piwheels.org/project/igtools
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
echo "fix it please"
```

```python
print("fix it asap please")
```

**Comment by bennuttall** [comment]
This package is not missing. What's the problem?

**Comment by bennuttall** [comment]
Oh I see. The package was deleted and re-registered. I'll delete the old versions.

**Comment by bennuttall** [comment]
No, just a load of dummy releases that got deleted from PyPI. I've deleted them piwheels now too.
