### ISSUE TITLE
missing package opencv-contrib-python for Python 3.8

### ISSUE THREAD

**Issue by obacht17** [piwheels/packages#106]
Package name: opencv-contrib-python
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/opencv-contrib-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python/
Version: 4.2.0.34, but basically any support for Python 3.8
Python version: e.g. 3.8
I am the maintainer: No
More information:

I successfully installed Python 3.8.2 on Raspbian 9 (stretch) using pyenv https://github.com/pyenv/pyenv.
In a pyenv-virtualenv environment, I try to install opencv-contrib-python using

```bash
pip3 install opencv-contrib-python
```

This results in the following error message:
```text
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-contrib-python
  ERROR: Could not find a version that satisfies the requirement opencv-contrib-python (from versions: none)
ERROR: No matching distribution found for opencv-contrib-python
```

On https://www.piwheels.org/project/opencv-contrib-python/, I am not able to find any version for Python 3.8.

**Comment by bennuttall** [comment]
We don't provide wheels for Python 3.8. We only build for Python versions in Raspbian.
