### ISSUE TITLE
Broken package: M2Crypto

### ISSUE THREAD

**Issue by merll** [piwheels/packages#110]
Package name: M2Crypto
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/M2Crypto/
Link to piwheels page: https://www.piwheels.org/project/M2Crypto/
Version: >=0.34.0
Python version: 3.7, 3.5
I am the maintainer: No
More information:

Attempt to install manually:
```bash
apt install libssl-dev
pip install M2Crypto

```
Compile fails with thousands of lines with just warning messages followed by
```
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```
but without further specification of the error.

However, [installation instructions](https://gitlab.com/m2crypto/m2crypto/-/blob/master/INSTALL.rst) list ``swig`` as a build-time dependency.

```
apt install libssl-dev swig
pip install M2Crypto
```
worked fine during my tests.

**Comment by bennuttall** [comment]
Thanks. Added swig to builders. It wasn't there before so I don't understand how the build succeeded on Jessie. I'm rebuilding the latest version on all - let's see what happens.

**Comment by bennuttall** [comment]
That succeeded on all. I'll rebuild all the old versions too, just in case.

**Comment by bennuttall** [comment]
All the recent (>=0.28.0) builds succeeded 👍
