### ISSUE TITLE
Missing package: msgpack

### ISSUE THREAD

**Issue by unrelatedlabs** [piwheels/packages#113]
Package name: msgpack
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/msgpack
Link to piwheels page: https://www.piwheels.org/project/msgpack
Version: all
Python version:  all
I am the maintainer: No
More information:
The builds are missing. The alternative that is available msgpack-python, is deprecated on PyPI

**Comment by bennuttall** [comment]
Thanks. It was marked as "deleted" as it had previously been deleted. I've un-marked it so it should get picked up soon.

**Comment by unrelatedlabs** [comment]
thanks, seem to work now
