### ISSUE TITLE
Missing package: pygame

### ISSUE THREAD

**Issue by illume** [piwheels/packages#114]
Package name: pygame
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/pygame
Link to piwheels page: https://www.piwheels.org/project/pygame
Version: 2.0.0.dev8 and python3.4 builds
Python version: all python versions on pygame 2.0.0.dev8 and python 3.4 on all pygame versions
I am the maintainer: Yes
More information:

Is there a log I can look at for making a fix?

**Comment by bennuttall** [comment]
👋 

**cp34**

Here's the build output from 2.0.0.dev6: http://paste.debian.net/1146529/

We're finding a lot of new releases don't support Python 3.4 any more, and we get hardly any cp34 downloads these days, so I wasn't worried.

**cp35/cp37**

It's not your problem, it's ours. I think I told you before, but we have been timing out calculating the build dependencies. We have a WIP fix but it's waiting on other stuff.

The last few versions I built myself offline, but I haven't got around to that yet. I will do shortly.

**Comment by bennuttall** [comment]
I've successfully built dev8 on stretch (cp35) and buster (cp37) and imported the files. I'll just sort out the dependencies so they show on the project page 👍

**Comment by bennuttall** [comment]
Done

**Comment by illume** [comment]
Thanks @bennuttall :)

**Comment by bennuttall** [comment]
Let me know if you have a source to test on cp34m.

We're going to drop support and stop building cp34m wheels next month, when Debian Jessie reaches EOL. Note Python 3.4 itself is now EOL too: https://python-release-cycle.glitch.me/

**Comment by bennuttall** [comment]
FYI @illume pygame 2.0 built fine on piwheels: https://piwheels.org/project/pygame/

**Comment by illume** [comment]
Great :)
