### ISSUE TITLE
Please patch tifffile to depend on imagecodecs-lite not imagecodecs

### ISSUE THREAD

**Issue by hmaarrfk** [piwheels/packages#115]
Package name: tifffile
Issue type: dependency too hard to build
Link to PyPI page:
https://pypi.org/project/tifffile/
https://pypi.org/project/imagecodecs/
https://pypi.org/project/imagecodecs-lite/

Link to piwheels page: https://www.piwheels.org/project/example
Version: recent
Python version: all
I am the maintainer: No, though downstream maintainer
More information:

Basically, imagecodecs is so hard to build due to all the additional c dependencies that it is almost guaranted to fail.
One fallback, is to use imagecodecs-lite
but I think the default dependency is imagecodecs

https://github.com/scikit-image/scikit-image/issues/4721#issuecomment-628862312

Could you patch tifffile to make it depend on imagecodecs-lite?

![image](https://user-images.githubusercontent.com/90008/81981381-13c5c900-95e5-11ea-8810-d4628d6e7db6.png)

cc @cgohlke

**Comment by bennuttall** [comment]
We can't modify the dependencies of a package. However, I've installed the right dependencies to fix the build for imagecodecs, so tifffile should install fine now.

**Comment by hmaarrfk** [comment]
awesome! Thanks!
