### ISSUE TITLE
Missing package: PyAudio

### ISSUE THREAD

**Issue by xgy995975102** [piwheels/packages#116]
Package name: PyAudio
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/PyAudio
Link to piwheels page: https://www.piwheels.org/project/PyAudio
Version: all
Python version: all
I am the maintainer: No

**Comment by bennuttall** [comment]
Please fill out the issue template in future

**Comment by bennuttall** [comment]
Builders were missing `portaudio19-dev`. Just tested on another Pi and managed to build it. Will install on the builders and kick off another build now.

**Comment by bennuttall** [comment]
The latest version has built successfully on Buster. The rest are in progress.

**Comment by bennuttall** [comment]
All done
