### ISSUE TITLE
piw removal

### ISSUE THREAD

**Issue by dontbmh** [piwheels/packages#118]
Package name: roseng
Link to PyPI page: https://pypi.org/project/roseng
Link to piwheels page: https://www.piwheels.org/simple/roseng
Version: e.g. 1.0, 1.1, 1.2
Python version: e.g. 3.5 or all
I am the maintainer: Yes
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
Done
