### ISSUE TITLE
Missing package: OctoBot-Trading

### ISSUE THREAD

**Issue by Herklos** [piwheels/packages#120]
Package name: OctoBot-Trading
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/OctoBot-Trading/
Link to piwheels page: https://www.piwheels.org/project/OctoBot-Trading/
Version: >= 1.3.1
Python version: 3.7
I am the maintainer: Yes ([DrakkarSoftware](https://github.com/Drakkar-Software) core developer)
More information:
Thank you for your awesome project !
We (the drakkar software team) would like to know why OctoBot-Trading package >= 1.3.1 builds are tagged "repeated timeout". We can help you to fix the issue if you have some information to share with us.

**Comment by bennuttall** [comment]
Sometimes the builders crash, and we check what they were building at the time, and if the same package comes up more than a couple of times, we skip it. It's hard to look into why, because the build output is lost on crash. I'll try and build this package manually and see if anything goes wrong.

**Comment by bennuttall** [comment]
It just built successfully for me in 73 mins, so I've removed the skip and will let it try again. Will take a while to get through them all, as it'll try and fail on cp34m and cp35m first, then should succeed on cp37m - but this is for every single missing version. Keep an eye on the project page for progress.

**Comment by bennuttall** [comment]
It's failed all versions so far. Currently on the latest version, which I built this afternoon, on what should have the same setup.

The failure of the previous version on Buster fell over at:

```
pkg_resources.ContextualVersionConflict: (Cython 0.29.17 (/tmp/pip-wheel-c3kdjsqt/OctoBot-Trading/.eggs/Cython-0.29.17-py3.7.egg), Requirement.parse('cython==0.29.19'), {'OctoBot-Backtesting', 'OctoBot-Channels', 'OctoBot-Commons'})
```

So looks like it's a slightly older cython?

**Comment by Herklos** [comment]
> It's failed all versions so far. Currently on the latest version, which I built this afternoon, on what should have the same setup.
> 
> The failure of the previous version on Buster fell over at:
> 
> ```
> pkg_resources.ContextualVersionConflict: (Cython 0.29.17 (/tmp/pip-wheel-c3kdjsqt/OctoBot-Trading/.eggs/Cython-0.29.17-py3.7.egg), Requirement.parse('cython==0.29.19'), {'OctoBot-Backtesting', 'OctoBot-Channels', 'OctoBot-Commons'})
> ```
> 
> So looks like it's a slightly older cython?

Thanks for the details. Concerning the previous versions there was an issue with the cython version. It should be ok for on now.

**Comment by bennuttall** [comment]
Weird. The only ABI/version combo I tried built successfully, so I let the builders try them all, and it was literally the only one that succeeded. Is that ok, or do you want to investigate the other versions?

**Comment by Herklos** [comment]
> Weird. The only ABI/version combo I tried built successfully, so I let the builders try them all, and it was literally the only one that succeeded. Is that ok, or do you want to investigate the other versions?

It's ok, we wanted to investigate the last version. Thanks !

**Comment by bennuttall** [comment]
👍

**Comment by Herklos** [comment]
Hi ! It worked well until recent releases (1.8.9 and 1.8.10). We didn't add significant changes. Can we help you to fix these builds ?

**Comment by bennuttall** [comment]
```
RuntimeError: Building NumPy requires Cython >= 0.29.21
```

**Comment by bennuttall** [comment]
Related to #133

**Comment by bennuttall** [comment]
It's built now

**Comment by Herklos** [comment]
Thanks !
