### ISSUE TITLE
OpenCV Headless version linked against GUI library

### ISSUE THREAD

**Issue by walchko** [piwheels/packages#122]
Package name: opencv-python-headless
Link to PyPI page: https://pypi.org/project/opencv-python-headless/
Link to piwheels page: https://www.piwheels.org/project/opencv-python-headless/
Version: e.g. 4.1.1.26
Python version: e.g. 3.7
I am the maintainer: No
More information:

### Expected behaviour

I installed the headless version on a Raspberry Pi and `cv2` crashes because it was linked to a GUI library, libgtk-3 ... seems like an error. I am using the `lite` version with no desktop installed ... doing embedded work.

version: opencv-python-headless 4.1.1.26

```
uname -a
Linux mote 5.4.44-v7+ #1320 SMP Wed Jun 3 16:07:06 BST 2020 armv7l GNU/Linux
```

```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
python --version
Python 3.7.3
```

### Actual behaviour

Crashed:

```
Traceback (most recent call last):
  File "./cam.py", line 4, in <module>
    import cv2
  File "/home/pi/venv/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

### Steps to reproduce

Install headless version and try to load `cv2` ... it will crash without the desktop installed.

**Comment by walchko** [comment]
so doesn't anyone maintain this package?

**Comment by walchko** [comment]
looking around some more, @waveform80 was asked a similar question about the headless package on an earlier version ... does @waveform80 maintain this package? If not, I am unclear how I could help. I have done this before on my own and you just need to add `-D WITH_QT=OFF  -D WITH_GTK=OFF` to your `cmake` call ... easy!

- link to [script](https://github.com/MomsFriendlyRobotCompany/dpkg_opencv/blob/master/opencv4/build-opencv.sh) I have used before to do this on my own :smile:

**Comment by bennuttall** [comment]
@waveform80 built the opencv wheels for piwheels. He's aware of the issue but he's busy.

**Comment by walchko** [comment]
ok .. thanks! :smile:

**Comment by bennuttall** [comment]
The latest version is now available
