### ISSUE TITLE
opencv-python: can't find libjasper1

### ISSUE THREAD

**Issue by clambin** [piwheels/packages#123]
Link to piwheels page: https://www.piwheels.org/project/opencv-python/
Version: 3.4.6.27
Python version: 3.7
I am the maintainer: No
More information:

Trying to build a docker image with this wheel included, but installation fails because it can't find libjasper1.   Key points from the dockerfile:

FROM arm32v7/python:3.7-slim
...
RUN pip3 install --no-cache-dir opencv-python==3.4.6.27
...
RUN apt-get install -y libjasper1

Building the docker image gives:

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libjasper1

Looking through the packages on the debian repo, indeed it seems libjasper1 doesn't exist for buster.

**Comment by bennuttall** [comment]
We currently don't show deps per file - so these could be for a different files. I should be able to look up the deps later but if you want to find them now you can follow this guide: https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/

**Comment by clambin** [comment]
OK thanks. Did that:

# /usr/local/lib/python3.7/site-packages/cv2# ldd /usr/local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so | grep "not found"
	libjasper.so.1 => not found
# apt install libjasper.so.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libjasper.so.1
E: Couldn't find any package by glob 'libjasper.so.1'
E: Couldn't find any package by regex 'libjasper.so.1'

No package provides that library. My sources:
# cat /etc/apt/sources.list
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z buster main
deb http://deb.debian.org/debian buster main
# deb http://snapshot.debian.org/archive/debian-security/20200607T000000Z buster/updates main
deb http://security.debian.org/debian-security buster/updates main
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z buster-updates main
deb http://deb.debian.org/debian buster-updates main


The instructions on https://www.piwheels.org/project/opencv-python/ do mention to install it as a dependency, but seems buster doesn't provide it?

**Comment by bennuttall** [comment]
You seem to have stopped after the first step. You need to read on, continuing with the step that says "To find out which apt packages provide this `.so`, use apt-file..."

**Comment by clambin** [comment]
You're right.  Multitasking is not a good idea.  But even after installing apt-file & running apt-file update:

```
# apt-file update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
# apt-file search libjasper.so.1
#
```

Looks like buster simply doesn't have any packages providing libjasper.so.1.

**Comment by clambin** [comment]
hmm ... I think this is probably related to the docker image I'm using as a base ...

Inside the docker image:

```
# cat /etc/apt/sources.list
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z buster main
deb http://deb.debian.org/debian buster main
# deb http://snapshot.debian.org/archive/debian-security/20200607T000000Z buster/updates main
deb http://security.debian.org/debian-security buster/updates main
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z buster-updates main
deb http://deb.debian.org/debian buster-updates main
#  apt-file search libjasper.so.1
#
```

but on the Pi itself:

```
$ cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Added for docker
deb https://download.docker.com/linux/raspbian/ stretch stable
$ sudo apt-file search libjasper.so.1
libjasper1: /usr/lib/arm-linux-gnueabihf/libjasper.so.1
libjasper1: /usr/lib/arm-linux-gnueabihf/libjasper.so.1.0.0
```

So the docker image (arm32v7/python:3.7-slim) uses debian , but Pi uses its own sources, which does provide the library in question.

**Comment by clambin** [comment]
Managed to get it to work by adding the raspbian repo to apt.  Thanks for your helping in getting me there!
