### ISSUE TITLE
Missing package: pylibmc

### ISSUE THREAD

**Issue by thrynir** [piwheels/packages#128]
Package name: pylibmc
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pylibmc
Link to piwheels page: https://www.piwheels.org/project/pylibmc
Version: all
Python version: all
I am the maintainer: No
More information:

Piwheel reports Failed builds for cp34m, cp35m, cp37m.

**Comment by bennuttall** [comment]
Thanks for filling out the template :100: 

Here's the build log for the latest version on Buster: https://paste.debian.net/1155449

The error is:

```
src/_pylibmcmodule.h:42:10: fatal error: libmemcached/memcached.h: No such file or directory
```

**Comment by bennuttall** [comment]
Looks like it needs this package: https://packages.debian.org/source/buster/libmemcached

I'll try building it

**Comment by bennuttall** [comment]
Yep that worked - I'll add it to the builders now and kick it back off

**Comment by bennuttall** [comment]
The latest versions have built successfully, so I've kicked off the rest. Note they won't be attempted on cp34m any more as Jessie's EOL now.

**Comment by thrynir** [comment]
Hi, thanks for all
