### ISSUE TITLE
Pillow : missing lib

### ISSUE THREAD

**Issue by thrynir** [piwheels/packages#129]
Package name: Pillow 
Link to PyPI page: https://pypi.org/project/pillow
Link to piwheels page: https://www.piwheels.org/project/pillow
Version: 7.2
Python version: 3.7
I am the maintainer: No
More information:

Hi,

Wheels add a directory pillows.libs to add all requested libraries to run pillow. But you are asking to install it with apt.
Can I ask why you choose that way ?

**Comment by bennuttall** [comment]
When we build a wheel, we run [this process](https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/) on the file to see which libraries are required, and which packages provide them.

What do you mean by this?

> Wheels add a directory pillows.libs to add all requested libraries to run pillow

**Comment by thrynir** [comment]
Well, maybe I just don't understand the all process.

My issue is if I run a pip install pillow on x86-x64 I get 3 directories in dist-packages PIL, Pillow.libs and Pillow-7.2.0-dist-info

With piwheels, I only get PIL and Pillow-7.2.0-dist-info and so I can't import PIL as there is some missing librairies.
As you explain in piwheels page (https://www.piwheels.org/project/Pillow/) I have to install all the libraries manualy with apt.
Except I would like ta have the same process I have with x86-x64.

What I missed ?

**Comment by bennuttall** [comment]
piwheels is an automated system - we run `pip wheel package==version` for every version of every package and make the resulting wheel file available for download. We don't really have the ability to customise the build. It looks like pillow provide a build option which bundles the dependencies, and the x86_64 wheel they provide for Linux has been built this way, but piwheels doesn't.

**Comment by thrynir** [comment]
Ok, thanks for your answer
