### ISSUE TITLE
Missing package: cryptoauthlib 20190304

### ISSUE THREAD

**Issue by bryan-hunt** [piwheels/packages#13]
Missing package
Package name: cryptoauthlib
Link to PyPI page: https://pypi.org/project/cryptoauthlib
Link to piwheels page: https://www.piwheels.org/project/cryptoauthlib
Version: 20190304
Python version: all
More information:

There are no wheels available (it should build 3.5 wheels) but no failures or skips either.

**Comment by bennuttall** [comment]
Successfully built on 3.5 and 3.7! :fireworks: https://www.piwheels.org/project/cryptoauthlib
