### ISSUE TITLE
Missing package: PyBluez

### ISSUE THREAD

**Issue by everettljohnson** [piwheels/packages#131]
Package name: pybluez
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/PyBluez/
Link to piwheels page: https://www.piwheels.org/project/PyBluez/
Version:  all
Python version: all
I am the maintainer: No
More information:

PyBluez is listed in the package list on piwheels.org, but it appears that all of the wheel files have been deleted.

**Comment by bennuttall** [comment]
Thanks. Looks like the package was previously deleted, and we hadn't updated when it had been re-created. I've marked it as not deleted and all versions have now been built.
