### ISSUE TITLE
Missing package: qiskit-aer

### ISSUE THREAD

**Issue by mtreinish** [piwheels/packages#132]
Package name: qiskit-aer
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/qiskit-aer/
Link to piwheels page: https://www.piwheels.org/project/qiskit-aer/
Version: >= 0.3.2
Python version: >=3.5
I am the maintainer: Yes
More information:

I assume this is a dependency problem there are a few external dependencies required for building.

**Comment by bennuttall** [comment]
Here's the build output: https://paste.debian.net/1155876/

It's missing a Rust compiler. Is there a Debian package that'll resolve that?

**Comment by mtreinish** [comment]
Hmm, interesting that's actually caused by retworkx (see #99) which is a second level dependency of qiskit-aer (from qiskit-terra which is the direct dependency). But neither should only be an install time dep, not really a build time dep. qiskit-aer itself is written in C++ so it doesn't need the rust compiler to build.

That being said I have been making progress on getting #99 resolvable, once https://github.com/Qiskit/retworkx/pull/91 merges I'll push out a 0.4.0 release and then the builds for retworkx 0.4.0 should work with the `rustc` package (and probably `cargo` too) from debian testing or unstable (the version in buster unfortunately is too old). It's currently blocked waiting for a release from the rust numpy binding lib (I was going to update #99 after I pushed the retworkx release).

**Comment by mtreinish** [comment]
Yeah, I just took a look at the package metadata is incorrectly saying all the install time dependencies should be also be build dependencies: https://github.com/Qiskit/qiskit-aer/blob/master/setup.py#L30-L47 It's true for all of the things in that install requirements list except for qiskit-terra, I'll update the package metadata to make that distinction which should be fixed in the next release, so qiskit-terra and therefore retworkx don't try to get installed for just a wheel build. Then hopefully the builds will work again, but I suspect something else will block it because qiskit-terra was only added as an explicit dependency in 0.4.2 (it was implicitly assumed to be installed prior to that) but the builds still failed before 0.3.2 and then.

**Comment by mtreinish** [comment]
@bennuttall there were 2 new releases in the past few days for qiskit-aer (0.6.0 and 0.6.1). It should be fixed to not incorrectly pull in qiskit-terra (and retworkx as a second level dep) now. The builds are still listed as failed on https://www.piwheels.org/project/qiskit-aer/ is there an updated error now?

**Comment by bennuttall** [comment]
Here you go: https://paste.debian.net/1160051/

Looks like:

```
Traceback (most recent call last):
2020-08-10T18:29:53,614       File "/tmp/pip-wheel-1luxfcde/qiskit-aer/setup.py", line 15, in <module>
2020-08-10T18:29:53,614         from conans import client
2020-08-10T18:29:53,614     ModuleNotFoundError: No module named 'conans'

2020-08-10T18:29:53,615     During handling of the above exception, another exception occurred:

2020-08-10T18:29:53,616     Traceback (most recent call last):
2020-08-10T18:29:53,616       File "<string>", line 1, in <module>
2020-08-10T18:29:53,617       File "/tmp/pip-wheel-1luxfcde/qiskit-aer/setup.py", line 18, in <module>
2020-08-10T18:29:53,617         from conans import client
2020-08-10T18:29:53,617     ModuleNotFoundError: No module named 'conans'
```

**Comment by bennuttall** [comment]
Update: I installed cargo, setuptools_rust and conan - and it seems to have done the trick. I managed to build 0.7.2 offline and piwheels is working on them all now. It's built up to version 0.5.2 so far and still working on the rest. Should be done in the next few hours, keep an eye on the project page for updates: https://www.piwheels.org/project/qiskit-aer/

**Comment by bennuttall** [comment]
We're good. The last few versions built successfully.

:partying_face:
