### ISSUE TITLE
PyNaCl not installing

### ISSUE THREAD

**Issue by henryse** [piwheels/packages#135]
I'm trying to install docker-compose on my new RPI4 but I'm getting the following error:

The version of Linux: Linux neo 5.4.51-v7l+ #1326 SMP Fri Jul 17 10:51:18 BST 2020 armv7l GNU/Linux

```bash
pi@neo:~ $ pip3 install pynacl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pynacl
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pynacl/
```

```bash
pi@neo:/etc $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: d03114
Serial		: 1000000098139ee9
Model		: Raspberry Pi 4 Model B Rev 1.4
```

**Comment by sk33z3r** [comment]
I was in the midst of gathering info and reporting the same issue, I'm also trying to setup my Pi 4b with `docker-compose` to no avail.

I also attempted earlier versions of compose (`1.25.5` and `1.24.1`) with the same error.

**Comment by BionicWeb** [comment]
I have the same issue, was working earlier in the day and then started failing. Raspberry Pi 4 Model B. Fresh install of Pi OS.

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pynacl/

**Comment by NinjaJake86** [comment]
I'm getting the same issue installing odoo in a venv

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pynacl/

**Comment by micheldewinter** [comment]
Same issue over here. Raspberry Pi 3b rev1.2

**Comment by TheokieZA** [comment]
In the mean time I just commented all the lines in /etc/pip.conf and it compiles, until this issue is resolved.

**Comment by bennuttall** [comment]
Fixed

**Comment by bennuttall** [comment]
Someone had issues yesterday with `pynacl` not finding any files, because it had previously been registered (and later deleted) as lowercase, and that was getting in the way. But I forgot I needed to replace it with a symlink after deleting the lowercase version.
