### ISSUE TITLE
Missing package: Simplification

### ISSUE THREAD

**Issue by BArratia-CL** [piwheels/packages#136]
Package name: Simplification
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/simplification
Link to piwheels page: https://www.piwheels.org/project/simplification
Version: all
Python version: all
I am the maintainer: No
More information:

There is no files available for download :(

**Comment by bennuttall** [comment]
There's no source distribution provided, you'll have to take it up with the maintainers.
