### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.1.1.26

### ISSUE THREAD

**Issue by Raj160907** [piwheels/packages#137]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by Raj160907** [comment]
ERROR: No matching distribution found for opencv-contrib-python==4.1.1.26

**Comment by Raj160907** [comment]
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.1.1.26

**Comment by wcschroe** [comment]
Same issue here on a Raspberry Pi 4 running Debian GNU/Linux 5.4.51-v8+ aarch64
Followed the instructions at [https://www.piwheels.org/project/opencv-contrib-python/](https://www.piwheels.org/project/opencv-contrib-python/) with no errors until the pip install

![image](https://user-images.githubusercontent.com/8304562/89134142-5e196080-d4d7-11ea-8b5a-f1841459794c.png)

**Comment by bennuttall** [comment]
@Raj160907 you haven't filled out the issue template, you haven't given me anything to go on.

Are you running aarch64 like @wcschroe? Note that we don't currently support aarch64 as per pinned issue #119.
