### ISSUE TITLE
Brotli 1.0.7 for Python 3.6 Wheel file

### ISSUE THREAD

**Issue by Mahmoud-Elsousy** [piwheels/packages#138]
Package name: Brotli
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/Brotli
Link to piwheels page: https://www.piwheels.org/project/Brotli
Version: 1.0.7
Python version:  3.6
I am the maintainer: No
More information:

I have compiled a python wheel for this package on BeagleBone AI, would love if it can be uploaded to your project:
Here is the wheel file:
https://gofile.io/d/QobP37

**Comment by bennuttall** [comment]
Sorry we don't support Python 3.6, only Python versions in Debian releases.
