### ISSUE TITLE
Python 3.8 versions for libraries

### ISSUE THREAD

**Issue by charlesoblack** [piwheels/packages#139]
Is it possible to get Python 3.8 builds for libraries, as well as 3.7?

**Comment by bennuttall** [comment]
No sorry we can only support versions of Python in Debian releases.

**Comment by domdfcoding** [comment]
Debian Bullseye has Python 3.9 as its default and Ubuntu 20.04 has Python 3.8

**Comment by bennuttall** [comment]
We won't build for Ubuntu, and we'll build for Bullseye once it comes out / is available on [Mythic](https://www.mythic-beasts.com/order/rpi).
