### ISSUE TITLE
Missing package: sklearn

### ISSUE THREAD

**Issue by deepunamb** [piwheels/packages#14]
Missing package
Package name: sklearn
Link to PyPI page: https://pypi.org/project/scikit-learn
Link to piwheels page: https://www.piwheels.org/project/scikit-learn

**Comment by bennuttall** [comment]
Successfully built on 3.5 and 3.7 :fireworks: https://www.piwheels.org/project/scikit-learn

**Comment by sakethramanujam** [comment]
Seems like 0.22.0 isn't available on armv7, is there a way to build the package myself?
