### ISSUE TITLE
Missing package: pyzmq

### ISSUE THREAD

**Issue by tomflannaghan** [piwheels/packages#140]
Hi, I noticed that pyzmq version 19.0.2 is missing.

Package name: pyzmq
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pyzmq/
Link to piwheels page: https://www.piwheels.org/project/pyzmq/
Version: 19.0.2
Python version: all
I am the maintainer: No
More information:

**Comment by bennuttall** [comment]
Thanks - it's built now
