### ISSUE TITLE
Attempting to install VL53L1X results in 404 error

### ISSUE THREAD

**Issue by Gadgetoid** [piwheels/packages#145]
Package name: VL53L1X
Link to PyPI page: https://pypi.org/project/VL53L1X/
Link to piwheels page: https://www.piwheels.org/project/VL53L1X/
Version: all, latest?
Python version: all
I am the maintainer: Yes

More information:

Attempting to `pip install VL53L1X` results in a 404 error against PiWheels due to some weird case-sensitivity error, eg:

```
pi@raspberrypi:~/ $ pip3 install vl53l1x
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vl53l1x
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/vl53l1x/
```

Okay fair enough the "simple" URL is uppercase - https://www.piwheels.org/simple/VL53L1X/ - so let's use that package name:

```
pi@raspberrypi:~/ $ pip3 install VL53L1X
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting VL53L1X
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/vl53l1x/
```

Uh... wat?

Why isn't `https://pypi.org/simple/vl53l1x/` being found?

Notably also if I visit the url `https://pypi.org/simple/VL53L1X/` it will convert it to the lowercase one mentioned above.

PiWheels.org should canonicalise on lowercase package names and follow the example of PyPI.

(Yes don't get me started on me naming my package wrong, I KNOW!)

**Comment by bennuttall** [comment]
We do canonicalise, but we've recently been going through removing historically deleted packages and there are some complexities with that process, such as this. Will sort this one out soon.

**Comment by Gadgetoid** [comment]
D'oh! Okay. Thank you!

**Comment by bennuttall** [comment]
Should work now

**Comment by Gadgetoid** [comment]
Confirmed, thank you for jumping on this so quickly!

```
pi@raspberrypi:~/ $ pip3 install vl53l1x
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vl53l1x
  Downloading https://files.pythonhosted.org/packages/df/05/7aff24243ae12ac1b8b1f1721e9ee6460be7373f71cce795fe2b79bae2d7/VL53L1X-0.0.5-cp37-cp37m-linux_armv7l.whl (149kB)
    100% |████████████████████████████████| 153kB 1.3MB/s
Collecting smbus2 (from vl53l1x)
  Downloading https://www.piwheels.org/simple/smbus2/smbus2-0.3.0-py2.py3-none-any.whl
Installing collected packages: smbus2, vl53l1x
Successfully installed smbus2-0.3.0 vl53l1x-0.0.5
```

Actually surprised `pip` breaks like this, rather than falling back!

**Comment by bennuttall** [comment]
It's not surprising really. You can't fall back from canonicalised (all lowercase) to all alternatives!
