### ISSUE TITLE
Missing meaningcloud-python 

### ISSUE THREAD

**Issue by mungle** [piwheels/packages#146]
Package name: meaningcloud-python 
Issue type: Missing package
Link to GitHub page: https://github.com/MeaningCloud/meaningcloud-python
Link to piwheels page: https://www.piwheels.org/project/MeaningCloud-python/
Link to piwheels page: https://www.piwheels.org/project/meaningcloud-python/
Version: all
Python version: all
I am the maintainer: No

**Comment by mungle** [comment]
Please Forget... Just saw after hours of research that the link is case sensitive

https://www.piwheels.org/project/MeaningCloud-python/

**Comment by bennuttall** [comment]
The lowercase one should work now
