### ISSUE TITLE
Missing package: Flask-BasicAuth

### ISSUE THREAD

**Issue by selepaul** [piwheels/packages#147]
Package name: Flask-BasicAuth
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/Flask-BasicAuth/
Link to piwheels page: https://www.piwheels.org/project/Flask-BasicAuth/
Version: ?
Python version: 3
I am the maintainer: No

**Comment by bennuttall** [comment]
Thanks for the report - it was a missing symlink to the canonical form which I've now created: https://www.piwheels.org/simple/flask-basicauth/
