### ISSUE TITLE
Missing package: Flask-Humanize

### ISSUE THREAD

**Issue by Ivangel1972** [piwheels/packages#148]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
sudo pip3 install Flask-Humanize
```
Collecting flask-humanize (from birdseye)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/flask-humanize/

sudo pip3 install Flask-Humanize

```python
print("code here")
```

**Comment by bennuttall** [comment]
Should be fixed now - can you confirm?

**Comment by bennuttall** [comment]
We processed some deletions recently, and there are some packages which got deleted and then re-created, which caused some links to go missing.

**Comment by Ivangel1972** [comment]
> We processed some deletions recently, and there are some packages which got deleted and then re-created, which caused some links to go missing.

Thanks very much, greetings
