### ISSUE TITLE
Case-Sensitive package fails install

### ISSUE THREAD

**Issue by dkumor** [piwheels/packages#149]
Package name: SoundCard
Link to PyPI page: https://pypi.org/project/SoundCard/
Link to piwheels page: https://www.piwheels.org/project/SoundCard
Version: 0.4.0
Python version: all
I am the maintainer: No
More information:

I maintain a library that is dependent on SoundCard. A couple days ago, users started reporting that installation was failing (https://github.com/dkumor/rtcbot/issues/16 https://github.com/bastibe/SoundCard/issues/107)

The issue seems to be that piwheels became case-sensitive, while pip attempts to install using lowercase:
```
$ sudo pip3 install SoundCard
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting SoundCard
Could not install packages due to an EnvironmentError: 403 Client Error: Forbidden for url: https://www.piwheels.org/simple/soundcard
```

The url https://www.piwheels.org/simple/soundcard gives an error, but https://www.piwheels.org/simple/SoundCard does not...

**Comment by bennuttall** [comment]
Thanks. This is fixed now. It seems `soundcloud` was created and deleted before `SoundCloud` was created. We processed some deletions recently and it left a few missing links. Will be sorted all-round once this PR is merged and deployed: https://github.com/piwheels/piwheels/pull/256
