### ISSUE TITLE
Missing package: Pygame 1.9.6 and 2.0.0.dev1

### ISSUE THREAD

**Issue by illume** [piwheels/packages#15]
Missing package
Package name: pygame
Link to PyPI page: https://pypi.org/project/pygame
Link to piwheels page: https://www.piwheels.org/project/pygame
Version: 1.9.6
Python version: all
More information:

**Comment by bennuttall** [comment]
Imported: https://www.piwheels.org/project/pygame/ :+1:

**Comment by illume** [comment]
Awesome. Thanks :)

Do you need help figuring out that issue, or was it just a hiccup?

**Comment by bennuttall** [comment]
No, that's fine. It's not an issue with pygame, just pygame having so many dependencies made it an edge case!
