### ISSUE TITLE
Missing package: ExifRead

### ISSUE THREAD

**Issue by Stonec56** [piwheels/packages#150]
Package name: ExifRead
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/ExifRead
Link to piwheels page: https://www.piwheels.org/project/ExifRead
Version: all
Python version: all
I am the maintainer: No
More information:
sudo pip3 install ExifRead

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/exifread/

**Comment by bennuttall** [comment]
I've fixed the 404 so it should get the files from PyPI now but the fix for the fact we have no files is pending deployment of https://github.com/piwheels/piwheels/pull/256

Will leave this open until it's sorted

**Comment by bennuttall** [comment]
Actually I've fixed it now
