### ISSUE TITLE
Flask-Table 404s

### ISSUE THREAD

**Issue by tweirtx** [piwheels/packages#152]
Package name: Flask-Table
Link to PyPI page: https://pypi.org/project/Flask-Table
Link to piwheels page: https://www.piwheels.org/project/Flask-Table
Version: 0.5.0
Python version: Only tested on 3.7
I am the maintainer: No
More information: Running ```bash
pip3 install Flask-Table``` returns:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Flask-Table
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/flask-table/

**Comment by bennuttall** [comment]
Fixed now. We've seen this with a few packages lately, any that have been historically re-registered with a change to lower/upper case characters. So flask-table was previously deleted, leaving no link to Flask-Table.
