### ISSUE TITLE
RPi.bme280

### ISSUE THREAD

**Issue by SvenTaveby** [piwheels/packages#154]
Package name: example
Link to PyPI page: https://pypi.org/project/RPi.bme280
-- | --
Link to piwheels page: https://www.piwheels.org/simple/rpi-bme280/
Version:  all
Python version: 3.7
I am the maintainer: No
More information:
403 Client Error: Forbidden for url: https://www.piwheels.org/simple/rpi-bme280/
Please use code blocks where appropriate:

```bash
command line commands here
```
sudo pip3 install RPi.bme280
```python
print("code here")
```

**Comment by bennuttall** [comment]
Fixed - we purged a bunch of deleted packages recently and sometimes when multiple packages with the same name (when canonicalised, like RPI.bme280 == rpi-bme280) were registered and deleted.
