### ISSUE TITLE
Can't access https://www.piwheels.org/simple/pbkdf2/

### ISSUE THREAD

**Issue by ChrisFullerAtLondon** [piwheels/packages#155]
when installing wifi package on RPI Zero W  I get error at the line Collecting pkddf2 (from wifi)

Package name: **pbkdf2**
Issue type: **Can't access package**
Link to PyPI page: https://pypi.org/project/pbkdf2 **This link is OK**
Link to piwheels page: https://www.piwheels.org/project/pbkdf2 **This is OK**
Version: e.g. 1.2.3 or all **pip version 18.1**
Python version: e.g. 3.7 or all **python version 3.7**
I am the maintainer: Yes/No **Yes**
More information:

When I try to access the package as part of my call to...
sudo pip install wifi

I get a message "Could not install packages due to environment error:403 Client Error Forbidden for url:https://www.piwheels.org/simple/pbkdf2/

when I put that url into a browser I get a message:

Forbidden

You don't have permission to access this resource.

Apache/2.4.38 (Raspbian) Server at www.piwheels.org Port 443

**Comment by bennuttall** [comment]
Fixed.

Did you recently delete the package from PyPI? We just processed some deletions, so if you re-created it straight after deleting, that would explain it.

Please note it really helps if you fill out the issue template properly.

**Comment by ChrisFullerAtLondon** [comment]
I didn't delete anything. 

But I see the link now works. So thanks for that
