### ISSUE TITLE
Incompatible package: traitlets (pure Python package)

### ISSUE THREAD

**Issue by carlosperate** [piwheels/packages#156]
**Package name:** traitlets
**Issue type:** Package is in PiWheels in several (working) versions, but when adding PiWheels as an extra index it installs a version of the package incompatible with the python version running pip.
**Link to PyPI page:** https://pypi.org/project/traitlets/
**Link to piwheels page:** https://www.piwheels.org/project/traitlets/
**Version:** >=5.0.0b1 added a Python3.7+ requirement
**Python version:** <3.7
**I am the maintainer:** No
**More information:**
Without PiWheels with Python 3.6 in a Linux distro running on Arm `python3 -m pip install traitlets` installs v4.3.3, the last version compatible with Py3.6. With PiWheels in the same Python environment (`python3 -m pip install traitlets --extra-index-url https://www.piwheels.org/simple`) it installs the latest v5.0.4.

I first thought maybe the wheel naming needs to specify Python version compatibility but both PyPI and PiWheels has the wheel filename as `-py3-none-any.whl`. Is PyPI reading the wheel metadata to identify compatible Python versions?
The wheel itself does have the `Requires-Python: >=3.7` attribute added.

**Comment by carlosperate** [comment]
Just noticed this in the main PiWheels issue tracker: https://github.com/piwheels/piwheels/issues/208
Sounds like this is exactly the issue here.

**Comment by bennuttall** [comment]
Yeah that's it. I've got a fix ready in https://github.com/piwheels/piwheels/pull/254 but that's waiting on another couple of PRs. Should be done soonish.

**Comment by carlosperate** [comment]
Looking forward to the fix making into piwheels!
Anything we can do to help?

**Comment by bennuttall** [comment]
This is now fixed:

```
<a href="traitlets-5.0.0-py3-none-any.whl#sha256=62a037f12ccb823fb05823afbe35fe0273bc18fa3202d0cf0ea8f24e97e464be" data-requires-python="&gt;=3.7">traitlets-5.0.0-py3-none-any.whl</a><br>
<a href="traitlets-5.0.0b1-py3-none-any.whl#sha256=c6ec96486dacf8f9374a06f23553f71029f8d60255ccf630fd30c0fc7c7751b0" data-requires-python="&gt;=3.7">traitlets-5.0.0b1-py3-none-any.whl</a><br>
<a href="traitlets-5.0.0rc2-py3-none-any.whl#sha256=d56e45db33a0f37ffa3cc4cfa439fc09ed2906e228d0f28310fcd42a19facdce" data-requires-python="&gt;=3.7">traitlets-5.0.0rc2-py3-none-any.whl</a><br>
<a href="traitlets-5.0.2-py3-none-any.whl#sha256=613da6efe96bdb4288c72dc65bc82c53320994b1702c6803150e0d2b21f83216" data-requires-python="&gt;=3.7">traitlets-5.0.2-py3-none-any.whl</a><br>
<a href="traitlets-5.0.3-py3-none-any.whl#sha256=8bdadb17a04c844f444cdefaa3dee47a12ff14cf6277b9eeda29bfa0659d5987" data-requires-python="&gt;=3.7">traitlets-5.0.3-py3-none-any.whl</a><br>
<a href="traitlets-5.0.4-py3-none-any.whl#sha256=9664ec0c526e48e7b47b7d14cd6b252efa03e0129011de0a9c1d70315d4309c3" data-requires-python="&gt;=3.7">traitlets-5.0.4-py3-none-any.whl</a><br>
```

https://www.piwheels.org/simple/traitlets/

**Comment by carlosperate** [comment]
Awesome, thanks Ben! I can confirm a pip install on Raspbian/Raspbery Pi OS runs without issues. 🎉
