### ISSUE TITLE
Missing package: numpy v1.19.2

### ISSUE THREAD

**Issue by carlosperate** [piwheels/packages#157]
Package name: numpy v1.19.2
Issue type: Version missing
Link to PyPI page: https://pypi.org/project/numpy/1.19.2/
Link to piwheels page: https://www.piwheels.org/project/numpy/
Version: 1.19.2
Python version: all
I am the maintainer: No
More information:

It just came out a couple of days ago.

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/4189262/92995417-6ebbee00-f4fb-11ea-9b9c-1ea4459aae67.png">

**Comment by bennuttall** [comment]
Yeah it'll be in the queue. We unlocked a load of previously deleted packages the other day and ended up with a load of packages entering the queue, so it's in there. Should get to it today, I'll keep an eye out.

**Comment by carlosperate** [comment]
Great, thanks Ben!

**Comment by bennuttall** [comment]
It's built now :rocket:
