### ISSUE TITLE
Missing package: cffi v1.14.2

### ISSUE THREAD

**Issue by carlosperate** [piwheels/packages#158]
Package name: cffi
Issue type: v1.14.2 of package missing
Link to PyPI page: https://www.pypi.org/project/cffi/
Link to piwheels page: https://www.piwheels.org/project/cffi
Version: v1.14.2 
Python version: all
I am the maintainer: No
More information:

Please use code blocks where appropriate:

I'm aware there is currently a queue, but this package came out almost a month ago, so maybe it's not currently in queue?

<img width="826" alt="image" src="https://user-images.githubusercontent.com/4189262/93001811-975adc80-f529-11ea-9bf3-287aa8dc7e6a.png">

**Comment by bennuttall** [comment]
Hmm that is odd. It didn't get picked up by the cloud gazer (the task that monitors PyPI releases). If it was just in the build queue it show the version number with no build entries in the versions table. But it's just not there.

I've not seen a version not make it through the cloud gazer before. I've manually added it so the builders should pick it up. In fact I can see it being built on Stretch already, and it'll then progress to Buster, but there's a queue at the moment so it'll be later tonight.

**Comment by bennuttall** [comment]
Done!
