### ISSUE TITLE
Missing package: DeeFuzzer

### ISSUE THREAD

**Issue by felisuky** [piwheels/packages#159]
Package name: Deefuzzer
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/DeeFuzzer
Link to piwheels page: https://www.piwheels.org/project/DeeFuzzer
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: No
More information:

```
------------------
pi@raspberrypi:~ $ sudo pip3 install DeeFuzzer
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting DeeFuzzer
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/deefuzzer/
---------------------------------
```

**Comment by bennuttall** [comment]
Fixed
