### ISSUE TITLE
virtualenvwrapper 5.0.0 should be removed from piwheels.org

### ISSUE THREAD

**Issue by dhellmann** [piwheels/packages#164]
Package name: virtualenvwrapper
Link to PyPI page: https://pypi.org/project/virtualenvwrapper/
Link to piwheels page: https://www.piwheels.org/project/virtualenvwrapper/
Version: 5.0.0
Python version: all
I am the maintainer: Yes
More information:

The 5.0.0 version had a serious bug that made it unusable. It was yanked from PyPI ages ago. I've had a bug report from a user that running `pip3 install virtualenvwrapper` on a raspberrypi still causes the old package to be installed because pip is finding the 5.0.0 package on piwheels.org.

Please remove 5.0.0 from the cache.

**Comment by bennuttall** [comment]
That's weird. We only added deletion recently (long story) but it should have removed this.

Anyway - I've removed it now. Thanks for letting us know.

**Comment by dhellmann** [comment]
Thanks for the quick response! I hadn't heard of piwheel.org before, but it seems like a really nice service for the community. :-)

**Comment by bennuttall** [comment]
Thanks!
