### ISSUE TITLE
Missing package: nsepython

### ISSUE THREAD

**Issue by PRAKSH24884** [piwheels/packages#168]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
It's not missing: https://www.piwheels.org/project/nsepython/

You didn't fill out the issue template and you haven't provided any further information.
