### ISSUE TITLE
No matching distribution found for opencv-contrib-python

### ISSUE THREAD

**Issue by VidhuPradhan** [piwheels/packages#169]
downloaded the whl file -opencv_contrib_python-4.4.0.44-cp38-cp38-win_amd64.whl (40.2 MB) from site https://pypi.org/project/opencv-contrib-python/#files and ran the command pip install <file name>
but faced the below error

C:\Users\dell\Downloads>pip install opencv-contrib-python
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python (from versions: none)
ERROR: No matching distribution found for opencv-contrib-python

C:\Users\dell\Downloads>pip install opencv_contrib_python-4.4.0.44-cp38-cp38-win_amd64.whl
ERROR: opencv_contrib_python-4.4.0.44-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

**Comment by bennuttall** [comment]
This is a Raspberry Pi package index, your issue does not belong here.
