### ISSUE TITLE
Missing package: coincurve

### ISSUE THREAD

**Issue by ofek** [piwheels/packages#17]
Missing package
Package name: coincurve
Link to PyPI page: https://pypi.org/project/coincurve
Link to piwheels page: https://www.piwheels.org/project/coincurve
Version: 12.0.0
Python version: 3.5

**Comment by bennuttall** [comment]
Successfully built version 12.0.0 on all ABIs!

**Comment by ofek** [comment]
Awesome, thank you!!!
