### ISSUE TITLE
Missing package: opencv-python cp38

### ISSUE THREAD

**Issue by redachhaibi** [piwheels/packages#171]
Dear maintainers,

recently, I am writing a code that uses opencv and multiprocessing. More specifically, multiprocessing with good shared memory has been introduced with Python 3.8

Could you please provide wheels with cp38?

Package name: opencv-python
Issue type: Missing package
Python version: 3.8

Kind regards

**Comment by bennuttall** [comment]
Sorry we don't do Python 3.8 wheels. We only build for Python versions in Debian.

**Comment by PeterPirog** [comment]
@redachhaibi 
I have built open-cv here:
[https://github.com/PeterPirog/Raspberry_armv7_builds/tree/main/opencv](https://github.com/PeterPirog/Raspberry_armv7_builds/tree/main/opencv)
