### ISSUE TITLE
Failed building wheel for pocketsphinx

### ISSUE THREAD

**Issue by YoloAlien64** [piwheels/packages#175]
I was trying to download pockectsphinx for a project I am making for my own benefit. In the terminal on the raspberry pi B, itself, I typed sudo pip3 install pocketsphinx and after entering it, it said that it failed building the wheel for pocketsphinx. How do I fix that problem?

**Comment by bennuttall** [comment]
https://piwheels.org/project/pocketsphinx/

looks like builds have failed. I'll take a look tomorrow.

**Comment by bennuttall** [comment]
It sounds like `sudo apt-get install swig` will install the required dependencies. Can you try it again after installing that, and let us know if it works?

**Comment by YoloAlien64** [comment]
Thanks, It works, but I now there is a new problem. It says that pulse/ pulseaudio.h is not found in the directory, so I did sudo apt-get install pulseaudio which successfully installed, then I tried it again and it said that that pulse/ pulseaudio.h is not found in the directory. Is there another thing I have to download?Sent from Mail for Windows 10 From: Ben NuttallSent: Thursday, December 24, 2020 8:40 AMTo: piwheels/packagesCc: YoloAlien64; AuthorSubject: Re: [piwheels/packages] Failed building wheel for pocketsphinx (#175) It sounds like sudo apt-get install swig will install the required dependencies. Can you try it again after installing that, and let us know if it works?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YoloAlien64** [comment]
Here is the image of what I see on the terminal of the raspberry pi. Sent from Mail for Windows 10 From: Travis DuongSent: Friday, December 25, 2020 4:49 PMTo: piwheels/packagesCc: Travis DuongSubject: RE: [piwheels/packages] Failed building wheel for pocketsphinx (#175) Thanks, It works, but I now there is a new problem. It says that pulse/ pulseaudio.h is not found in the directory, so I did sudo apt-get install pulseaudio which successfully installed, then I tried it again and it said that that pulse/ pulseaudio.h is not found in the directory. Is there another thing I have to download?Sent from Mail for Windows 10 From: Ben NuttallSent: Thursday, December 24, 2020 8:40 AMTo: piwheels/packagesCc: YoloAlien64; AuthorSubject: Re: [piwheels/packages] Failed building wheel for pocketsphinx (#175) It sounds like sudo apt-get install swig will install the required dependencies. Can you try it again after installing that, and let us know if it works?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YoloAlien64** [comment]
Thanks it worked, but now there is a new problem, after trying to download pocketsphinx, it still had the same error, it said that pulse/pulseaudio.h was not found in the directory so I downloaded pulseaudio in the terminal and then tried again and the same error with the same problem (pulse/pulseaudio.h was not found in the directory). Is it because it is something else I have to download? Also While testing the motor for the project I am currently working on, it said that GPIO.OUT(17,False) could not be called. Is there something I need to download for that too? Here are the two codes in case you want to look at them.

**LightsON/OFF Code**

import RPi.GPIO as GPIO
import time
import speech_recognition as sr

#configer GPIO pins
GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)

# configure variables
command = ""
on = "lights on"
off = "lights off"
voice = False
r = sr.Recognizer()

#keep running until given the command to turn on or off the lights
while(voice == False):
    print("speak")
    audio = sr.listen(source)
    
    try:
        speechString = r.recognize_google(audio)
        print(speechString)
        voice = True
        
    except sr.unkownValueError:
        print("could not understand audio")
        
    except sr.RequestError as e:
        print("could not request results; {0}".format(e))
    
    # determine if user said lights on or lights off
    if (speechString == on):
        GPIO.output(17, False)
        GPIO.output(27, True)
        time.sleep(0.3)
    if (speechString == off):
        GPIO.output(17, True)
        GPIO.output(27, False)
        time.sleep(0.3)

**Motor test code**

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)

GPIO.OUT(17,False)
GPIO.OUT(27,True)
time.sleep(0.1)
GPIO.cleanup()
