### ISSUE TITLE
PyEcoLib

### ISSUE THREAD

**Issue by Trust00** [piwheels/packages#178]
Package name: PyEcoLib
Link to PyPI page: https://pypi.org/project/PyEcoLib/
Link to piwheels page: https://piwheels.org/project/PyEcoLib/
Version: 1.0.12
Python version: 3.5
I am the maintainer: No
More information:

Please use code blocks where appropriate:

```bash
from examples.SizeStatistics import SizeStatistics
```

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-464420bf050b> in <module>
----> 1 from examples.SizeStatistics import SizeStatistics

ModuleNotFoundError: No module named 'examples.SizeStatistics'


```

**Comment by bennuttall** [comment]
According to their PyPI page, this package requires Python >=3.6

https://pypi.org/project/PyEcoLib/

**Comment by Trust00** [comment]
yes, that was an error on my own side. my python version is 3.8.5 not 3.5

**Comment by bennuttall** [comment]
As per the homepage and FAQs, we only build for versions of Pythion in Debian releases (so 3.5 and 3.7 currently).
