### ISSUE TITLE
Missing package: syft

### ISSUE THREAD

**Issue by robert-wagner** [piwheels/packages#18]
Missing package
Package name: syft
Link to PyPI page: https://pypi.org/project/syft
Link to piwheels page: https://www.piwheels.org/project/syft
Version: e.g. 0.1.7a1 - 0.1.14a1
Python version: e.g. all
More information:

The last 8 versions of syft (two months) are missing from piwheels but are available on PyPi. There are no successful or failed builds displayed

**Comment by bennuttall** [comment]
Successfully built :+1:
