### ISSUE TITLE
opencv-contrib-python-headless 4.5.1.48

### ISSUE THREAD

**Issue by dannystaple** [piwheels/packages#180]
Package name: opencv-contrib-python-headless
Link to PyPI page: pypi.org/project/opencv-contrib-python-headless
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python-headless/
Version: 4.5.1.48
Python version:all
I am the maintainer: No
More information:

The buster build seems to have failed. Attempting to `pip3 install opencv-contrib-python-headless` will lead to it downloading and building the pypi package as no wheel is available - and as of 9th Jan 2021, this is the latest version. 
This also frequently results in the killed message.

**Comment by bennuttall** [comment]
It seems the build ran out of memory. I'll try to run it again and see if it's doable.

**Comment by PeterPirog** [comment]
@dannystaple  @bennuttall  
Here is procedure how to build **opencv-contrib-python-headless** :

[https://github.com/PeterPirog/Raspberry_armv7_builds/blob/main/opencv/compilation.txt](https://github.com/PeterPirog/Raspberry_armv7_builds/blob/main/opencv/compilation.txt)

If you want build ver. 4.5.1.48 change  branch from 36 to 48
`git clone -b 48 --recursive https://github.com/skvark/opencv-python.git`

IMPORTANT: don't use `git checkout 48` !!!

`export ENABLE_CONTRIB=1` if you  don't want contrib set 0
`export ENABLE_HEADLESS=1` if you don't want headless set 0

**Comment by bennuttall** [comment]
I've imported files for this version - and newer ones are available too
