### ISSUE TITLE
exact-cover - build failed for version 0.3.2

### ISSUE THREAD

**Issue by jwg4** [piwheels/packages#181]
Package name: exact-cover
Link to PyPI page: https://pypi.org/project/exact-cover
Link to piwheels page: https://www.piwheels.org/project/exact-cover
Version: e.g. 0.3.2
Python version: all
I am the maintainer: Yes
More information:

Hi, I am not sure why the package build failed (on raspbian 'buster') for version 0.3.2. This version is supposed to be exactly the same as the pre-release version 0.3.2a2, which built fine, and which I have been able to install, pulling down the wheel from piwheels.

It would be very helpful if you could show me the error when this wheel build was attempted, or if you could give me some guidance as to how to closely match the piwheels build in CI, so that I can prevalidate if my package is going to work.

Thanks!

**Comment by bennuttall** [comment]
Here's the build output: https://paste.debian.net/1180780/

**Comment by jwg4** [comment]
Thank you so much. It's a build issue which is fixed in a branch, so soon
there will be a stable version which will hopefully build fine.

Great job with piwheels by the way.

**Comment by bennuttall** [comment]
Great! Ping here when you do a new release.

Thanks 👍

**Comment by bennuttall** [comment]
Built now
