### ISSUE TITLE
Missing package ambibulb

### ISSUE THREAD

**Issue by bespsm** [piwheels/packages#182]
Package name: ambibulb
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/ambibulb
Link to piwheels page: -
Version: 0.0.4rc1
Python version: 3.7.3
I am the maintainer: Yes
More information:

I couldn't find the package ambibulb although I was able to build the package on my RPi 3B+ (including dependencies collection). 

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ python3 --version
Python 3.7.3
```

**Comment by bennuttall** [comment]
That's strange. It was released a few hours ago. Did you, by any chance, delete it from PyPI and recreate it? I'll check the logs

**Comment by bespsm** [comment]
nope, I've just created it without any changes. If you need I can publish another rc to trigger the pipeline

**Comment by bennuttall** [comment]
Ah, looks like we had a crash overnight. I've just restarted so it'll pick up ambibulb shortly.

**Comment by bespsm** [comment]
thank you, issue is solved
