### ISSUE TITLE
missing package: ray

### ISSUE THREAD

**Issue by PeterPirog** [piwheels/packages#183]
Package name: ray
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/ray/
Link to piwheels page: https://www.piwheels.org/project/ray/
Version: e.g. 1.1.0
Python version: e.g. 3.7 or 3.8
I am the maintainer: No
More information:

Github repo: https://github.com/ray-project/ray

**Comment by bennuttall** [comment]
This package provides no source distribution - there's nothing for us to build: https://pypi.org/project/ray/#files

The piwheels page is here: https://www.piwheels.org/project/ray/

You'll have to ask the maintainers of the package to upload source distribution to PyPI.

**Comment by PeterPirog** [comment]
@bennuttall I have built ray wheels here:
[https://github.com/PeterPirog/Raspberry_armv7_builds/tree/main/ray](https://github.com/PeterPirog/Raspberry_armv7_builds/tree/main/ray)
[ray-1.2.0-cp38-cp38-linux_armv7l.whl](https://github.com/PeterPirog/Raspberry_armv7_builds/blob/main/ray/ray-1.2.0-cp38-cp38-linux_armv7l.whl)
