### ISSUE TITLE
Missing package: pc-ble-driver-py

### ISSUE THREAD

**Issue by ukBaz** [piwheels/packages#185]
Package name: nrfutil
Link to PyPI page: https://pypi.org/project/pc-ble-driver-py
Link to piwheels page: https://www.piwheels.org/project/pc-ble-driver-py
Version:  all
Python version:  all
I am the maintainer: No
More information:

Please use code blocks where appropriate:

Trying to install [nrfutil](https://www.piwheels.org/project/nrfutil):

```bash
$ pip3 install nrfutil==6.1.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting nrfutil==6.1.0
  Using cached https://www.piwheels.org/simple/nrfutil/nrfutil-6.1.0-py3-none-any.whl
Collecting piccata (from nrfutil==6.1.0)
  Using cached https://files.pythonhosted.org/packages/19/4d/711f14ad4fd6de8c54143b404ddf8c203a52e2501227b137c9bb0e0ec55b/piccata-2.0.1-py3-none-any.whl
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (from nrfutil==6.1.0) (3.4)
Collecting intelhex (from nrfutil==6.1.0)
  Using cached https://files.pythonhosted.org/packages/97/78/79461288da2b13ed0a13deb65c4ad1428acb674b95278fa9abf1cefe62a2/intelhex-2.3.0-py2.py3-none-any.whl
Collecting protobuf (from nrfutil==6.1.0)
  Downloading https://files.pythonhosted.org/packages/81/d4/a8a31a326ee60e295e5d7477d93d8f6ceee98246c1a7381afc817a91d893/protobuf-3.14.0-py2.py3-none-any.whl (173kB)
    100% |████████████████████████████████| 174kB 1.2MB/s 
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nrfutil==6.1.0) (4.46.0)
Collecting crcmod (from nrfutil==6.1.0)
  Using cached https://www.piwheels.org/simple/crcmod/crcmod-1.7-cp37-cp37m-linux_armv7l.whl
Collecting pyyaml (from nrfutil==6.1.0)
  Downloading https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175kB)
    100% |████████████████████████████████| 184kB 1.2MB/s 
  Installing build dependencies ... done
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nrfutil==6.1.0) (7.0)
Requirement already satisfied: ecdsa in ./venv/lib/python3.7/site-packages (from nrfutil==6.1.0) (0.16.1)
Collecting pyspinel>=1.0.0a3 (from nrfutil==6.1.0)
  Using cached https://www.piwheels.org/simple/pyspinel/pyspinel-1.0.3-py3-none-any.whl
Collecting pc-ble-driver-py>=0.14.2 (from nrfutil==6.1.0)
  Could not find a version that satisfies the requirement pc-ble-driver-py>=0.14.2 (from nrfutil==6.1.0) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4)
No matching distribution found for pc-ble-driver-py>=0.14.2 (from nrfutil==6.1.0)```
```

It appears to have a dependency on : https://www.piwheels.org/project/pc-ble-driver-py/
which piwheels don't support.

Adafruit seem to have tried to fix this by creating a new package:
https://www.piwheels.org/project/adafruit-nrfutil/

**Comment by bennuttall** [comment]
If you take a look [pc-ble-driver-py on PyPI](https://pypi.org/project/pc-ble-driver-py/#files) you'll see they generally don't release source distribution - just wheels for other platforms, so there's nothing for us to build. You could try filing an issue with the maintainers of that package.

Is adafruit-nrfutil a drop-in replacement?

**Comment by ukBaz** [comment]
It's not obvious if adafruit-nrfutil is a direct replacement or just works for their nrf boards.

I hadn't spotted that they aren't including sdist. I'm going down a deep hole looking at this. Seems to be a number of people having issues even if they build from github sources. e.g.
https://devzone.nordicsemi.com/f/nordic-q-a/30787/building-pc-ble-driver-py-on-a-raspberry-pi

I'll move forward with the adafruit solution and see if I hit problems using it with the micro:bit

Thank for taking a look.
