### ISSUE TITLE
Missing package: scipy

### ISSUE THREAD

**Issue by Eefried** [piwheels/packages#186]
Package name: scipy
Issue type: Missing newer package, shows 1.1.0 even if the /etc/pip.conf has  [global]
`extra-index-url=https://www.piwheels.org/simple`
Version: 1.6
Python version: 3.7
I am the maintainer: No
More information:
Raspian GNU/Linux 10
Linux version 5.4.83-v7l+ 
sudo pip3 install scipy

**Comment by bennuttall** [comment]
scipy 1.6.0 is available for Buster: https://piwheels.org/simp/scipy/

```
pi@raspberrypi:~# pip3 wheel scipy==1.6.0 --extra-index-url https://www.piwheels.org/simple   
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting scipy==1.6.0
  Using cached https://www.piwheels.org/simple/scipy/scipy-1.6.0-cp37-cp37m-linux_armv7l.whl (61.9 MB)
Collecting numpy>=1.16.5
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.20.1-cp37-cp37m-linux_armv7l.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 44 kB/s 
Saved ./scipy-1.6.0-cp37-cp37m-linux_armv7l.whl
Saved ./numpy-1.20.1-cp37-cp37m-linux_armv7l.whl
```

Can you give more information about what you're doing, what the output is, and if you have any further configuration? Assuming you are in fact using Python 3.7 (and haven't installed your own python) I don't see why this would fail.

FYI adding `-v` to your pip command will tell you (lots) more about what's going on.
