### ISSUE TITLE
opencv-python-headless 4.3.0.36

### ISSUE THREAD

**Issue by PeterPirog** [piwheels/packages#187]
Package name: opencv-python-headless 4.3.0.36
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/opencv-python-headless/4.3.0.36/
Link to piwheels page: https://www.piwheels.org/project/opencv-python-headless/
Version: e.g. 4.3.0.36
Python version: e.g. 3.7, 3.8
I am the maintainer: No

pip install opencv-python-headless==4.3.0.36

**Comment by bennuttall** [comment]
There is no source distribution for that particular version, so there's nothing for us to build. This is indicated on the project page:

<img width="958" alt="Screenshot 2021-02-08 at 11 21 22" src="https://user-images.githubusercontent.com/1609725/107213088-d1a8a700-69ff-11eb-9b23-2963b5f95ed9.png">

However, there are Python 3.7 wheels available for all newer versions.

**Comment by PeterPirog** [comment]
Thank you for explanation, now I understand what practically means "grey -" symbol

**Comment by bennuttall** [comment]
There's some hover text, but yeah - hard to cram in all the info!

**Comment by PeterPirog** [comment]
Thank you for the great job with armv7 packages. Inspired by Yours repo I will try to build something myself if  I can't find https://github.com/PeterPirog/Raspberry_armv7_builds
