### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#188]
Package name: cryptography
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/cryptography
Link to piwheels page: https://www.piwheels.org/project/cryptography
Version: 3.4+
Python version: 3.7
I am the maintainer: No
More information:

Truncated build output:

http://paste.debian.net/1184562

Since moving to rust, we can't build this with only Debian rust packages installed. We need to bite the bullet and move to rustup.

**Comment by mcampbellizo** [comment]
I've seen this same issue on our side. FWIW, I'm temporarily fixed it by installing `cryptography==3.3.2` in my virtual env before installing anything else. This works at least with the pre-2020 pip resolver, YMMV. 3.3.2 is the last version with a wheel in piwheels.

**Comment by MichaIng** [comment]
The builds for Buster succeeded yesterday: https://www.piwheels.org/project/cryptography/
Stretch builds are not available since v3.3, but at least for Raspberry Pi not important anymore?

**Comment by bennuttall** [comment]
That's odd. I started testing building this with rustup yesterday but I didn't install it on the builders yet (doing it right now).

Ah - it appears the maintainers lowered the Rust version requirement yesterday! https://github.com/pyca/cryptography/commit/151aa097cdf4632f382bc8c95d7771ed7290cf66

```
Lower the minimum supported Rust version (MSRV) to >=1.41.0. This change improves compatibility with system-provided Rust on several Linux distributions.
```

Ah well. Later we should have the missing versions too.

**Comment by bennuttall** [comment]
Update: using rustup on the builders isn't feasible due to https://github.com/rust-lang/rustup/issues/2383 so I've reverted back to using Debian's cargo. The latest cryptography builds ok so that'll have to do.

I may manually build and import the missing wheels if I get chance.
