### ISSUE TITLE
Missing package: mdf-iter

### ISSUE THREAD

**Issue by ajaykoppisetty** [piwheels/packages#189]
Package name: mdf_iter
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/mdf-iter/
Version: all
Python version: 3.6.9, 3.7.5 and 3.8.0
I am the maintainer: No
More information:

Please use code blocks where appropriate:

```bash
pip3 install mdf_iter
```

```python
Collecting mdf_iter
  Could not find a version that satisfies the requirement mdf_iter (from versions: )
No matching distribution found for mdf_iter
```

**Comment by bennuttall** [comment]
There's no source distribution on PyPI, so there's nothing for us to build:

![Screenshot 2021-02-12 at 12 08 00](https://user-images.githubusercontent.com/1609725/107766291-24999b80-6d2b-11eb-84d6-366232a7b538.png)

This piwheels project page indicates this: https://piwheels.org/project/mdf-iter

You'll have to file an issue with the project maintainers and ask them to upload source distribution to PyPI.
