### ISSUE TITLE
Missing package (version): praat-parselmouth

### ISSUE THREAD

**Issue by YannickJadoul** [piwheels/packages#190]
Package name: praat-parselmouth
Link to PyPI page: https://pypi.org/project/praat-parselmouth
Link to piwheels page: https://www.piwheels.org/project/praat-parselmouth
Version: 0.4.0
Python version: all
I am the maintainer: Yes
More information:

Version 0.3.3 nicely was nicely built, but it seems something went wrong with 0.4.0. I have tried reproducing (emulated in QEMU) with Raspberry Pi OS buster (`2021-01-11-raspios-buster-armhf-lite.img`), and (after installing `pip`) the only thing required to get the build working was installing `git`, since [my `pyproject.toml`](https://github.com/YannickJadoul/Parselmouth/blob/2b2c7be61ff7f79ba64b80b2f86c20a62215dc69/pyproject.toml) requires (for now) a slightly modified version of scikit-build:

```toml
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "scikit-build @ git+https://github.com/YannickJadoul/scikit-build@vs2019-apple-silicon",
]
build-backend = "setuptools.build_meta"
```

I must be honest; compiling with emulation very slow, though. So I did not finish the full build. But things seemed to be building normally (as they were in 0.3.3).

So is there a way to check if `git` is installed during the builds, or get a further indication of where my 0.4.0 builds went wrong?

(I've also realized that depending on this fork of `scikit-build` might not be amazing to have in a source dist, though; so if this is not possible to fix, maybe I'll just try avoiding that and release a version 0.4.1 without...)

EDIT: I'm realizing it's very unlikely `git` wouldn't be installed, but I don't really know what else could be the issue. Given that it took me half an hour to build 1% of my project in emulation, it would be nice if there'd be some kind of log or indication of where piwheels's build when wrong.

**Comment by bennuttall** [comment]
That's strange. Here are the build outputs:

cp35m: https://paste.debian.net/1186214/
cp37m: https://paste.debian.net/1186215/

I'll get it to re-attempt to see if it does anything different...

**Comment by bennuttall** [comment]
No, it looks to be the same output. I'll try a manual build on a Pi.

**Comment by YannickJadoul** [comment]
Thanks for looking into this!

But huh; they seem to even be two separate errors? I have tried installing pip 21.0 locally, but at least on 64-bit intel Linux, that doesn't result in the same error.

**Comment by YannickJadoul** [comment]
0.4.1 now worked for 3.7 and 3.9. It failed on 3.5; I'm guessing some issue with an old version of pip or so.
I would look into it, but it seems useless to waste your time on a retired version of Python, so I'll just close this :-)
