### ISSUE TITLE
adafruit-circuitpython-rfm9x

### ISSUE THREAD

**Issue by bfc74** [piwheels/packages#191]
Package name: adafruit-circuitpython-rfm9x
Link to PyPI page: https://www.piwheels.org/project/adafruit-circuitpython-rfm9x/#install
Link to piwheels page: https://www.piwheels.org/simple/adafruit-circuitpython-rfm9x/adafruit_circuitpython_rfm9x-2.1.3-py3-none-any.whl#sha256=f470fbd5f56dedaeb5d50de2b8d4260c75a6c419d1b151705e4d967c02ff5131
Version: 2.1.3 and 2.1.2
Python version: 3.5.3
I am the maintainer: No
More information:
During the installation of adafruit-circuitpython-rfm9x package, sys_ipc 1.1.0 gives a syntax error
installing standalone sys_ipc gives the same error
Pip install of older versions works fine, sys_ipc 1.1.0 has a release date of January 17, 2021

```python
sudo pip3 install adafruit-circuitpython-rfm9x=
.
.
Collecting sysv-ipc (from Adafruit-Blinka->adafruit-circuitpython-rfm9x==2.1.3)
  Using cached https://files.pythonhosted.org/packages/0c/d7/5d2f861155e9749f981e6c58f2a482d3ab458bf8c35ae24d4b4d5899ebf9/sysv_ipc-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fm84bu33/sysv-ipc/setup.py", line 11, in <module>
        import prober
      File "/tmp/pip-build-fm84bu33/sysv-ipc/prober.py", line 137
        d["SYSV_IPC_VERSION"] = f'"{version}"'
                                             ^
    SyntaxError: invalid syntax

```

**Comment by bennuttall** [comment]
The error you're getting is in a dependency package, [sysv-ipc](https://piwheels.org/project/sysv-ipc/) which has started using Python 3.6+ syntax, so you should install the previous version of that before you start:

```python
sudo pip3 install sysv-ipc==1.0.1
sudo pip3 install adafruit-circuitpython-rfm9x
```

**Comment by bennuttall** [comment]
Actually that won't work because Blinka requires sysv-ipc==1.1.0: https://github.com/adafruit/Adafruit_Blinka/blob/master/requirements.txt#L6

In fact Blinka requires Python 3.6+: https://github.com/adafruit/Adafruit_Blinka/blob/master/setup.py#L44

**Comment by bennuttall** [comment]
I think if you upgraded your pip it would honour the "Requires-Python" specification and tell you it's not possible to install. You need to start using Buster and Python 3.7 to get this to work.

**Comment by bfc74** [comment]
Upgrading to Raspbian Buster with the accompanying python 3.7.3 works. THX!
