### ISSUE TITLE
Missing package: mxnet-cu111

### ISSUE THREAD

**Issue by Flanture** [piwheels/packages#199]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
Are you sure? That package doesn't exist on PyPI: https://pypi.org/project/mxnet-cu111/ and piwheels has picked it up as having no releases: https://piwheels.org/project/mxnet-cu111/

If you have any more details, please fill out the template properly.
