### ISSUE TITLE
Missing package: fast5mod

### ISSUE THREAD

**Issue by JayVaz18** [piwheels/packages#203]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
Can you please edit your comment to complete the issue template

**Comment by bennuttall** [comment]
Are you the maintainer? Here's the build output: http://paste.debian.net/1196800/

If you're not the maintainer, you'll have to pass this on to them.
