### ISSUE TITLE
Missing package: awscrt

### ISSUE THREAD

**Issue by graebm** [piwheels/packages#204]
Package name: awscrt
Link to PyPI page: https://pypi.org/project/awscrt/
Link to piwheels page: https://www.piwheels.org/project/awscrt/
Version: 0.11.13 
Python version: all
I am the maintainer: Yes
More information:
This package has a C extension. Version 0.11.13 is marked broken on piwheels, but builds fine on my personal 3B+ with a fresh Buster lite install (plus `apt install cmake python3-dev` which I see are also present on the [builders](https://github.com/piwheels/piwheels/blob/05f0819581dd44844a5e99462746a50e28f46b56/deploy_slave.sh#L42))

I'm **more** interested in why the 3.7 build fails, than why 3.5 fails (since 3.5 is beyond end-of-life)

**Comment by bennuttall** [comment]
I've truncated the log as it was 1860 lines, here's the end: https//paste.debian.net/1195632/

Do you do something with golang??

**Comment by graebm** [comment]
Thanks a ton!
We recently took in a new dependency that *does* apparently do stuff with golang when it's available. I'll update this ticket when we resolve it, or need more logs

**Comment by bennuttall** [comment]
Ah, that would explain it. We only just added golang to the builders. Had a similar problem there, something about https: https://github.com/piwheels/packages/issues/197

**Comment by graebm** [comment]
Ok, finally fixed for python 3.7.

Here's what was going wrong for us in the python 3.7 build:
1) we'd added a dependency with a complex build process, that would use golang if it was available on the machine.
2) it's normal for golang to pull dependencies with git
3) the piwheels builder.py disables [git network access](https://github.com/piwheels/piwheels/blob/05f0819581dd44844a5e99462746a50e28f46b56/piwheels/slave/builder.py#L420)
4) kablooie

Anyway, we stopped that dependency from trying to use golang during its build, so problem solved for us.

I guess be warned that other projects using golang might hit a similar issues if they try and pull dependencies.

**Comment by graebm** [comment]
closing ticket. the python3.5 wheels are still broken, but python 3.5 is beyond end of life

**Comment by graebm** [comment]
Thanks for the help!
