### ISSUE TITLE
Missing package: azcam-qhy

### ISSUE THREAD

**Issue by qianwu2** [piwheels/packages#205]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by qianwu2** [comment]
Hi,
I am not able to use pip to install the package.

**Comment by bennuttall** [comment]
This package doesn't exist on PyPI: https://pypi.org/project/azcam-qhy/
