### ISSUE TITLE
Missing package: mediapipe

### ISSUE THREAD

**Issue by Harshvardan-14** [piwheels/packages#206]
Package name: Mediapipe
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/mediapipe/
Link to piwheels page: https://www.piwheels.org/project/mediapipe/
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: No

**Comment by bennuttall** [comment]
There's no source distribution on PyPI, only wheels: https://pypi.org/project/mediapipe/#files

You'll have to ask the maintainers to upload source so we have something to build.
