### ISSUE TITLE
Support for Raspbian Bullseye and Python 3.9+

### ISSUE THREAD

**Issue by samyhocine** [piwheels/packages#209]
Package name: pyzmq
Link to PyPI page: https://pypi.org/project/pyzmq/22.1.0/
Link to piwheels page: https://www.piwheels.org/project/pyzmq/
Version: 22.1.0
Python version: 3.9+
I am the maintainer: No
More information:

Hi, i'm trying to install pyzmq on a raspberry pi zero W (armv6) with Raspbian Bullseye / Python3.9 and takes it an eternity: 3 hours for now and still building.

I would like to know when wheels (not only for pyzmq but also redis and others) will be available for Raspbian Bullseye / Python3.9  ?

Edit: After 3 hours the compilation is done, here is the wheel file "pyzmq-22.1.0-cp39-cp39-linux_armv6l.whl" if it can help: https://drive.google.com/file/d/1V83ZbSP4W-nXWD1nKsKUnT1SmrLyVAMK/view?usp=sharing

Best regards,

**Comment by bennuttall** [comment]
Debian Bullseye hasn't been released yet, so we'll start building as soon as a candidate release image is available from our providers. We aim to have all wheels built by the time Bullseye is released. I'll make a new issue so people can follow progress.

**Comment by bennuttall** [comment]
#210
