### ISSUE TITLE
cytoolz

### ISSUE THREAD

**Issue by mahdiamer** [piwheels/packages#216]
Package name: example
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.5 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
It's not missing: https://www.piwheels.org/project/cytoolz/
