### ISSUE TITLE
grpcio: Illegal instruction on RPi1/Zero armv6

### ISSUE THREAD

**Issue by julianoes** [piwheels/packages#217]
Package name: grpcio
Link to PyPI page: https://pypi.org/project/grpcio/
Link to piwheels page: https://www.piwheels.org/project/grpcio/
Version: 1.38.0
Python version: 3.7
I am the maintainer: No
More information:

When using grpcio from piwheels on a Raspberry Pi 1 or Zero based on armv6, we get an "Illegal Instruction".

```
(gdb) r
Starting program: /usr/bin/python3 examples/takeoff_and_land.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0xb636f728 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
(gdb) bt
#0  0xb636f728 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
#1  0xb636918c in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

`grpcio` installed using `sudo apt-get install python3-grpcio` works.

Also see https://github.com/grpc/grpc/issues/26474.

**Comment by bennuttall** [comment]
Sorry this is due to the accidental removal of a flag from the pip command, solved by https://github.com/piwheels/piwheels/pull/276

Will update soon

**Comment by bennuttall** [comment]
I've built and imported all the wheels for this package now
