### ISSUE TITLE
Missing New keywords list for robotframework-excellib-xlsm 2.0.3

### ISSUE THREAD

**Issue by wallytauriac** [piwheels/packages#218]
Package name: robotframework-excellib-xlsm
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: 2.0.3
Python version: e.g. 3.5 or all
I am the maintainer: No
More information:
Trying to use version 2.0.3 Excellibrary but getting an error Keyword 'ExcelLibrary.Open Excel Document' expected 3 arguments, got 2
Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
Please contact the maintainers
