### ISSUE TITLE
TensorFlow Lite

### ISSUE THREAD

**Issue by aallan** [piwheels/packages#22]
Just a thought. I've been using the pre-built wheels for TensorFlow Lite from here, https://github.com/PINTO0309/Tensorflow-bin. The official wheel from Google doesn't include TensorFlow Lite, but the results from my benchmarking, https://blog.hackster.io/benchmarking-tensorflow-and-tensorflow-lite-on-the-raspberry-pi-43f51b796796, shows that its considerably faster (and possibly more appropriate) for the Pi. With the move to Python 3.7 the unofficial TensorFlow Lite wheel will need rebuilding, might be time to give it more official support and include it?

**Comment by kpine** [comment]
There are now official tflite wheels at https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter.

There is also a separate project by PINTO0309 just for the tflite wheels at https://github.com/PINTO0309/TensorflowLite-bin.

Is there an advantage to using the PINTO0309 builds still?

**Comment by bennuttall** [comment]
Closing this as there's no tflite package on PyPI
