### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by bwoodsend** [piwheels/packages#220]
Package name: pyinstaller
Link to PyPI page: https://pypi.org/project/pyinstaller
Link to piwheels page: https://www.piwheels.org/project/pyinstaller
Version: 4.3
Python version: all
I am the maintainer: Yes
More information:

PyInstaller 4.3 was yanked because, by being a wheel without platform tags, it mistakenly implied that PyInstaller was pure Python, causing the required binaries to not be compiled and then triggering *where are my binaries???* errors at runtime. This yanked broken wheel appears to be the latest release on piwheels and resultantly is breaking Pi + PyInstaller users.

**Comment by bennuttall** [comment]
> PyInstaller 4.3 was yanked

What do you mean by "yanked"? Yanked has a specific meaning on pypi: https://www.python.org/dev/peps/pep-0592/ - do you mean that or the version was just deleted and re-uploaded?

If you mean "yanked" then it's not currently shown as yanked on pypi - did you un-yank? (piwheels implements yanked and processes yanks/unyanks when actions are logged on pypi)

If you mean deleted and re-uploaded, piwheels should have processed each of these actions in turn (delete would have removed it from piwheels and the second create would have added it again and build from source).

If piwheels hasn't done what it should have, I'll have to investigate and trigger a rebuild. Should rebuilding the latest version now fix things? It looks like it failed on cp35m - is that to be expected?

**Comment by bwoodsend** [comment]
My mistake. The wheel wasn't *yanked* - just deleted and replaced with the sdist that's there currently.

> If piwheels hasn't done what it should have, I'll have to investigate and trigger a rebuild. Should rebuilding the latest version now fix things? It looks like it failed on cp35m - is that to be expected?

Building from the sdist or a git clone should do the job. We dropped support for Python 3.5 in pyinstaller 4.3 so yes, Python 3.5 is expected to fail.

**Comment by bennuttall** [comment]
Ok thanks for the clarity. It's strange that piwheels didn't delete the version and the file, and then kick off a new build when the version was re-registered. Anyway, I'll do that now.

**Comment by bennuttall** [comment]
It's rebuilt. Is the new one ok?

**Comment by bwoodsend** [comment]
Yep that one works perfectly thanks.

**Comment by bennuttall** [comment]
:+1:

**Comment by bwoodsend** [comment]
On a semi-related note - Am I right in saying that `armv8l` Pis should be able to install `manylinux2014_aarch64` tagged wheels which is why piwheels has wheels labelled `armv6l` and `armv7l` but not `armv8l`?

**Comment by bennuttall** [comment]
Yes, 64-bit OS users will be able to install `manylinux2014_aarch64` wheels. We intend to build them in future but haven't yet written the necessary changes into the piwheels system. See #119.
