### ISSUE TITLE
Missing package: pynse

### ISSUE THREAD

**Issue by rahullak** [piwheels/packages#221]
Package name: pynse
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pynse
Link to piwheels page: https://www.piwheels.org/project/pynse
Version: all
Python version: all
I am the maintainer: No
More information: None

**Comment by bennuttall** [comment]
That package seems to have been removed from PyPI: https://pypi.org/project/pynse/

I'm not sure why it's still on piwheels, it should have been removed.

**Comment by bennuttall** [comment]
On further inspection it seems that only the versions were removed from PyPI, not the package itself. So we should have removed these versions (which are from before the package was recreated...) and should have an empty project page.

@rahullak why did you open this issue?

**Comment by rahullak** [comment]
@bennuttall I had tried to install the package using the instructions on the piwheels page and it did not work (package not found). Also could not find the page on PyPI.

I was hoping the package was still available but was not accessible for some reason and that's why I raised the issue.

Thanks for clarifying.

**Comment by bennuttall** [comment]
Well you can still install it from piwheels, or even download the wheel yourself: https://www.piwheels.org/simple/pynse/pynse-0.1-py3-none-any.whl

I'll be deleting it shortly though, so hurry up :)
