### ISSUE TITLE
Missing package: libzt

### ISSUE THREAD

**Issue by aolme** [piwheels/packages#226]
### Package name

libzt

### Package version

1.4.2

### PyPI URL

https://pypi.org/project/libzt/

### piwheels URL

https://www.piwheels.org/project/libzt/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Unable to install the module on an arm Raspberry Pi. It says the build was skipped on piwheels.org

**Comment by bennuttall** [comment]
The package is skipped because there's no source distribution on PyPI, only wheels for other platforms. You'll have to ask the maintainers to upload a source file.
