### ISSUE TITLE
Missing package: cmake

### ISSUE THREAD

**Issue by JanLahmann** [piwheels/packages#227]
### Package name

cmake

### Package version

3.21.1

### PyPI URL

https://pypi.org/project/cmake/

### piwheels URL

https://www.piwheels.org/project/cmake/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The latest cmake versions cannot be build with the default
`sudo pip3 install cmake`

But the following seems to work:
```
sudo apt update
sudo apt -y install libssl-dev cmake
sudo pip3 install cmake
```

Could you update the procedure accordingly ?

**Comment by bennuttall** [comment]
Ok, this is an unusual one. I've just tracked down why this is failing.

The failure boils down to:

```python
File "setup.py", line 33, in <module>
      version=versioneer.get_version(),
  AttributeError: module 'versioneer' has no attribute 'get_version'
```

We have the library [versioneer](https://pypi.org/project/versioneer/) installed on the piwheels builders but this output is complaining that the module doesn't have a `get_version` function. We have the latest version installed, so it's not that.

However, what I discovered is that `import versioneer` in cmake's [setup.py]() does not intend to import this library, it is supposed to import a file called [versioneer.py]()

Unfortunately this means you can't build cmake if you have the library versioneer installed.

I will report this issue to cmake and I'll manually build the recent failing versions and import them in the next few days.

**Comment by JanLahmann** [comment]
Thank you, @bennuttall . That is great !

**Comment by bennuttall** [comment]
All imported:

![Screenshot from 2021-07-31 12-08-05](https://user-images.githubusercontent.com/1609725/127737998-bf53ed54-80d5-4258-8063-77a9d716dad7.png)

If you see another release that fails in future, feel free to reopen this issue and I'll build it again.

Hopefully cmake will fix the issue before too long.
