### ISSUE TITLE
Missing package: openPMD-api

### ISSUE THREAD

**Issue by ax3l** [piwheels/packages#23]
Package name: openPMD-api
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/openPMD-api
Link to piwheels page: https://www.piwheels.org/project/openPMD-api
Version: latest (0.8.0a0)
Build dependencies: https://openpmd-api.readthedocs.io/en/latest/dev/dependencies.html
Build options: https://openpmd-api.readthedocs.io/en/latest/dev/buildoptions.html
Python version:  all
More information:

I recently created `manylinux2010` build scripts within docker in https://github.com/openPMD/openPMD-api/pull/523 which builds all dependencies as statically linked.

Is it possible to add/re-use those for piwheels?

**Comment by bennuttall** [comment]
This is successfully building on Python 3.7 but not 3.5 - is that ok, or is 3.5 fixable?

**Comment by ax3l** [comment]
Can you show me the build log? I am not seeing it at https://www.piwheels.org/project/openpmd-api/

**Comment by ax3l** [comment]
Also, where can I add the required `sudo apt install libadios-dev libhdf5-dev` line for this package as well? :)

**Comment by ax3l** [comment]
@bennuttall with https://github.com/piwheels/piwheels/pull/190 merged, the [latest PyPI release](https://pypi.org/project/openPMD-api/) `0.9.0a1` should build on all three supported Python targets of piwheels. Can you confirm?

**Comment by bennuttall** [comment]
Passed on 3.7. Here's the build log for 3.5: https://paste.ubuntu.com/p/mw4zNkkcWc/

**Comment by ax3l** [comment]
Thanks!
Hm, two interesting things here: first of all it tries to download CMake from `pypi` instead of `piwheels` and second it seams to lack a dependency while installing CMake itself:
```
File "/tmp/pip-install-pls3e7ps/cmake/setup.py", line 7, in <module>                                                                                                                                                                                                                                                                                                                                             from skbuild import setup                                                                                                                                                                                                                                                                                                                                                                                      ImportError: No module named 'skbuild'      
```

Here is its upstream repo: https://github.com/scikit-build/cmake-python-distributions

**Comment by ax3l** [comment]
Maybe the build slave should actually contain the `extra-index-url=https://www.piwheels.org/simple` to `piwheels` as well instead of nothing? ;)

https://github.com/piwheels/piwheels/blob/master/deploy_slave.sh#L105

**Comment by bennuttall** [comment]
> Maybe the build slave should actually contain the extra-index-url=https://www.piwheels.org/simple to piwheels as well? ;)

We actually delete `pip.conf` from the build slaves because we build from PyPI - if we were to attempt to rebuild a package, it would pick up the previously built wheel and use that (defeating the object). Now I think we use the `-no-binary` option so we're probably ok.

@waveform80 any reason not to add `pip.conf` back in?

I'm actually quite unfamilar with build dependencies - something I need to look into.

**Comment by ax3l** [comment]
Yes, since you are not uploading source packages to piwheels, building with `--no-binary :all:` should totally work and pull the right dependencies (from `piwheels`), both in `pyproject.toml` as well as `requirements.txt` .

**Comment by ax3l** [comment]
ping @waveform80 can we update the `pip.conf` accordingly to rely on `piwheels` dependencies during build? :)

**Comment by ax3l** [comment]
pingpong @waveform80 and @bennuttall :)

**Comment by bennuttall** [comment]
Been a while since we updated this issue but now `scikit-build` is installed on builders, the package is successfully building on Buster.

**Comment by ax3l** [comment]
Thanks!

But it does not seem to pick up libadios-dev yet, do you have a log on what the install step produces?

https://github.com/piwheels/piwheels/pull/190

**Comment by bennuttall** [comment]
Oh, sorry. I just looked and saw that the wheels were there and thought the issue was resolved. Should have read more of the comments! I have installed `libadios-dev` on all the builders. I'll have a go at building it now and see what happens.

**Comment by ax3l** [comment]
Ah dang, forgot again that adios1 is a static library and therefore won't show up in the apt-get list on piwheels :)

**Comment by bennuttall** [comment]
Ok so it's succeeded for cp37m with these instructions:

```bash
sudo apt install libsz2 libaec0 libhdf5-103
sudo pip3 install openPMD-api
```

Do these instructions work, or is there more to do to get it to work?

**Comment by ax3l** [comment]
Yep, that's it. The compile-time dependency `libadios-dev` is static and should not show up to users anymore (besides transitive dependencies it could potentially carry).
Thanks a lot!

**Comment by bennuttall** [comment]
Excellent. Sorry for the delay - glad we got it sorted in the end.

**Comment by ax3l** [comment]
Thanks a lot for your splendid support :)
