### ISSUE TITLE
"version `GLIBC_2.29' not found" error on python3.9

### ISSUE THREAD

**Issue by theyd** [piwheels/packages#230]
### Package name

numpy

### Package version

1.21.1

### PyPI URL

https://pypi.org/project/numpy/

### piwheels URL

https://www.piwheels.org/project/numpy/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I have got a self compiled python3.9 on raspberry pi3 Buster. I installed numpy with 
` python3.9 -m pip install numpy`

pip uses following file for the installation: `https://www.piwheels.org/simple/numpy/numpy-1.21.1-cp39-cp39-linux_armv7l.whl`

After importing numpy in python console, i get following error:

`ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version GLIBC_2.29 not found (required by /home/pi/.local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-arm-linux-gnueabihf.so)` 

As i understand, it is not recommended to update the glibc version on the system. 

im using pip 21.2.2

**Comment by bennuttall** [comment]
The wheel was built on Debian Bullseye, against the glibc in Bullseye. If you want to use Python 3.9 I suggest you upgrade your OS to Bullseye rather than just upgrade Python.

Edit `/etc/apt/sources.list` and replace `buster` with `bullseye`, then `apt update` and `apt dist-upgrade`. Or wait a week or so for it to be released.

**Comment by theyd** [comment]
Hi and thank you for the answer.
Because i have no chance to updating my system to bullseye, i will install numpy with `--no-binary` option with long copile time as consequence.

Do you mean bullseye will be released for raspberry pi in a week?

**Comment by bennuttall** [comment]
I would imagine so. It's being released by Debian on 14 August and I expect Raspberry Pi to follow quickly.
