### ISSUE TITLE
Missing package: opencv-contrib-python

### ISSUE THREAD

**Issue by sylvaneau** [piwheels/packages#233]
### Package name

opencv-contrib-python

### Package version

4.5.3.56

### PyPI URL

https://pypi.org/project/opencv-contrib-python/

### piwheels URL

https://www.piwheels.org/project/opencv-contrib-python/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

This build is on error but the build of the base package opencv-python is on success.

Do you have more info on why this build has failed (maybe a missing dependency) ?
can I help to build this package ?

Thx

**Comment by sylvaneau** [comment]
building for python 3.5 is not necessary for this package i think

**Comment by bennuttall** [comment]
I've built it for 3.7 - will do 3.9 next

**Comment by bennuttall** [comment]
Done
