### ISSUE TITLE
Missing package: Shapely

### ISSUE THREAD

**Issue by DaAwesomeP** [piwheels/packages#234]
### Package name

Shapely

### Package version

>= 1.7.1

### PyPI URL

https://pypi.org/project/Shapely/

### piwheels URL

https://www.piwheels.org/project/Shapely/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

This package isn't totally missing, but the newer versions fail to build. Happy to help debug if the build log is shared.

**Comment by bennuttall** [comment]
It looks like building this now requires [libgeos-dev](https://packages.debian.org/bullseye/libgeos-dev) - I'll add it and kick off a rebuild

**Comment by bennuttall** [comment]
It's built successfully now :+1:

**Comment by DaAwesomeP** [comment]
Thanks!
