### ISSUE TITLE
Missing package: tplink-smartplug-api

### ISSUE THREAD

**Issue by bytos** [piwheels/packages#235]
### Package name

tplink-smartplug-api

### Package version

all

### PyPI URL

none

### piwheels URL

none

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

https://github.com/vrachieru/tplink-smartplug-api

Simple, but effective library for controlling smart plugs

**Comment by bennuttall** [comment]
You need to ask the maintainer to publish it on PyPI, and then it'll appear on piwheels automatically. We don't add random packages from github - they must be registered on PyPI.

**Comment by bytos** [comment]
I branched the code to my account, can I do it if he's not available or willing?
