### ISSUE TITLE
Missing package: IP2Trace

### ISSUE THREAD

**Issue by ip2location** [piwheels/packages#236]
### Package name

IP2Trace

### Package version

2.1.3, 2.1.4

### PyPI URL

https://pypi.org/project/IP2Trace/

### piwheels URL

https://www.piwheels.org/project/IP2Trace/

### Python version

- [X] Python 3.5
- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [X] Yes

### More information

Hi, recently we found out that on your site, our package is having build failed issue on Stretch (Python 3.5). However, on our side, we had tested with a docker with Stretch and Python 3.5, and no issue found. May I know how to fix this? Thank You.

**Comment by bennuttall** [comment]
The build output can be found here: http://paste.debian.net/1208830/

It looks like your `setup.py` references `readme.md` which is not contained within the sdist. I guess you need to include it in the manifest.

```
File "/tmp/pip-wheel-ny9ktrpf/ip2trace_01ae60fb4e3d460ea303fcd0f9ab74df/setup.py", line 4, in <module>
2021-08-23T23:36:22,981         with open("readme.md", "r") as fh:
2021-08-23T23:36:22,981     FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
```

**Comment by ip2location** [comment]
Hi,

Thank you for the reply. We had rechecked the distribution, and had uploaded a new version that contained the readme.md to PyPI. Is there anything else we can do here?

**Comment by bennuttall** [comment]
The latest version succeeded :+1:
