### ISSUE TITLE
Missing package: pyzbar

### ISSUE THREAD

**Issue by santicomp2014** [piwheels/packages#238]
### Package name

pyzbar

### Package version

all

### PyPI URL

https://pypi.org/project/pyzbar/

### piwheels URL

https://www.piwheels.org/project/pyzbar/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Pyzbar not found in index `https://www.piwheels.org/simple`
`ERROR: Could not find a version that satisfies the requirement pyzbar (from versions: none)`
`ERROR: No matching distribution found for pyzbar`

**Comment by bennuttall** [comment]
There's no source distribution on PyPI, so nothing for piwheels to build. It looks like there's a pure python wheel on PyPI though, so it should work if you install from PyPI.

**Comment by santicomp2014** [comment]
@bennuttall 
I installed it directly from PyPI as you mentioned, It's odd because it was there.
I will close this issue.
Thank you
