### ISSUE TITLE
Missing package: llvmlite

### ISSUE THREAD

**Issue by jacky-treehorn** [piwheels/packages#239]
### Package name

llvmlite

### Package version

all

### PyPI URL

https://pypi.org/project/llvmlite/

### piwheels URL

https://www.piwheels.org/project/llvmlite/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
This has been raised before and we didn't get anywhere, but take a look at this: https://github.com/piwheels/packages/issues/33
