### ISSUE TITLE
Package issue: Hash not match

### ISSUE THREAD

**Issue by Maphila** [piwheels/packages#245]
### Package name

pyinstaller

### Package version

4.5.1

### PyPI URL

https://pypi.org/project/pyinstaller

### piwheels URL

https://www.piwheels.org/project/pyinstaller

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

https://www.piwheels.org/simple/pyinstaller/pyinstaller-4.5.1-py3-none-any.whl

THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pyinstaller from https://www.piwheels.org/simple/pyinstaller/pyinstaller-4.5.1-py3-none-any.whl#sha256=2817136532eaacc920582c08b88368f9807c8979c404a26fd29555e766e94e15:
        Expected sha256 2817136532eaacc920582c08b88368f9807c8979c404a26fd29555e766e94e15
             Got        393afd647abbc1cfc402f519c269adde9bf6b67d85e2f9dfa2e69f72c09d14b2

**Comment by bennuttall** [comment]
The hash of the file is indeed `2817136532eaacc920582c08b88368f9807c8979c404a26fd29555e766e94e15`. This may be related to #220, perhaps an old file had that hash you were looking for. If you are using a lockfile I'd update it to the new hash. The `393...` one is wrong.
