### ISSUE TITLE
Missing package: sqlcipher3-binary

### ISSUE THREAD

**Issue by rochamorelli** [piwheels/packages#246]
Package name: sqlcipher3-binary
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/sqlcipher3-binary
Link to piwheels page: https://www.piwheels.org/project/sqlcipher3-binary/
Version: all
Python version: e.g. all
I am the maintainer: No
More information: No package is available for download neither through site nor pip command

Please use code blocks where appropriate:

Run on rpi4
```bash
# pip3 install sqlcipher3-binary
ERROR: Could not find a version that satisfies the requirement sqlcipher3-binary (from versions: none)
ERROR: No matching distribution found for sqlcipher3-binary
```

Thanks ;)

**Comment by bennuttall** [comment]
There's no source distribution for the `-binary` package, so you probably want the normal package: https://www.piwheels.org/project/sqlcipher3/

However, those builds have failed. The build log is here: https://paste.debian.net/1212772/

It looks like maybe installing this package will fix it: https://packages.debian.org/bullseye/libsqlite3-dev

**Comment by bennuttall** [comment]
Wheels are now available: https://www.piwheels.org/project/sqlcipher3/

You need to install the package `sqlcipher3` not `sqlcipher3-binary`
