### ISSUE TITLE
Missing package: gphoto2

### ISSUE THREAD

**Issue by jim-easterbrook** [piwheels/packages#249]
### Package name

gphoto2

### Package version

all

### PyPI URL

https://pypi.org/project/gphoto2/

### piwheels URL

https://www.piwheels.org/project/gphoto2/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

python-gphoto2 usually requires libgphoto2 (including development headers) to be installed on the users machine. As of v2.3.0 I've been creating x86_64 manylinux wheels which include libgphoto2 binaries. One of the difficulties in doing this is that libgphoto2 dynamically loads "camlibs" and "iolibs", so these binaries need to be included in a binary wheel, but aren't found by the usual tools.

Do let me know if there's anything I need to change in the package to enable a piwheels build.

**Comment by bennuttall** [comment]
Thanks for reporting, I installed `libgphoto2-dev` and they're now all building fine.

https://github.com/piwheels/piwheels/commit/75673f94b8d24d2642f7c833464ef8ca4d0bddaf

You'll notice the project page shows which apt packages are required: https://www.piwheels.org/project/gphoto2/
