### ISSUE TITLE
Missing package: pytest-homeassistant-custom-component

### ISSUE THREAD

**Issue by TomG736** [piwheels/packages#253]
### Package name

pytest-homeassistant-custom-component

### Package version

>=0.1

### PyPI URL

https://pypi.org/project/pytest-homeassistant-custom-component/

### piwheels URL

https://www.piwheels.org/project/pytest-homeassistant-custom-component/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
Here's the build output: https://paste.debian.net/1215737/

The error is here:

```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements_test.txt'
```

I think you need to include this file in the sdist (i.e. add to manifest)

**Comment by bennuttall** [comment]
Sorry, to clarify, this is what the maintainer needs to do - you ought to report it to them.
