### ISSUE TITLE
Missing package: PyP100-0.0.10.tar.gz

### ISSUE THREAD

**Issue by GoganGogan** [piwheels/packages#255]
### Package name

PyP100-0.0.10.tar.gz

### Package version

PyP100-0.0.10.tar.gz

### piwheels URL

https://www.piwheels.org/simple/pyp100/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Sorry if any info is missing, I'm completely new to this

**Comment by bennuttall** [comment]
That version failed because `HISTORY.md` was not included in the manifest. See full output here: https://paste.debian.net/1217763/
