### ISSUE TITLE
Missing package: pyo

### ISSUE THREAD

**Issue by domaslasauskas** [piwheels/packages#258]
### Package name

pyo

### Package version

all

### PyPI URL

https://pypi.org/project/pyo/

### piwheels URL

https://www.piwheels.org/project/pyo/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I've successfully built the wheel on mythic-beasts Raspberry Pi 4 instance (Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux)

```
apt-get install -y libsndfile1-dev liblo-dev
pip3 wheel pyo
```

**Comment by bennuttall** [comment]
Sorry for the delay, those packages have now been installed and the wheels have been built. There were some failures but the latest version has built successfully for cp37m and cp39 :+1:
