### ISSUE TITLE
Missing package: eclipse-zenoh

### ISSUE THREAD

**Issue by JEnoch** [piwheels/packages#263]
### Package name

eclipse-zenoh

### Package version

0.5.0b9

### PyPI URL

https://pypi.org/project/eclipse-zenoh/

### piwheels URL

https://www.piwheels.org/project/eclipse-zenoh/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

This package is Rust-based, relying on [setuptools-rust](https://github.com/PyO3/setuptools-rust) for the build.
All its dependencies are pulled from crates.io (no github dependency).
The github workflow succeed to build wheels for several platforms using [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel): see https://github.com/eclipse-zenoh/zenoh-python/actions/runs/1503356405
Sources: https://github.com/eclipse-zenoh/zenoh-python/tree/0.5.0b9

What went wrong building on piwheels infra?

**Comment by bennuttall** [comment]
Here's the build log: https://paste.debian.net/1220783/

**Comment by JEnoch** [comment]
Thanks. I see the problem comes from a dependency (spin) using `core::hint::spin_loop()`, which was [not stabilised before rust 1.49](https://github.com/rust-lang/rust/pull/76097).
I guess the piwheel infra uses an older version than rust 1.49 (see rustc --version), right ?
Do you see any way to update it ? Is rustup installed by chance ?

**Comment by bennuttall** [comment]
We use [Rust in Debian](https://packages.debian.org/bullseye/rustc), so that's 1.48 in Bullseye.

We tried to use rustup but it seems you can't install it as root for all users to use, so we reverted it.

**Comment by JEnoch** [comment]
rustup is usually installed by the user (see https://rustup.rs/), as it can download/install different rust toolchains on user demand or when specified in a `rust-toolchain` file by a project. All the binaries (`rustup`, `cargo`, `rustc`) go to `~/.cargo/bin/`.

Would it be possible/acceptable to install it as user on piwheels infra (setting `~/.cargo/bin/` in `$PATH`)?

**Comment by bennuttall** [comment]
Built successfully
