### ISSUE TITLE
Missing package: tktabl

### ISSUE THREAD

**Issue by vishalvikash2000** [piwheels/packages#265]
### Package name

tktabl

### Package version

0.2.0

### PyPI URL

https://pypi.org/project/tktabl/

### piwheels URL

https://www.piwheels.org/project/tktabl/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

attributes inside the pack() is not working...

**Comment by bennuttall** [comment]
I'm not sure what could have gone wrong, maybe it's a poetry thing?

It's a pure Python package that has wheels on PyPI, so I've removed our builds and skipped the package to prevent any future builds.
