### ISSUE TITLE
MIssing Package pyLoRa

### ISSUE THREAD

**Issue by garykuipers** [piwheels/packages#268]
pip install pyLoRa
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyLoRa
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5c708d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pylora/
  (repeated)
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5479c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pylora/
  Could not find a version that satisfies the requirement pyLoRa (from versions: )
No matching distribution found for pyLoRa

**Comment by bennuttall** [comment]
It looks like you were having internet connection issues at the time. PyLoRa is available from PyPI and piwheels: https://piwheels.org/project/pylora/
