### ISSUE TITLE
Missing package: qiskit-terra

### ISSUE THREAD

**Issue by mtreinish** [piwheels/packages#27]
Package name: qiskit-terra
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/qiskit-terra/
Link to piwheels page: https://www.piwheels.org/project/qiskit-terra/
Version: `0.8.2`, `0.8.1`, `0.8.0`, `0.7.2`
Python version: `3.5`, `3.6`, `3.7`
More information:

**Comment by bennuttall** [comment]
Successfully built on 3.5 and 3.7 :+1:
