### ISSUE TITLE
pycryptodomex v3.12 "Illegal instruction" in binary for armv6l

### ISSUE THREAD

**Issue by JsBergbau** [piwheels/packages#270]
### Package name

pycryptodomex

### Package version

3.12

### PyPI URL

https://pypi.org/project/pycryptodomex/

### piwheels URL

https://www.piwheels.org/project/pycryptodomex/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

With https://www.piwheels.org/simple/pycryptodomex/pycryptodomex-3.12.0-cp35-abi3-linux_armv6l.whl
open python3 and type
from Cryptodome.Cipher import AES
then it will crash with illegal instruction

![grafik](https://user-images.githubusercontent.com/37013344/146022009-74e77eb5-7682-4061-88b7-3f95f8994944.png)

Version 3.11 works, see JsBergbau/MiTemperature2#104

**Comment by bennuttall** [comment]
This issue has been identified and we hope to fix asap. Follow in #276

**Comment by bennuttall** [comment]
The wheels have been rebuilt and this issue should now be resolved

**Comment by JsBergbau** [comment]
Is there some caching active? Did not work for me.

```
tempvenv $ python3 -m venv .
~/tempvenv $ cd bin
~/tempvenv/bin $ . ./activate
~/tempvenv/bin $ pip3 install pycryptodomex

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pycryptodomex
  Downloading https://www.piwheels.org/simple/pycryptodomex/pycryptodomex-3.12.0-cp35-abi3-linux_armv6l.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 46kB/s
Installing collected packages: pycryptodomex
Successfully installed pycryptodomex-3.12.0
~/tempvenv/bin $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cryptodome.Cipher import AES
Illegal Instruction
```

**Comment by bennuttall** [comment]
I'm not sure why the files didn't get deleted in this case - I've kicked it off again so they should be up shortly (might take a few hours as the build is quite a long one).

**Comment by JsBergbau** [comment]
Works now. Thank you very much.
