### ISSUE TITLE
Broken package: alsa-midi (crashes with SIGILL)

### ISSUE THREAD

**Issue by Jajcus** [piwheels/packages#272]
### Package name

alsa-midi

### Package version

0.1.0

### PyPI URL

https://pypi.org/project/alsa-midi/

### piwheels URL

https://www.piwheels.org/project/alsa-midi/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

On Raspberry Pi Zero W importing the pywheels module fails with SIGILL:
```
>>> import alsa_midi
Illegal instruction
```

The same module compiled locally (`pip3 install --no-binary=alsa-midi alsa-midi`) works correctly.

The package contains cffi bindings to `libalsa.so.2`.

**Comment by Jajcus** [comment]
Probably the same issue as #269 and #270.

**Comment by bennuttall** [comment]
This issue has been identified and we hope to fix asap. Follow in #276

**Comment by bennuttall** [comment]
The wheels have been rebuilt and this issue should now be resolved

**Comment by Jajcus** [comment]
I was finally able to verify and indeed, it works now. Thanks!
