### ISSUE TITLE
Package issue: numpy produces "Illegal Instruction" on Raspberry Pi 1

### ISSUE THREAD

**Issue by tomflannaghan** [piwheels/packages#275]
### Package name

numpy

### Package version

1.21.5, 1.22.0, 1.22.1

### PyPI URL

https://pypi.org/project/numpy/

### piwheels URL

https://www.piwheels.org/project/numpy/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

On the Raspberry Pi 1 (Model B) running Raspberry Pi OS (bullseye), importing numpy produces an "Illegal instruction" error.

```
$ python3 -c 'import numpy'
Illegal instruction
```

I've tried versions 1.22.1, 1.22.0 and 1.21.5 - all produce this error. Numpy works as expected for version 1.21.4.

Here's the uname info: `Linux raspberrypi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux`

**Comment by michaeltoohig** [comment]
I had this issue also but I mentioned this in #269 with PIL and a couple other packages.

**Comment by bennuttall** [comment]
This issue has been identified and we hope to fix asap. Follow in #276

**Comment by bennuttall** [comment]
The wheels have been rebuilt and this issue should now be resolved

**Comment by tomflannaghan** [comment]
Thank you!
