### ISSUE TITLE
"Illegal instruction" issue with armv6 wheels

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#276]
Since a recent update to our provider's OS images, we've noticed that the version of gcc we have is compiled strictly for armv7 and not compatible with armv6 as before. This means that although wheels work on armv7 models (Pi 2 and up, inc Zero 2), they don't work on armv6 models (Pi 1 and Zero). This causes a fatal "Illegal instruction" error.

The issue applies to all (I think) armv6 wheels built since around mid-December.

We have identified the cause, but need further investigation to work out how to resolve the issue.

Please don't open new issues per package relating to this issue.

The workaround is unfortunately to build any required wheels yourself, e.g:

```
pip3 wheel numpy --no-binary :all:
```

For speed, build on an armv7 model, and rename to `armv7` to `armv6`.

**Comment by bennuttall** [comment]
A fix has been deployed, all affected builds since early December will be rebuilt overnight.

**Comment by bennuttall** [comment]
All packages have been rebuilt, this should have fixed the problem now.

**Comment by magicse** [comment]
https://github.com/home-assistant/core/issues/86589
