### ISSUE TITLE
Missing package: regex

### ISSUE THREAD

**Issue by MichaIng** [piwheels/packages#279]
### Package name

regex

### Package version

2022.1.18

### PyPI URL

https://pypi.org/project/regex/

### piwheels URL

https://www.piwheels.org/project/regex/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Latest build failed.

**Comment by bennuttall** [comment]
Not sure why but pip didn't find it at first, must have been a delay in the file being available on the PyPI CDN. I've kicked it off again and they've all built fine.
