### ISSUE TITLE
Misssing package: opencv-python and friends

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#28]
Package names:
- opencv-python
- opencv-python-headless
- opencv-contrib-python
- opencv-contrib-python-headless

Link to PyPI pages:
- https://pypi.org/project/opencv-python
- https://pypi.org/project/opencv-python-headless
- https://pypi.org/project/opencv-contrib-python
- https://pypi.org/project/opencv-contrib-python-headless

Link to piwheels page:
- https://www.piwheels.org/project/opencv-python
- https://www.piwheels.org/project/opencv-python-headless
- https://www.piwheels.org/project/opencv-contrib-python
- https://www.piwheels.org/project/opencv-contrib-python-headless

Version: 4.0.1.22 to 4.1.0.25
Python version: all

**Comment by willmendil** [comment]
Thanks for the link, but if it is already incoporated to piwheel, why do I get:

```
pi@robopi:~ $ pip install opencv-python
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
  ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python

```

**Comment by bennuttall** [comment]
You're trying to install it using `pip` which is for Python 2. We don't have Python 2 wheels.

We also don't have v4.x releases and we don't have any wheels for Python 3.7 (in Buster). If you want to use opencv you'll have to use Raspbian Stretch. There `sudo pip3 install opencv-python` will work and bring in the latest version we have.

**Comment by willmendil** [comment]
my pip is associated to pip3, so that's not the problem. But I am indeed running buster with 3.7, do you recommend downgrading to stretch or to python 3.6?

**Comment by bennuttall** [comment]
We don't have Python 3.6 wheels. Just download stretch, put that on your card, [install the dependencies](https://blog.piwheels.org/new-opencv-builds/) and install opencv.

**Comment by freinold** [comment]
> 
> 
> @waveform80 builds these manually, offline, separate from the rest of piwheels which is automated.
> 
> Once we've dealt with our current workload (fixing things, and getting cp37 builds done), we can look at getting recent opencv builds done.

@bennuttall How much longer do you think this will take approximately? Otherwise I will try to build it myself.

**Comment by waveform80** [comment]
@freinold :

@bennuttall kindly bought a bunch of Pi3's up to my place at the weekend. I've spent the last few evenings rigging together something to automate this process (as release notices just get buried in the avalanche of e-mail in my inbox these days). I'm hoping to have something built by the weekend, if you can wait that long; if you can't there are some older releases available on piwheels at the moment: https://www.piwheels.org/project/opencv-python/ which you can install with a version pin (e.g. pip3 install opencv-python==3.4.4.19).

**Comment by njern** [comment]
@waveform80 excellent news, came here to look for the same thing as the original poster but it seems you're already on it.

I (and the silent majority) definitely appreciate your hard work and CPU time saved :)

**Comment by willmendil2** [comment]
Indeed we do appreciate, and I wonder, is ther a way we could help. I have raspberry pis hanging, I could compile stuff for you if you want. I'm not used to doing that so it might be too difficult to outsource the work. But if there's a sh file I can run that compiles everything which I can then send to you, you tell me

**Comment by jordanperr** [comment]
+1 for Python 3.7

**Comment by freinold** [comment]
Any progress during the last week?
I tried building it myself from source today but failed several times.

**Comment by pmishev** [comment]
Why was this issue closed? Do you not intend to provide such binaries at all?

**Comment by waveform80** [comment]
> Any progress during the last week?

Yup, finally got some progress - I've now got a little cluster successfully building everything (across jessie, stretch, and buster). There's quite a bit to catch up with (basically everything since 4.0) and that's going to take a few days but the cluster's beavering away at it.

Also, I *think* I've got it set up to automate the builds going forward; I've yet to test that bit but in theory next time a release occurs the cluster *should* notice it, automatically build everything, and text me to tell me to upload stuff.

**Comment by trickeydan** [comment]
@waveform80 Do you have any timeline for OpenCV 4.x on Buster / Python 3.7?

We have been unable to compile it successfully ourselves, and it's blocking our new CV system for robotics. I can probably run some pis to act as build slaves if that helps? Thanks :)

**Comment by bennuttall** [comment]
Thanks everyone for your patience. We've just imported all the missing opencv wheels!

**Comment by Pyrestone** [comment]
The python3.6 wheels are still missing!

**Comment by bennuttall** [comment]
We don't build for Python 3.6, only for versions in Raspbian Jessie (3.4), Stretch (3.5) and Buster (3.7).
