### ISSUE TITLE
sourcedefender removal

### ISSUE THREAD

**Issue by richard-scott** [piwheels/packages#281]
### Package name

sourcedefender

### Package version

all

### PyPI URL

https://pypi.org/project/sourcedefender/

### piwheels URL

https://www.piwheels.org/project/sourcedefender/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

Please can you remove this package from your system and flag it in the database to be excluded in future.

**Comment by bennuttall** [comment]
Done
