### ISSUE TITLE
Missing package: sysv-ipc

### ISSUE THREAD

**Issue by dtrunk90** [piwheels/packages#285]
### Package name

sysv-ipc

### Package version

1.1.0

### PyPI URL

https://pypi.org/project/sysv-ipc/

### piwheels URL

https://www.piwheels.org/project/sysv-ipc/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

armv8 is missing

**Comment by bennuttall** [comment]
We don't currently build aarch64 https://github.com/piwheels/packages/issues/119

**Comment by dtrunk90** [comment]
How do I install it on my pi4? download armv7 wheel and rename to `*-py3-none-any.whl`?

**Comment by bennuttall** [comment]
No, that won't work. You'll have to build it yourself. Look up the build dependencies, install them, and run `pip install sysv-ipc`.

**Comment by dtrunk90** [comment]
In that case i have to cross-compile them on my computer because batocera.linux is very restricted. i don't have any gcc. Or i could add gcc and stuff i need to compile natively where i have to compile batocera.linux myself. thx for the help.
