### ISSUE TITLE
Missing package: rpi-ws281x

### ISSUE THREAD

**Issue by dtrunk90** [piwheels/packages#286]
### Package name

rpi-ws281x

### Package version

4.3.1

### PyPI URL

https://pypi.org/project/rpi-ws281x/

### piwheels URL

https://www.piwheels.org/project/rpi-ws281x/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

armv8 is missing

**Comment by bennuttall** [comment]
We don't currently build aarch64 https://github.com/piwheels/packages/issues/119
