### ISSUE TITLE
Missing Package: libcst

### ISSUE THREAD

**Issue by cp2004** [piwheels/packages#290]
### Package name

libcst

### Package version

0.4.0 onwards

### PyPI URL

https://pypi.org/project/libcst/#description

### piwheels URL

https://www.piwheels.org/project/libcst/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

It looks like the latest version (0.4.0 onwards) requires rust to build. They provide wheels for a lot of platforms, but none for RPis. Probably a similar situation to cryptography, also requiring rust?

**Comment by bennuttall** [comment]
We do have rust installed, but it's version 1.48: https://packages.debian.org/bullseye/rustc

Here's the build log: http://paste.debian.net/1232166/

**Comment by cp2004** [comment]
Went digging through their issues as I couldn't see it mentioned anywhere - looks like it needs 1.53 according to this comment. https://github.com/Instagram/LibCST/issues/613#issuecomment-1015520556

**Comment by bennuttall** [comment]
Built successfully
