### ISSUE TITLE
Package issue: opencv-python-headless glibc version mismatch on Buster

### ISSUE THREAD

**Issue by fangchenli** [piwheels/packages#291]
### Package name

opencv-python-headless

### Package version

4.5.5.62

### PyPI URL

https://pypi.org/project/opencv-python-headless/

### piwheels URL

https://www.piwheels.org/project/opencv-python-headless/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I installed the latest `opencv-python-headless` via `pip` on Buster in a venv. But when importing `cv2`, it has this error:

```
ImportError: /lib/arm-linux-gnueabihf/libpthread.so.0: version `GLIBC_2.30` not found (required by /.../cv2/cv2.abi3.so)
```

The latest `glibc (libc6)` on Buster is `2.28`. But the wheel was built with `2.30`.

**Comment by bennuttall** [comment]
You checked the Python 3.9 box but you're talking about Buster - which is it, Python 3.7 on Buster, or Python 3,9 on Bullseye?

If you've installed Python 3.9 on Buster, then you'll have the wheel that was built for Bullseye. Your best bet is to stick to Python 3.7 on Buster or upgrade to Bullseye.
