### ISSUE TITLE
Missing package: opencv-python

### ISSUE THREAD

**Issue by Th0mas1981** [piwheels/packages#294]
### Package name

opencv-python

### Package version

4.2.0.34

### PyPI URL

https://pypi.org/project/opencv-python/

### piwheels URL

https://www.piwheels.org/project/opencv-python/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I need this version for an application, that is only working with this version,

**Comment by bennuttall** [comment]
That version is binary only, there's no source on pypi for us to build. We have many newer versions available.
