### ISSUE TITLE
Missing package: Pillow

### ISSUE THREAD

**Issue by MichaIng** [piwheels/packages#296]
### Package name

Pillow

### Package version

9.1.0

### PyPI URL

https://pypi.org/project/Pillow/

### piwheels URL

https://piwheels.org/project/pillow/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The latest build from 1. April failed.

**Comment by nulano** [comment]
A user has opened an issue in the upstream repo: https://github.com/python-pillow/Pillow/issues/6193

I looked at the logs and it seems the [build triggered at around 14:57 UTC and failed to find the source archive](https://www.piwheels.org/logs/0000/0801/9419.txt), but PyPI shows that the source archive was already uploaded at 14:39 UTC: https://pypi.org/project/Pillow/9.1.0/#files

**Comment by bennuttall** [comment]
Thanks for the heads-up! It's built now

**Comment by MichaIng** [comment]
Many thanks 👍.
