### ISSUE TITLE
Missing package: mkl

### ISSUE THREAD

**Issue by simonnier** [piwheels/packages#298]
### Package name

mkl

### Package version

2022.1.0

### PyPI URL

https://pypi.org/project/mkl/

### piwheels URL

https://www.piwheels.org/project/mkl/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

On raspberry OS

`sudo pip3 install mkl `

shows below

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement mkl
ERROR: No matching distribution found for mkl
```

**Comment by bennuttall** [comment]
That package does not provide a source distribution so there's nothing for us to build. You'll have to contact the maintainers and ask them to upload a source distribution.
