### ISSUE TITLE
Missing package: watchfiles

### ISSUE THREAD

**Issue by bellini666** [piwheels/packages#303]
### Package name

watchfiles

### Package version

0.14.1

### PyPI URL

https://pypi.org/project/watchfiles/

### piwheels URL

https://www.piwheels.org/project/watchfiles/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
More info in #304
