### ISSUE TITLE
Package issue: watchfiles

### ISSUE THREAD

**Issue by samuelcolvin** [piwheels/packages#304]
### Package name

watchfiles

### Package version

all

### PyPI URL

https://pypi.org/project/watchfiles/

### piwheels URL

https://www.piwheels.org/project/watchfiles/

### Python version

- [ ] Python 3.5 (Issue doesn't relate to python 3.5 since watchfiles doesn't support 3.5, it would be helpful to users if your ["Releases" build matrix](https://www.piwheels.org/project/watchfiles/) distinguished between failed builds and unsupported versions.)
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

See https://github.com/samuelcolvin/watchfiles/issues/149.

Watchfiles requires a newer version of rust to compile.

Any version of rust which allows `edition = "2021"` should work, e.g. `>=1.56.0`. Confirmed in https://github.com/samuelcolvin/watchfiles/pull/150.

Would it be possible to install latest stable rust via [rustup](https://rustup.rs/) for builds of this package?

---

Details of the error from the build logs https://www.piwheels.org/logs/0000/0825/2816.txt:

```
2022-05-18T01:12:30,641   Caused by:
2022-05-18T01:12:30,642     failed to parse the `edition` key

2022-05-18T01:12:30,642   Caused by:
2022-05-18T01:12:30,643     this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

I assume this build is using rust around v1.41 installed via apt or similar, but I can't confirm as I don't have a pi with me right now and the logs don't see to include the rust version.

**Comment by samuelcolvin** [comment]
Any update on this?

Watchfiles has binaries for armv7l as of `v0.15a1`, which are confirmed to work on raspberry pi, https://github.com/samuelcolvin/watchfiles/issues/149#issuecomment-1146638752.

If piwheels isn't going to provide binaries, could you just proxy/redirect to pypi?

As of this latest version, watchfiles build will been maturin, see #254.

**Comment by samuelcolvin** [comment]
Should be fixed when https://github.com/piwheels/piwheels/pull/322 is released.

**Comment by bennuttall** [comment]
Builds succeeded
