### ISSUE TITLE
Missing package: cmake

### ISSUE THREAD

**Issue by jack1142** [piwheels/packages#307]
### Package name

cmake

### Package version

3.22.5

### PyPI URL

https://pypi.org/project/cmake/

### piwheels URL

https://www.piwheels.org/project/cmake/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Aside from 3.22.5 which fails for all Python versions, it also seems that the build failed for Python 3.7 on versions 3.22.3 and 3.22.4 (it succeeded for the other two Python versions there though).

**Comment by bennuttall** [comment]
Newer versions have built successfully :+1:
