### ISSUE TITLE
Missing package: cbor2

### ISSUE THREAD

**Issue by pszafer** [piwheels/packages#310]
### Package name

cbor2

### Package version

5.4.3

### PyPI URL

https://pypi.org/project/cbor2/

### piwheels URL

https://www.piwheels.org/project/cbor2/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
Thanks. It's available now.
