### ISSUE TITLE
Missing package: python-libfprint

### ISSUE THREAD

**Issue by kewartoscar** [piwheels/packages#319]
### Package name

python-libfprint

### Package version

all

### PyPI URL

https://pypi.org/project/python-libfprint/

### piwheels URL

https://www.piwheels.org/project/python-libfprint/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

'python-libfprint' cannot be installed for python 3.9 or later.

**Comment by bennuttall** [comment]
I've managed to build it for Python 3.7 by installing `fprint-dev` in Buster, but in Bullseye the package is `fprint-2-dev` and that doesn't help build this package.

I think you need to report this to the package maintainer at https://github.com/jdiego/python-libfprint/issues
