### ISSUE TITLE
Missing package: fast-ctc-decode

### ISSUE THREAD

**Issue by zhjai** [piwheels/packages#320]
### Package name

fast-ctc-decode

### Package version

all

### PyPI URL

https://pypi.org/project/fast-ctc-decode/

### piwheels URL

https://www.piwheels.org/project/fast-ctc-decode/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
This package does not provide source distribution so there's nothing for us to build: https://pypi.org/project/fast-ctc-decode/#files

You'll have to ask the package maintainers to upload an sdist
