### ISSUE TITLE
Missing package: bcrypt

### ISSUE THREAD

**Issue by G3zz** [piwheels/packages#321]
### Package name

bcrypt

### Package version

4.0.0

### PyPI URL

https://pypi.org/project/bcrypt/

### piwheels URL

https://www.piwheels.org/project/bcrypt/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Build is failing for both Buster and Bullseye meaning that clients will have to build from source.
You can see in the logs that it's because of the rust compiler, which needs to be updated:

_2022-08-24T04:12:33,810   error: Rust 1.48.0 does not match extension requirement >=1.56.0_

**Comment by bennuttall** [comment]
Related to https://github.com/piwheels/piwheels/pull/322 will report back when I've tested it out

**Comment by G3zz** [comment]
Any news (or do you need any help)?

**Comment by bennuttall** [comment]
Built successfully
