### ISSUE TITLE
Problem with package: stable-baselines

### ISSUE THREAD

**Issue by llamasoft** [piwheels/packages#323]
### Package name

stable-baselines

### Package version

all

### PyPI URL

https://pypi.org/project/stable-baselines/

### piwheels URL

https://www.piwheels.org/project/stable-baselines/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The stable-baselines package has a dependency on tensorflow but because of how the check is implemented in setup.py (https://github.com/Stable-Baselines-Team/stable-baselines/blob/master/setup.py#L18-L45) or possibly because of the build environment, the resulting wheel has no tensorflow requirements.  This results in an unusable package when installed from wheel.

**Comment by bennuttall** [comment]
That's not something we have any control over. They're just doing bad practices in their setup.py. You'll have to take it up with the maintainers.
