### ISSUE TITLE
Missing package: opencv-contrib-python

### ISSUE THREAD

**Issue by JoeSantamariaParedes** [piwheels/packages#325]
### Package name

opencv-contrib-python

### Package version

todos

### PyPI URL

https://pypi.org/project/opencv-contrib-python/

### piwheels URL

https://www.piwheels.org/project/opencv-contrib-python/

### Python version

- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
The build output is here: https://www.piwheels.org/logs/0000/0836/5847.txt

I can't immediately tell what went wrong - will take a look when I get chance

**Comment by pvanderlinden** [comment]
@bennuttall Do you have plans to build this package again? The last build was 2 years ago, and Bookworm: Python 3.11has no successful builds at all.

**Comment by pvanderlinden** [comment]
If I look at the build output, it seems to be running out of memory. If these build are all running on rpi 3b, then it will need some more swap. I ran it on my 3b and it worked in 8GB of swap, but it will probably work with 2GB total memory (1GB RAM + 1GB swap).

**Comment by bennuttall** [comment]
I'm trying to build them offline using an 8GB Pi 4. Closing this in favour of #299.
