### ISSUE TITLE
Missing package: matrix-synapse

### ISSUE THREAD

**Issue by MichaIng** [piwheels/packages#327]
### Package name

matrix-synapse

### Package version

1.68.0

### PyPI URL

https://pypi.org/project/matrix-synapse/

### piwheels URL

https://www.piwheels.org/project/matrix-synapse/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Recent builds failed as is requires Rust since v1.68.0: https://matrix-org.github.io/synapse/v1.68/upgrade.html#rust-requirement-when-building-from-source

As always when Rust comes into play, pre-compiled wheels safe users a lot of compiling time and build environment setup efforts.

**Comment by bennuttall** [comment]
See https://github.com/piwheels/piwheels/pull/322

**Comment by bennuttall** [comment]
Built successfully
