### ISSUE TITLE
Problem with package: opencv-python

### ISSUE THREAD

**Issue by vn218** [piwheels/packages#328]
### Package name

opencv-python

### Package version

all

### PyPI URL

https://pypi.org/project/opencv-python/

### piwheels URL

https://www.piwheels.org/project/opencv-python/

### Python version

- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Ubuntu 22.04 has libwebp7 instead of libwebp6. Could you please upload a wheel file which supports the same.

**Comment by vn218** [comment]
Not just libwep6, a few other dependencies are also not available on 22.04

**Comment by bennuttall** [comment]
We don't support Ubuntu, just Raspberry Pi OS.
