### ISSUE TITLE
Problem with package: TheengsGateway

### ISSUE THREAD

**Issue by 1technophile** [piwheels/packages#331]
### Package name

theengsgateway

### Package version

0.6.0

### PyPI URL

https://pypi.org/project/theengsgateway/

### piwheels URL

https://www.piwheels.org/project/theengsgateway/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

Build for Python 3.9 failed:
`2022-10-24T18:57:42,382   OSError: [Errno 28] No space left on device`
https://www.piwheels.org/logs/0000/0886/0359.txt

I just built the wheel successfully with Python 3.9 on my Raspberry Pi 3B:
```
pip3 wheel TheengsGateway==0.6.0 --no-deps --no-binary TheengsGateway
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting TheengsGateway==0.6.0
  Using cached TheengsGateway-0.6.0.tar.gz (130 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: TheengsGateway
  Building wheel for TheengsGateway (PEP 517) ... done
  Created wheel for TheengsGateway: filename=TheengsGateway-0.6.0-cp39-cp39-linux_armv7l.whl size=304305 sha256=6216c0daebbb40cd81f2e5ee19dab371ffbc45f406ce42eaf4741e4e3a72d248
  Stored in directory: /home/openhabian/.cache/pip/wheels/8b/ba/4e/0dfd2cadf368fd51c70ab898bfae6d4c6cb5d5b7f7ce87c4c8
Successfully built TheengsGateway
```

**Comment by bennuttall** [comment]
Done now :+1:

**Comment by 1technophile** [comment]
Thanks!
