### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by ronbuist** [piwheels/packages#334]
### Package name

cryptography

### Package version

38.0.3

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Error message indicates Rust compiler is missing. This did not seem to be the case for version 38.0.2 (yanked).

**Comment by bennuttall** [comment]
Duplicate of #333 and #329 - see https://github.com/piwheels/piwheels/pull/322
