### ISSUE TITLE
Missing package: PyGObject

### ISSUE THREAD

**Issue by WayneKeenan** [piwheels/packages#336]
### Package name

PyGObject

### Package version

all

### PyPI URL

https://pypi.org/project/PyGObject/

### piwheels URL

https://www.piwheels.org/project/PyGObject/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The Python package needs the following apt packages to compile:

```
libglib2.0-dev 
libgirepository1.0-dev 
libcairo2-dev
```

**Comment by WayneKeenan** [comment]
The Python package needs the following apt packages to compile:

```
sudo apt install -y libglib2.0-dev libgirepository1.0-dev libcairo2-dev
```

**Comment by WayneKeenan** [comment]
There is the `vext.gi` package that fulfils `bluezero` requirements, so this isn't a high priority.      

Not looked into what the exact functional overlap of these two packages are, so still might be worth adding.

**Comment by bennuttall** [comment]
Built successfully
