### ISSUE TITLE
Missing package: zxing-cpp

### ISSUE THREAD

**Issue by stumpylog** [piwheels/packages#344]
### Package name

zxing-cpp

### Package version

all

### PyPI URL

https://pypi.org/project/zxing-cpp/

### piwheels URL

https://www.piwheels.org/project/zxing-cpp/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

```log
Cloning into 'pybind11-src'...
2023-01-05T23:22:30,880   fatal: transport 'https' not allowed
```

The build appears to be failing to clone pybind11 over https.  I'm guessing there is some Git config setting needed to enable https as a valid transport.  The URL in the CMakeLists.txt looks correct.  Running `python3 -m build --wheel` locally with the sdist works with no extra configurations.

**Comment by bennuttall** [comment]
We do not allow running `git clone` as part of building a package.

**Comment by axxel** [comment]
> We do not allow running `git clone` as part of building a package.

pybind11 will only be fetched from cmake via git clone if it is not found installed locally.

**Comment by bennuttall** [comment]
pybind11 should be available. It's installed here: https://github.com/piwheels/piwheels/blob/master/deploy_slave.sh#L59

**Comment by axxel** [comment]
That is strange because the git clone only happens when a standard `find_package` fails: https://github.com/zxing-cpp/zxing-cpp/blob/deda5eef587a6c2288dad5a69c08240e5224707f/zxing.cmake#L29

**Comment by stumpylog** [comment]
This might be resolved by my changes to the build system requirements.  It think it will create a virtual environment with pybind11 visible there

**Comment by axxel** [comment]
I'm not familiar with the piwheels infrastructure at all. If there is something that upstream (i.e. me) would need to do to make this work, please let me know.

**Comment by bennuttall** [comment]
We install a load of apt libraries and things, and run `pip wheel pkg==version` for everything.

Here's the build log: https://www.piwheels.org/logs/0000/0916/4830.txt

**Comment by axxel** [comment]
I've seen the build log before but could not conclude more than that cmake did not find a local pybind11 installation.

**Comment by axxel** [comment]
> This might be resolved by my changes to the build system requirements.

Any updates on that? Is anyone still "working" on this somehow?

**Comment by stumpylog** [comment]
I was referring to these changes: https://github.com/zxing-cpp/zxing-cpp/pull/530

I think they will at least help, if not fix, but I won't have more information until the next release/build log to look at.

**Comment by axxel** [comment]
I see. I don't see how those changes will affect the issue with the missing cmake `find_package` detection of `pybind11`, though.

So this means nothing will happen until after the next upstream release? Would be nice if we could somehow find out beforehand if it will work to have the opportunity to fix any remaining issue and not have to wait for yet another release then.

**Comment by stumpylog** [comment]
The addition of pybind11 to the build dependencies in pyproject.toml and the inclusion of the C++ files in the sdist will both help, I think.

I don't know its possible to check a development version on Piwheels.  I think it scans or polls Pypi for releases to trigger a build

**Comment by axxel** [comment]
Now that 2.1 is released it builds successfully on Bullseye but still fails on Buster due to the old gcc. I don't intend to fix those issues as I would consider a gcc-8 to be outdated.

**Comment by stumpylog** [comment]
Perfectly reasonable to me!
