### ISSUE TITLE
Problem with package: cryptography Illegal Instruction on armv6

### ISSUE THREAD

**Issue by arthur-proglove** [piwheels/packages#348]
### Package name

cryptography

### Package version

39.0.2

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The cryptography package is causing a `Illegal instruction` on my Raspberry Pi 0 W.
I tried with the Raspbian image 2022-04-04 and 2023-02-21.
I did not debug further so I am not sure where the incompatibility comes from.

**Comment by arthur-proglove** [comment]
Interestingly enough, the issue already appears on 38.0.4 but not on 38.0.1

**Comment by grschneider** [comment]
I ran into the same issue with cryptography 40.0.1.

The following import causes it in my case:
```
>>> from cryptography.hazmat.primitives import padding
Illegal instruction
```

Cross verified version 39.0.2: same behaviour.

**Comment by bennuttall** [comment]
Fixed
