### ISSUE TITLE
Simplejson 3.16.1 deleted from Pypi

### ISSUE THREAD

**Issue by katzrkool** [piwheels/packages#35]
Package name: simplejson
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/simplejson
Link to piwheels page: https://www.piwheels.org/project/simplejson
Version: 3.16.1
Python version: 3.7
More information:
Due to compatibility issues, simplejson 3.16.1 was removed from pypi. 

[See the issue here](https://github.com/issues/237)

The 3.16.1 release is still available on piwheels, and breaks when installed. Would it be possible to remove the release to match with pypi?

**Comment by bennuttall** [comment]
Sorry I didn't see this right away - have deleted now
