### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by rtheil** [piwheels/packages#359]
### Package name

cryptography

### Package version

40.0.2

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Can't install cryptography 40.0.2 without rust compiler. 40.0.1 works great.

**Comment by bennuttall** [comment]
Fixed
