### ISSUE TITLE
Missing package: cmsis-pack-manager

### ISSUE THREAD

**Issue by flit** [piwheels/packages#36]
Package name: cmsis-pack-manager
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/cmsis-pack-manager
Link to piwheels page: https://www.piwheels.org/project/cmsis-pack-manager
Version: 0.2.8
Python version: all

More information: cmsis-pack-manager uses a Rust backend, and thus requires a recent Rust and Cargo installation. There doesn't appear to be any documentation or FAQ that covers what languages are supported on the build nodes.

**Comment by bennuttall** [comment]
Can you provide instructions to build this package on a Raspberry Pi?

**Comment by bennuttall** [comment]
Also you say this package is broken, but it looks like it's just missing. There's one old version built - is this broken?

**Comment by flit** [comment]
It wasn't clear if broken or missing was the right issue type. It's "broken" in the sense that it failed to build, whereas I interpreted "missing" meaning it somehow wasn't detected by piwheels. 😄 

The old version that built successfully was pure Python (and extremely slow). The 0.2.x versions have a new backend written in Rust that is super fast. The APIs are also incompatible between 0.1 and recent 0.2 versions.

It _should_ build via 'pip wheel' as long as you have Rust and Cargo installed via the `rustc` and `cargo` packages. I'm a little worried that the packaged Rust might be out of date. @theotherjimmy is the package owner—do you know if rustc v1.15.1 will work? If that's too old, the [rustup](https://rustup.rs/) tool can install the latest version.

Btw, this primarily all so users can install and run [pyOCD](https://github.com/mbedmicro/pyOCD) on RasPi. (cmsis-pack-manager is a dependency of pyOCD.)

**Comment by bennuttall** [comment]
Try building it on a Pi using Raspbian package dependencies only and let me know how you get on.

**Comment by flit** [comment]
Will do.

**Comment by flit** [comment]
Hi @bennuttall, do you have plans to support Rust based packages?

**Comment by bennuttall** [comment]
We're considering installing rustc but only from the Debian repo, so 1.41 in Buster: https://packages.debian.org/buster/rustc

Bullseye comes out next summer and that'll have something newer (currently has 1.46, experimental has 1.47).

**Comment by flit** [comment]
Ok, thanks!

**Comment by bennuttall** [comment]
Update: I installed cargo, setuptools_rust and conan - this fixed some other rust packages but not this one. Looks like the cargo version is too far behind:

```
error[E0658]: subslice patterns are unstable
```

Full error here: http://paste.debian.net/1182499/

**Comment by flit** [comment]
Thanks for the update.

cc @mbrossard

**Comment by flit** [comment]
@bennuttall On #163 you mentioned that "Alternatively, you can build the wheels and send to us for direct upload." Would that be possible for me to do with cmsis-pack-manager?

**Comment by flit** [comment]
@bennuttall Is it possible for me to upload wheels? Fortunately, cmsis-pack-manager builds successfully with Bullseye (🎉!). But Bullseye isn't released yet, and it would be beneficial to users to be able to use cmsis-pack-manager with Buster. Thanks!
