### ISSUE TITLE
Problem with package: numpy

### ISSUE THREAD

**Issue by pandaninjas** [piwheels/packages#360]
### Package name

numpy

### Package version

v1.24.3

### PyPI URL

https://pypi.org/project/numpy/

### piwheels URL

https://www.piwheels.org/project/numpy/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

v1.24.3 is being build for aarch64 instead of armv7l or armv6l

**Comment by bennuttall** [comment]
Thanks. I've rolled back a change we made and deleted all builds since then. It'll take a good few days to rebuild everything.
