### ISSUE TITLE
Missing package: os-sys

### ISSUE THREAD

**Issue by manhuy0402** [piwheels/packages#361]
### Package name

os-sys

### Package version

1.9.3

### PyPI URL

https://pypi.org/project/os-sys/

### piwheels URL

https://www.piwheels.org/project/os-sys/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
There's an issue with that version of the package which means it's not possible to build a wheel for that version. Nothing we can do and the maintainer has fixed it in subsequent releases.
