### ISSUE TITLE
Problem with package: cryptography 40.0.1 produces "Illegal Instruction"

### ISSUE THREAD

**Issue by fpcardoso** [piwheels/packages#362]
### Package name

cryptography

### Package version

40.0.1

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

OS version: Raspbian GNU/Linux 11 (bullseye) on Raspberry Pi Zero v1.1
uname -a : Linux raspberrypi 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux

On Raspberry Pi Zero v1.1, the cryptography module version 40.0.1 results in "Illegal Instruction". Downgrading to 38.0.0 doesn't produce any error.

This is the specific wheel that gets downloaded when I pip install cryptography: https://www.piwheels.org/simple/cryptography/cryptography-40.0.1-cp39-cp39-linux_armv6l.whl

**Comment by bennuttall** [comment]
This should be fixed now
