### ISSUE TITLE
Package issue: 

### ISSUE THREAD

**Issue by KathyGCY** [piwheels/packages#364]
### Package name

Prophet

### Package version

1.0.1

### PyPI URL

https://github.com/facebook/prophet

### piwheels URL

https://github.com/facebook/prophet

### Python version

- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

All PR suddenly started failing and returning 

> Failed building wheel for prophet.
> Python exception: ModuleNotFoundError: No module named 'numpy'

**Comment by bennuttall** [comment]
This is a Raspberry Pi package repository, not a general issue tracker for Python packages. I think you need to look elsewhere for help.
