### ISSUE TITLE
Missing package: safetensors

### ISSUE THREAD

**Issue by pandaninjas** [piwheels/packages#367]
### Package name

safetensors

### Package version

non 0.3.0

### PyPI URL

https://pypi.org/project/safetensors/

### piwheels URL

https://www.piwheels.org/project/safetensors/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

needs rust

**Comment by bennuttall** [comment]
Fixed
