### ISSUE TITLE
Problem with package: aenum (missing files inside whl)

### ISSUE THREAD

**Issue by dejvidq** [piwheels/packages#370]
### Package name

aenum

### Package version

3.1.14

### PyPI URL

https://pypi.org/project/aenum/

### piwheels URL

https://www.piwheels.org/project/aenum/

### Python version

- [x] Python 3.7
- [x] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Piwheels `aenum` whl file is broken, there are few files missing, so the package is not working.

aenum-3.1.14-py3-none-any.whl downloaded from pypi:
* `CHANGES`
* `LICENSE`
* `__init__.py`
* `_common.py`
* `_constant.py`
* `_enum.py`
* `_py2.py`
* `_py3.py`
* `_tuple.py`
* `doc`
* `test.py`
* `test_v3.py`
* `test_v37.py`

aenum-3.1.14-py3-none-any.whl downloaded from piwheels:
* `CHANGES`
* `LICENSE`
* `__init__.py`
* `_py2.py`
* `_py3.py`
* `doc`
* `test.py`
* `test_v3.py`

Missing files:
* `_common.py`
* `_constant.py`
* `_enum.py`
* `_tuple.py`
* `test_v37.py`

**Comment by bennuttall** [comment]
It's up to the maintainers to ensure that files are included in wheels - we just automate building them from source. It's out of our control.
