### ISSUE TITLE
Missing package: monotonic-align

### ISSUE THREAD

**Issue by akeepgoing** [piwheels/packages#371]
### Package name

monotonic-align

### Package version

0.0.3

### PyPI URL

https://pypi.org/project/monotonic-align/

### piwheels URL

https://www.piwheels.org/project/monotonic-align/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
Huh? There is no such version on PyPI:

![Screenshot from 2023-06-28 11-26-17](https://github.com/piwheels/packages/assets/1609725/76ec2b48-e0c6-4fe5-a264-5a01fe0c16ba)

https://pypi.org/project/monotonic-align/#history
