### ISSUE TITLE
Missing package: similari-trackers-rs

### ISSUE THREAD

**Issue by r-bt** [piwheels/packages#376]
### Package name

similari-trackers-rs

### Package version

all

### PyPI URL

https://pypi.org/project/similari-trackers-rs/

### piwheels URL

https://www.piwheels.org/project/similari-trackers-rs/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Seems like it's missing as it needs rust to compile

**Comment by bennuttall** [comment]
Related to https://github.com/piwheels/piwheels/pull/328

**Comment by bennuttall** [comment]
Fixed
