### ISSUE TITLE
Missing package: dacite

### ISSUE THREAD

**Issue by sv3ndk** [piwheels/packages#377]
### Package name

dacite

### Package version

1.8.1

### PyPI URL

https://pypi.org/project/dacite/

### piwheels URL

https://www.piwheels.org/project/dacite/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The cause of the issue, as indicated in [piwheels json project](https://www.piwheels.org/project/dacite/json/), is due to missing sources published by dacite.

For reference, the issue on Dacite side is here: https://github.com/konradhalas/dacite/issues/235

**Comment by bennuttall** [comment]
Correct - also noted on the project page itself:

![Screenshot from 2023-07-21 18-10-59](https://github.com/piwheels/packages/assets/1609725/ed9c361c-08d5-43b4-ae4b-3fd9e35e5d26)
