### ISSUE TITLE
Package issue: 

### ISSUE THREAD

**Issue by glyph** [piwheels/packages#378]
### Package name

cryptography

### Package version

all

### PyPI URL

https://pypi.org/project/cryptography

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Cryptography requires a rust compiler to build, but none is provided in the piwheels build environment, as shown in the build log: https://www.piwheels.org/logs/0000/1004/3600.txt

**Comment by bennuttall** [comment]
Duplicate of https://github.com/piwheels/packages/issues/359

**Comment by glyph** [comment]
Sorry for the dup. Could have sworn that didn't show up in a search, but I see it now!

**Comment by bennuttall** [comment]
It's been an annoying issue, getting a rustup installation that works for the piwheels process. There's a PR for it at https://github.com/piwheels/piwheels/pull/328 but it's a slow/difficult testing process. Need to take another look soon.

**Comment by xmatthias** [comment]
@bennuttall cryptography is starting to become a pain - it's now got 3 open security vulnerabilities we can't get fixed as the pi installation is not working with newer versions.

Unfortunately, it's unclear (to me) what's missing in the PR linked - or how one could assist in getting that merged, to get cryptography working again.

**Comment by bennuttall** [comment]
> Unfortunately, it's unclear (to me) what's missing in the PR linked 

We've run builds with the changes in that PR and the builds still fail
