### ISSUE TITLE
Missing package: typechat

### ISSUE THREAD

**Issue by YixuanAllen** [piwheels/packages#383]
### Package name

typechat

### Package version

0.0.1

### PyPI URL

https://pypi.org/project/typechat/

### piwheels URL

https://www.piwheels.org/project/typechat/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

When I want to use TypeChat component on my Pycharm project. I did 'from typechat import TypeChat', it had wrong that ImportError: cannot import name 'TypeChat' from 'typechat'.

**Comment by bennuttall** [comment]
This doesn't sound like a piwheels issue. Please look up support for the package itself.
