### ISSUE TITLE
Problem with package: mlsgrid-api

### ISSUE THREAD

**Issue by RealEstateSaga** [piwheels/packages#384]
### Package name

mlsgrid-api

### Package version

1.0

### PyPI URL

https://pypi.org/project/mlsgrid-api/

### piwheels URL

https://www.piwheels.org/project/mlsgrid-api/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

Coudl you please contact me mike@1mw.com

Thanks!

**Comment by RealEstateSaga** [comment]
Should I not inquire, is that what you are saying?

Mike Wilen
612-400-9000
Wilen Coldwell Banker

On Aug 26, 2023, at 7:11 AM, Ben Nuttall ***@***.***> wrote:


Closed #384 <https://github.com/piwheels/packages/issues/384> as completed.

**Comment by bennuttall** [comment]
I'm not sure what you expected.

piwheels is a package repository for Raspberry Pi, which I maintain. You filed an issue against a package, asked me to contact you, and then treated it like I'd applied for a job.

**Comment by RealEstateSaga** [comment]
How are you sir?

Again, my apologies.

Would you have any guidance for us on the best way to move forward on designing and completing the sync with MLSGrid.

What would you charge to complete a project such as this?


On Aug 27, 2023, at 5:25 AM, Ben Nuttall ***@***.***> wrote:


I'm not sure what you expected.

piwheels is a package repository for Raspberry Pi, which I maintain. You filed an issue against a package, asked me to contact you, and then treated it like I'd applied for a job.
