### ISSUE TITLE
Missing package: maturin

### ISSUE THREAD

**Issue by marceloalencar** [piwheels/packages#387]
### Package name

maturin

### Package version

\>=1.0.0

### PyPI URL

https://pypi.org/project/maturin/

### piwheels URL

https://www.piwheels.org/project/maturin/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Failed builds shows ` error: can't find Rust compiler`.

**Comment by bennuttall** [comment]
Fixed
