### ISSUE TITLE
grpcio-tools: undefined symbol: __atomic_fetch_add_8

### ISSUE THREAD

**Issue by pvphan** [piwheels/packages#39]
Package name: grpcio-tools
Issue type: "undefined symbol: __atomic_fetch_add_8" when invoking package
Link to PyPI page: https://pypi.org/project/grpcio-tools/
Link to piwheels page: https://www.piwheels.org/project/grpcio-tools/
Version: 1.22.0 or all
Python version: 3.7.3 or all

More information:

Occurs on Raspberry Pi 4 running raspbian/buster, python 3.7.3 (via virtualenv) when trying to generate *_pb2.py and *_pb2_grpc.py files. Issue encountered while following the [grpc documentation for python](https://www.grpc.io/docs/quickstart/python/).

```
$ git clone -b v1.22.0 https://github.com/grpc/grpc
$ cd grpc/examples/python/helloworld
$ python -m grpc_tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/helloworld.proto
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.virtualenvs/<envname>/lib/python3.7/site-packages/grpc_tools/protoc.py", line 20, in <module>
    from grpc_tools import _protoc_compiler
ImportError: /home/pi/.virtualenvs/<envname>/lib/python3.7/site-packages/grpc_tools/_protoc_compiler.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8
```

For what it's worth, I was able to resolve the issue by building grpcio-tools from source via the [grpcio_tools README](https://github.com/grpc/grpc/tree/master/tools/distrib/python/grpcio_tools) with the following deviations from their docs.

1. [Building and installing bazel from source](https://docs.bazel.build/versions/master/install-compile-source.html). 

2. Modify grpc/tools/distrib/python/make_grpcio_tools.py so that `python ../make_grpcio_tools.py` would succeed (would choke during a list comprehension otherwise):

```
--- a/tools/distrib/python/make_grpcio_tools.py                      
+++ b/tools/distrib/python/make_grpcio_tools.py                      
@@ -94,13 +94,13 @@ def protobuf_submodule_commit_hash():            
     os.chdir(GRPC_PROTOBUF_SUBMODULE_ROOT)                          
     output = subprocess.check_output(['git', 'rev-parse', 'HEAD'])  
     os.chdir(cwd)                                                   
-    return output.splitlines()[0].strip()                           
+    return str(output.splitlines()[0].strip())[2:-1]                
                                                                     
                                                                     
 def bazel_query(query):                                             
     print('Running "bazel query %s"' % query)                       
     output = subprocess.check_output([BAZEL_DEPS, query])           
-    return output.splitlines()                                      
+    return list(map(lambda x: str(x)[2:-1], output.splitlines()))   
```

3. Substituting their `GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .` command with:

```
CC=`which clang` GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install . --ignore-installed six
```

I'm unsure if the `--ignore-installed six` actually does anything, but that's what worked in this case. the CC=`which clang` definitely made a difference though. Without that, I was still getting the same __atomic_fetch_add_8 error.

**Comment by bennuttall** [comment]
This is a baffling issue - we've just experienced the same with the new opencv builds, and we have a workaround for it: #59 - does that work for grpcio-tools?
