### ISSUE TITLE
Missing package: lxml

### ISSUE THREAD

**Issue by holta** [piwheels/packages#391]
### Package name

lxml

### Package version

4.9.3

### PyPI URL

https://pypi.org/project/lxml/

### piwheels URL

https://www.piwheels.org/project/lxml/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Can a "cp311" (for Python 3.11) `lxml` wheel be published to https://piwheels.org/simple/lxml/ ?

Thanks if possible — https://bugs.launchpad.net/lxml/+bug/1969912/comments/7 confirms that lxml does indeed work with Python 3.11 on other OS's/architectures!

Background / FYI — this is currently preventing Calibre-Web from being installed on "32-bit" Raspberry Pi OS 12 Bookworm pre-released, as documented here:

- iiab/iiab#3642

cc: @deldesir

**Comment by bennuttall** [comment]
We are working through the backlog now - it'll be another week maybe

**Comment by holta** [comment]
> We are working through the backlog now - it'll be another week maybe

Awesome!

Huge thanks @bennuttall & all 🌎 🌍 🌏 who are helping!

**Comment by holta** [comment]
Curiously (just FYI) lxml-4.9.3 for Python 3.11 never appeared here:

https://piwheels.org/simple/lxml/

**Comment by bennuttall** [comment]
I just checked and it failed. The build log is here: https://www.piwheels.org/logs/0000/1080/1409.txt

It looks truncated, so I wouldn't be surprised if it just ran out of disk. I've removed the build so it should re-attempt soon.

**Comment by holta** [comment]
> I just checked and it failed. The build log is here: https://www.piwheels.org/logs/0000/1080/1409.txt
> 
> It looks truncated, so I wouldn't be surprised if it just ran out of disk. I've removed the build so it should re-attempt soon.

Wow, it's now done, huge thanks @bennuttall !

![image](https://github.com/piwheels/packages/assets/2458907/fe7e5cd5-34d5-400b-9f69-e94942303932)

**Comment by bennuttall** [comment]
Great. But annoying that other packages may have failed the same way! Will just have to wait for reports.
