### ISSUE TITLE
Problem with package: ej2-streamlit-grids

### ISSUE THREAD

**Issue by Vishnu-Moorthi** [piwheels/packages#399]
### Package name

ej2-streamlit-grids

### Package version

all

### PyPI URL

https://pypi.org/project/ej2-streamlit-grids/

### piwheels URL

https://www.piwheels.org/project/ej2-streamlit-grids/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [ ] Yes

### I have checked for duplicate issues

- [ ] Yes

### I am the maintainer

- [X] Yes

### More information

Build status of this package is not displayed for Python 3.11, and also there is no column for the Python 3.7 and Python 3.9. How to make this package to be build in all these package and to display the build result of this package.

**Comment by bennuttall** [comment]
Did you see the banner at the top of the page? 

<img width="579" alt="Screenshot 2023-10-26 at 10 16 02 am" src="https://github.com/piwheels/packages/assets/1609725/c9fee9b3-4b8c-4c0e-9b2a-b2caa14d194e">

https://github.com/piwheels/packages/issues/388

Is there an issue with a missing version? The latest version is available

**Comment by Vishnu-Moorthi** [comment]
Ok for **Bookworm**, May I know why the package is not builded for **Buster** and **Bullseye**.

**Comment by bennuttall** [comment]
It's just that the project pages are broken (see link above) - that's why the other OS columns are not shown. The version that's built is a pure Python wheel so it works on all Python 3.x versions: `ej2_streamlit_grids-23.1.36-py3-none-any.whl`
