### ISSUE TITLE
Missing package: tables

### ISSUE THREAD

**Issue by xmatthias** [piwheels/packages#400]
### Package name

tables

### Package version

3.9.1

### PyPI URL

https://pypi.org/project/tables/

### piwheels URL

https://www.piwheels.org/project/tables/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [ ] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

Seems like the last 2 versions failed to build? unfortunately, since the addition of 3.11, the builds don't seem to be visible anymore - so it's unclear if it's just "in the backlog, not having taken it's turn so far" - or if there's been issues.

That said, the release has been 20 days ago (October 6th, according to pypi) - so i thought that might warrant an issue here.

**Comment by bennuttall** [comment]
Here's the build log: https://www.piwheels.org/logs/0000/1095/6291.txt

It failed trying to build [blosc2](https://piwheels.org/project/blosc2/)

The build log for that is: https://www.piwheels.org/logs/0000/1095/0453.txt

I've opened #401 to track it

**Comment by xmatthias** [comment]
Seems to be working now 👍 

Thanks a lot for your time and investigation!

![grafik](https://github.com/piwheels/packages/assets/5024695/201ac279-93d7-42f7-b4c5-0d745ae32f38)

**Comment by bennuttall** [comment]
Great
