### ISSUE TITLE
Problem with package: zxing-cpp

### ISSUE THREAD

**Issue by peanball** [piwheels/packages#403]
### Package name

zxing-cpp

### Package version

1.4.0

### PyPI URL

https://pypi.org/project/zxing-cpp/

### piwheels URL

https://www.piwheels.org/project/zxing-cpp/

### Python version

- [X] Python 3.7
- [ ] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

Version 1.4.0 builds fine on a raspberry pi using Buster. The last attempted build seemed to have failed because a Git checkout didn't work. Is it possible to re-trigger that again?

I had no luck building version 2.1.0 on raspbian buster, did not try 2.0.0.

**Comment by bennuttall** [comment]
We don't allow git clones during builds (it looks like they removed that from the process in the latest version).

**Comment by peanball** [comment]
Ok, fair. I'll build a local wheel then and use that.

The build process is admittedly convoluted on this package. Unfortunately the latest version doesn't seem to compile for Python 3.7 anymore.
