### ISSUE TITLE
Missing package: opencv-python

### ISSUE THREAD

**Issue by stopcome** [piwheels/packages#405]
### Package name

opencv-python

### Package version

4.6

### PyPI URL

https://pypi.org/project/opencv-python/

### piwheels URL

https://www.piwheels.org/project/opencv-python/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [ ] Yes

### I have checked for duplicate issues

- [ ] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
"I have checked for duplicate issues"

¯\\_(ツ)_/¯
