### ISSUE TITLE
Missing package: pyE2EE

### ISSUE THREAD

**Issue by mzaarsnipersk13** [piwheels/packages#413]
### Package name

pye2ee

### Package version

all

### PyPI URL

https://pypi.org/project/pye2ee/

### piwheels URL

https://www.piwheels.org/project/pye2ee/

### Python version

- [x] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [X] Yes

### More information

OK

**Comment by bennuttall** [comment]
There's a pure Python wheel available. What's the problem? It's not missing
