### ISSUE TITLE
Missing package: Pillow version 10.2.0

### ISSUE THREAD

**Issue by yakirm-cr** [piwheels/packages#419]
### Package name

pillow

### Package version

10.2.0

### PyPI URL

https://pypi.org/project/pillow/

### piwheels URL

https://www.piwheels.org/project/pillow/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [x] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
Looks like the master went down over Christmas. I've restarted it so it'll pick up new releases soon.

**Comment by yakirm-cr** [comment]
@bennuttall 
I can see that for Python 3.9 and Python 3.11 the issue is resolved.
Should the issue be closed?

**Comment by bennuttall** [comment]
Yes - thanks
