### ISSUE TITLE
Missing package: picamera

### ISSUE THREAD

**Issue by StephanCandA** [piwheels/packages#420]
### Package name

picamera

### Package version

1.13 

### PyPI URL

https://pypi.org/project/picamera/

### piwheels URL

https://www.piwheels.org/project/picamera/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
The project page layout has a bug which shows the wrong icon for 3.11, but picamera is a pure python package, so the wheel that's available will work for Python 3.11.
