### ISSUE TITLE
Missing package: netifaces-plus version 0.12.1

### ISSUE THREAD

**Issue by yakirm-cr** [piwheels/packages#423]
### Package name

netifaces-plus

### Package version

0.12.1

### PyPI URL

https://pypi.org/project/netifaces-plus/

### piwheels URL

https://www.piwheels.org/project/netifaces-plus/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
No source distribution is available from PyPI, there's nothing to build: https://pypi.org/project/netifaces-plus/#files
