### ISSUE TITLE
Problem with package: pynauty

### ISSUE THREAD

**Issue by annysc** [piwheels/packages#424]
### Package name

pynauty

### Package version

2.8.6, 1.1.2 and maybe others

### PyPI URL

https://pypi.org/project/pynauty/

### piwheels URL

https://www.piwheels.org/project/pynauty/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [ ] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

I get an error about the wheel not building. I've tried using Python 3.11 and 3.10, pynauty 2.8.6 and the version before, two different computers (both Windows 11 Home). Interestingly, when I first tried it it worked and I used the package, but the next day it wasn't there anymore (when I did pip list in my environment, and it wasn't in the base environment either) and I couldn't install it. Below is a part of the error message.

Building wheels for collected packages: pynauty
  Building wheel for pynauty (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [258 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pynauty
      copying src\pynauty\graph.py -> build\lib.win-amd64-cpython-311\pynauty
      copying src\pynauty\__init__.py -> build\lib.win-amd64-cpython-311\pynauty
      copying src\pynauty\__main__.py -> build\lib.win-amd64-cpython-311\pynauty
      running egg_info
      writing pynauty.egg-info\PKG-INFO
      writing dependency_links to pynauty.egg-info\dependency_links.txt
      writing top-level names to pynauty.egg-info\top_level.txt
      reading manifest file 'pynauty.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '__pycache__\*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.o' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'pynauty.egg-info\SOURCES.txt'
      C:\workspace\droplet\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pynauty.docs.doctrees' as data is deprecated, please list it in `packages`.
          !!

**Comment by bennuttall** [comment]
"I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi"
