### ISSUE TITLE
tkterminal: get_output method is responding previous output not current

### ISSUE THREAD

**Issue by samratahirwar** [piwheels/packages#426]
### Package name

tkterminal

### Package version

all

### PyPI URL

https://pypi.org/project/tkterminal/

### piwheels URL

https://www.piwheels.org/project/tkterminal/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [ ] Yes

### I have checked for duplicate issues

- [ ] Yes

### I am the maintainer

- [ ] Yes

### More information

        self.terminal = Terminal(pady=5, padx=5)
        self.terminal.shell = True
        self.terminal.linebar = True
        self.terminal.pack(expand=True, fill='both')

    def run_terminal(self,command):
        self.terminal.run_command(command)
        return self.terminal.get_output()

in this case the get_output method will return me the output of last command not the current one which processed, if current command is the first command then it will raise error 

Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/mnt/o/a/z/z.py", line 39, in compile_code
    output=self.get_output()
  File "/mnt/o/a/z/z.py", line 28, in get_output
    return self.terminal.get_output()
  File "/home/xxx/.local/lib/python3.10/site-packages/tkterminal/ternimal.py", line 402, in get_output
    if self._out or self._err:
AttributeError: 'Terminal' object has no attribute '_out'

kindly provide the fix

**Comment by bennuttall** [comment]
This is not the place to report this issue
