### ISSUE TITLE
Missing package: audio-mouse

### ISSUE THREAD

**Issue by DTSH-373** [piwheels/packages#427]
### Package name

audio-mouse

### Package version

1.0.2

### PyPI URL

https://pypi.org/project/audio-mouse/

### piwheels URL

https://www.piwheels.org/project/audio-mouse/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

adSADADdASDadADwq

**Comment by bennuttall** [comment]
It's not missing, it's available.
