### ISSUE TITLE
Missing package: Polygon3

### ISSUE THREAD

**Issue by xian1319** [piwheels/packages#429]
### Package name

polygon3

### Package version

Polygon3‑3.0.9.1‑cp39‑cp39‑win_amd64.whl

### PyPI URL

https://pypi.org/project/polygon3/

### piwheels URL

https://www.piwheels.org/project/polygon3/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [ ] Yes

### I have checked for duplicate issues

- [ ] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
"I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi"
