### ISSUE TITLE
Problem with package: rpi-ws281x

### ISSUE THREAD

**Issue by samskiter** [piwheels/packages#433]
### Package name

rpi-ws281x

### Package version

5.0.0

### PyPI URL

https://pypi.org/project/rpi-ws281x/

### piwheels URL

https://www.piwheels.org/project/rpi-ws281x/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

3.11 build is 'failing' how could this be debugged/fixed?

**Comment by bennuttall** [comment]
Fixed - thanks
