### ISSUE TITLE
Missing package: pydantic-core

### ISSUE THREAD

**Issue by samskiter** [piwheels/packages#435]
### Package name

pydantic-core

### Package version

2.16.3

### PyPI URL

https://pypi.org/project/pydantic-core/

### piwheels URL

https://www.piwheels.org/project/pydantic-core/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
I've fixed all the 3.9 builds but recent versions of pydantic don't support 3.7
