### ISSUE TITLE
Problem with package: motioneye

### ISSUE THREAD

**Issue by dojomotion** [piwheels/packages#439]
### Package name

motioneye

### Package version

0.42.1

### PyPI URL

https://pypi.org/project/motioneye/

### piwheels URL

https://www.piwheels.org/project/motioneye/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

within a virtual environment.  Used "pip3 install motioneye==0.42.1".  Used "pip3 install motion".

(venv_cam) pi@rpi115:~/prgs/venv_cam/bin $ python meyectl startserver
Traceback (most recent call last):
  File "/home/pi/prgs/venv_cam/bin/meyectl", line 5, in <module>
    from motioneye.meyectl import main
  File "/home/pi/prgs/venv_cam/lib/python3.9/site-packages/motioneye/meyectl.py", line 28, in <module>  import settings
ModuleNotFoundError: No module named 'settings'

**Comment by bennuttall** [comment]
I don't think this is a piwheels issue. Can you open an issue with the project itself? If it turns out to be an issue with the way the wheel was built, please reopen this issue and let us know the details.

**Comment by dojomotion** [comment]
ok, thanks.  Will try that way.  best regard's.
