### ISSUE TITLE
Missing package: scipy

### ISSUE THREAD

**Issue by DerOetzi** [piwheels/packages#441]
### Package name

scipy

### Package version

1.13.0rc1

### PyPI URL

https://pypi.org/project/scipy/

### piwheels URL

https://www.piwheels.org/project/scipy/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
It seems to be there now, must have caught up
