### ISSUE TITLE
Missing package: regex

### ISSUE THREAD

**Issue by MichaIng** [piwheels/packages#442]
### Package name

regex

### Package version

2024-04-16 and 2023-12-24

### PyPI URL

https://pypi.org/project/regex/

### piwheels URL

https://www.piwheels.org/project/regex/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

Recent Bullseye builds for this wheel fail, due to insufficient disc space, it seems:
```
2024-04-16T21:40:33,089   regex_3/_regex.c:26490:1: fatal error: error closing /tmp/ccIjk05e.s: No space left on device
```
```
2024-01-05T11:10:32,324 OSError: [Errno 28] No space left on device
```

**Comment by bennuttall** [comment]
Thanks. I've been meaning to check for these and clear them out. I've kicked off these builds again so keep an eye on the page for updates.

**Comment by bennuttall** [comment]
Built :+1:
