### ISSUE TITLE
Missing package: codac

### ISSUE THREAD

**Issue by lebarsfa** [piwheels/packages#443]
### Package name

codac

### Package version

all

### PyPI URL

https://pypi.org/project/codac/

### piwheels URL

https://www.piwheels.org/project/codac/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [X] Yes

### More information

Hello, I am one of the maintainers of https://github.com/codac-team/codac for its packages part. We are currently not ready to provide a Python source package that would easily build on piwheels automatically, but we have a specific script https://github.com/lebarsfa/codac/blob/master/packages/temporary/gennewcodacpi_armhf.sh which can build wheels for the Raspberry Pi. 
Is it possible to upload those wheels (available on https://packages.ensta-bretagne.fr/piwheels/ ) on piwheels, or what should be the procedure so that we can provide our wheels on piwheels? 

The armv6l files were built from a Mac M1 and armv7l from a pi4 (it is not clear why with the same script Docker gives different architectures…) and if I understood well, we won't be able to upload both on PyPI (or maybe just if they are identical?).

**Comment by bennuttall** [comment]
I can import them to piwheels from there.

Are you sure they're compatible with Pi? I'm always cautious of cross-compiled arm stuff.

**Comment by lebarsfa** [comment]
For now, I tested on a pi4 with Raspbian Buster, Bullseye, Bookworm, and a pi0w with Bookworm.

**Comment by bennuttall** [comment]
Thanks - I've imported them: https://www.piwheels.org/project/codac/

If you want to email me when you have future releases, use `ben [at] bennuttall [dot] com`

**Comment by lebarsfa** [comment]
OK, many thanks!
