### ISSUE TITLE
Missing package: opencv-contrib-python

### ISSUE THREAD

**Issue by JavadRah** [piwheels/packages#45]
Package name: opencv-contrib-python
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/opencv-contrib-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python/
Version: 4.1.0.25
Python version: 3.7
More information:

**Comment by bennuttall** [comment]
Yet another duplicate of pinned issue #28
