### ISSUE TITLE
Missing package: scikit-learn

### ISSUE THREAD

**Issue by DerOetzi** [piwheels/packages#451]
### Package name

scikit-learn

### Package version

1.5.0

### PyPI URL

https://pypi.org/project/scikit-learn/

### piwheels URL

https://www.piwheels.org/project/scikit-learn/

### Python version

- [X] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by DerOetzi** [comment]
Same for 1.5.1

As the lower version have security alerts it might be urgent. What can I do to get this build fixed. Can I somehow contribute?

**Comment by bennuttall** [comment]
See if you can build it yourself first. Look at their website for build requirements to build from source and run `pip3 wheel scikit-learn==1.5.1`

**Comment by bennuttall** [comment]
I've tried this and reported here: https://github.com/scikit-learn/scikit-learn/discussions/29430

**Comment by DerOetzi** [comment]
I have tried on my rpi with bookworm and get the same errors. But unfortunately I have no idea what's wrong from the error messages

**Comment by DerOetzi** [comment]
Any updates on this?

**Comment by DerOetzi** [comment]
I just have seen a package for v1.5.2 was build for python 3.9 but not for 3.11 bookworm. Maybe @bennuttall you can investigate what is different?

**Comment by DerOetzi** [comment]
From new version 1.6.0 the packages are available again
