### ISSUE TITLE
Missing package: numpy

### ISSUE THREAD

**Issue by bsimmo** [piwheels/packages#456]
### Package name

numpy

### Package version

2.0.0

### PyPI URL

https://pypi.org/project/numpy/

### piwheels URL

https://www.piwheels.org/project/numpy/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

Big X not a tick next to it.

It also seems to fail when it tries to build locally (bookworm Python 3.11, Pi3A+ & Zero2W) since it cannot find the wheel.

**Comment by bennuttall** [comment]
Not sure what happened there. I've kicked off another build.

**Comment by bennuttall** [comment]
It's there now
