### ISSUE TITLE
Pandas 0.25.0 missing for Python 3.4, 3.5

### ISSUE THREAD

**Issue by charlesoblack** [piwheels/packages#46]
Package name: pandas
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pandas
Link to piwheels page: https://www.piwheels.org/project/pandas
Version: 0.25.0
Python version: 3.4, 3.5
More information:

pandas 0.25.0 implements pandas.DataFrame.explode which is super useful, but not present in 0.25.0rc0. Could we maybe re-run the build attempt for Python 3.4/3.5?

**Comment by bennuttall** [comment]
Weird - 0.25.0rc0 built ok on cp35 but 0.25.0 didn't.

It's not expected to build on cp34 any more as they only support >=3.5

Anyway, here's the build log: http://paste.ubuntu.com/p/sG82P8dq5v/

**Comment by Naohiro2g** [comment]
I could make it at hand and I found it requires latest numpy, version 1.17.0 to compile.
The build attemp shows it is using numpy-1.17.0rc2, is this something bad?  I did not try it with rc2, though. 
BTW, it takes 75 minutes with Raspi-3B.

**Comment by Naohiro2g** [comment]
The reason why numpy 1.17rc2 was there at that time:
Jul 5  pandas 0.25.0rc0
Jul 16  numpy 1.17rc2
Jul 19  pandas 0.25.0
Jul 27  numpy 1.17

I'm not sure but is it safe to use rc version to compile?

**Comment by bennuttall** [comment]
It's rebuilding now, let's see what happens.

**Comment by bennuttall** [comment]
Success! https://www.piwheels.org/project/pandas/

**Comment by charlesoblack** [comment]
Thanks for your help guys! I'll install it on my pi and close soon.
