### ISSUE TITLE
Missing package: numpy

### ISSUE THREAD

**Issue by yakirm-cr** [piwheels/packages#460]
### Package name

numpy

### Package version

2.0.1

### PyPI URL

https://pypi.org/project/numpy/

### piwheels URL

https://www.piwheels.org/project/numpy/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
Rebuild pending
