### ISSUE TITLE
Missing package: fastexcel

### ISSUE THREAD

**Issue by MarcelBeining** [piwheels/packages#470]
### Package name

fastexcel

### Package version

all

### PyPI URL

https://pypi.org/project/fastexcel/

### piwheels URL

https://www.piwheels.org/project/fastexcel/

### Python version

- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
There's no source distribution provided so there's nothing for us to build: https://pypi.org/project/fastexcel/#files

Are you sure you want to use this library on a Raspberry Pi? If so, there's nothing we can do unless the maintainers upload a source distribution to PyPI so you'll have to open an issue with them.
