### ISSUE TITLE
Missing package: pydantic-core

### ISSUE THREAD

**Issue by Kestranor** [piwheels/packages#472]
### Package name

pydantic-core

### Package version

2.23.4

### PyPI URL

https://pypi.org/project/pydantic-core/

### piwheels URL

https://www.piwheels.org/project/pydantic-core/

### Python version

- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

It seems that the build for this version has failed for Python 3.11. Please check it. My Raspberry Pi Zero has no chance to build it by itself :-)

EDIT:
"Why is this a problem, a more up to date version of the core is available and builds normally?"
Because the latest version of Pydantic still includes core version 2.23.4. After asking the pydantic team, the latest version of the core, 2.24 (which actually builds), will only be included in Pydantic 2.10, which has no clear release date (see the mention linked in this issue). This essentially means that anything that includes pydantic as a dependency as of now will try to pull the 2.23.4 version of the core, which has no wheel. In my use case, this means that I currently cannot install google-generativeai on my pi, due to the dependency on pydantic.

**Comment by Kestranor** [comment]
More info:
"Why is this a problem, a more up to date version of the core is available and builds normally?"
Because the latest version of Pydantic still includes core version 2.23.4. After asking the pydantic team, the latest version of the core, 2.24 (which actually builds), will only be included in Pydantic 2.10, which has no clear release date (see the mention linked in this isshe). This essentially means that anything that includes pydantic as a dependency as of now will try to pull the 2.23.4 version of the core, which has no wheel. In my use case, this means that I currently cannot install google-generativeai on my pi, due to the dependency on pydantic.

**Comment by bennuttall** [comment]
Queued for rebuild

**Comment by Kestranor** [comment]
And now it's built successfully. Thanks! Closing the ticket.
