### ISSUE TITLE
Issue with Librosa on arm32v7/ubuntu:18.04

### ISSUE THREAD

**Issue by ksaye** [piwheels/packages#49]
Package name: librosa

Trying to install LIbrosa on arm32v7/ubuntu:18.04 fails

Getting the following error:

  ERROR: Could not find a version that satisfies the requirement scikit-learn!=0.19.0,>=0.14.0 (from librosa) (from versions: none)
ERROR: No matching distribution found for scikit-learn!=0.19.0,>=0.14.0 (from librosa)

Docker File below:

```bash
FROM arm32v7/ubuntu:18.04

RUN apt-get update \
    && apt-get install -y \
    libboost-python-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    liblapack-dev \
    libblas-dev \
    gfortran \
    python3.5 \
    python3-pip \
    wget \
    inetutils-traceroute \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip3 install setuptools wheel
RUN pip3 install --index-url=https://www.piwheels.org/simple librosa
```

**Comment by bennuttall** [comment]
Ubuntu 18.04 ships with Python 3.6. Since we only build on Raspbian, we have wheels for Python 3.4 (Jessie), 3.5 (Stretch) and 3.7 (Buster).

@waveform80 is planning to create an Ubuntu-specific piwheels instance at some point.

P.S. Please use issue templates in future
