### ISSUE TITLE
Missing package: Kivy

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#5]
Missing package
Package name: `Kivy`
Link to PyPI page: https://pypi.org/project/kivy
Link to piwheels page: https://www.piwheels.org/project/kivy
Version: all

**Comment by bennuttall** [comment]
Sorry, didn't get around to looking into this. Looks like we've successfully built the latest release for 3.5 and 3.7. Do you want to give it a try and let us know how it looks?

https://www.piwheels.org/project/kivy/

**Comment by Lauszus** [comment]
@bennuttall FYI Kivy now cross compiles wheels for the Raspberry Pi: https://github.com/kivy/kivy/pull/6568 and https://github.com/kivy/kivy/pull/6662.

Maybe piwheels could simply host these?

**Comment by bennuttall** [comment]
@Lauszus Great! That would be fine, we can import wheels. My only concern is that I saw a comment about your wheels that they only support Pi 4 - is that correct? Is that with Raspbian Buster?

pip is able to distinguish between Pi 1/Zero (`armv6l`) and Pi 2/3/4 (`armv7l`) but not individually, so if we hosted a Kivvy `armv7l` wheel people would expect it to work on Pi 3.

**Comment by Lauszus** [comment]
@bennuttall no that was my first assumption. I got the same wheel working on both the Raspberry 3 and 4 - see: https://github.com/kivy/kivy/pull/6662#issuecomment-573221825.

I have not tested it on a Raspberry Pi 1 and 2, but I can't see no reason why it shouldn't work since it works with the 3.

**Comment by bennuttall** [comment]
This is now building successfully
