### ISSUE TITLE
opencv-contrib-python not available for python 3.7 (Raspbian Buster)

### ISSUE THREAD

**Issue by SylvainRoy** [piwheels/packages#51]
Package name: opencv-contrib-python
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: all (but 4.1.0.25 in particular)
Python version: 3.7.3
More information: It's just not available in piwheels for the time being.

Here is the error I got with pipenv:

```bash
[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.1.0.25 (from -r /tmp/pipenv-c8qqn10p-requirements/pipenv-1cdg5ij6-requirement.txt (line 1)) (from versions: none)', 'ERROR: No matching distribution found for opencv-contrib-python==4.1.0.25 (from -r /tmp/pipenv-c8qqn10p-requirements/pipenv-1cdg5ij6-requirement.txt (line 1))']
```

**Comment by bennuttall** [comment]
Duplicate of #28
