### ISSUE TITLE
opencv-python-headless requires GTK-3

### ISSUE THREAD

**Issue by embie27** [piwheels/packages#56]
Package name: opencv-python-headless
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/opencv-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-python-headless/
Version: e.g. 3.4.3.18
Python version: e.g. 3.7
More information:

opencv-python-headless seems to require GTK3.0.

Importing the package:
```python
import cv2
```

Leads to the following error:
```
Import Error: libgtk-3.so.0: cannot  open shared object file  No such file or directory
```

**Comment by bennuttall** [comment]
https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/

**Comment by embie27** [comment]
But why does the headless version require GTK?

**Comment by bennuttall** [comment]
@waveform80?
