### ISSUE TITLE
Missing package: pygame 2.0.0.dev4

### ISSUE THREAD

**Issue by meirg** [piwheels/packages#57]
Package name: pygame
Issue type: Missing package version 2.0.0.dev4 build (temporary skip)
Link to PyPI page: https://pypi.org/project/pygame
Link to piwheels page: https://www.piwheels.org/project/pygame
Version: 2.0.0.dev4
Python version: all
More information:
There are no builds for version 2.0.0.dev4, released Oct 7th. Under skip it says temporary skip, but there is no reason stated.

Please let me know if there is anything I can do to help.

Thanks

**Comment by bennuttall** [comment]
The build dependency calculation takes too long for pygame, so we had to skip it. I've kicked off manual builds for cp45m and cp37m and I'll import them when they're done.

**Comment by bennuttall** [comment]
Done: https://www.piwheels.org/project/pygame/
