### ISSUE TITLE
opencv: undefined symbol: __atomic_fetch_add_8

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#59]
Package name: opencv-python
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/opencv-python
Link to piwheels page: https://www.piwheels.org/project/opencv-python
Version: all
Python version: all
More information:

When you import `cv2` you get the following error:

```bash
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /home/pi/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8
```

The workaround is:

```bash
pi@raspberrypi:~ $ LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 
```

But this can be fixed by rebuilding all the opencv files (sorry @waveform80).

**Comment by MichK1** [comment]
On my Raspberry Pi 3 model B importing opencv installed via package _opencv-contrib-python versions_ **3.6.27** or earlier works fine. However, it fails with above mentioned error for package version **3.7.28**, but it works with provided workaround.

**Comment by rob-smallshire** [comment]
This issue has consumed a lot of my time, and the list of successful build on the PiWheels website got me thinking about what constitutes a successful build. Are there any smoke tests which check that it's possible to import the built package? This failing OpenCV build would fail even the most rudimentary test on a Raspberry Pi 3. I'd be happy to help get such tests in place, but it's not clear to me how these wheels are actually constructed, and where the build scripts are.

**Comment by waveform80** [comment]
@rob-smallshire : https://github.com/waveform80/cvcluster - new-setup.py is probably the most important bit for the purposes of actually producing the wheels - all the rest is just machinery for the cluster.

**Comment by rob-smallshire** [comment]
@waveform80 Any chance you could put a license on this repo? It strikes me as important and useful. There's use-case for building Raspberry Pi compatible wheels which include the proprietary bits which the PiWheels can't host as binaries, but which individuals could build into a wheel themselves.

**Comment by jjppython** [comment]
Have the same issue. I am trying to install OpenCV on Raspberry Pi 4. Its a clean install and still getting the following error. I am using the python IDLE.

Traceback (most recent call last):
  File "/home/pi/Desktop/Age_Classification_Try/Try2/age_try6.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

**Comment by bennuttall** [comment]
Did the workaround work for you?

**Comment by barrysaik** [comment]
Yes the workaround works.

**Comment by rasha4321** [comment]
> On my Raspberry Pi 3 model B importing opencv installed via package _opencv-contrib-python versions_ **3.6.27** or earlier works fine. However, it fails with above mentioned error for package version **3.7.28**, but it works with provided workaround.

hi can you help me in how to install a previous version as i am failing to do so and getting the error with latest version

**Comment by rasha4321** [comment]
> Package name: opencv-python
> Issue type: Broken package
> Link to PyPI page: https://pypi.org/project/opencv-python
> Link to piwheels page: https://www.piwheels.org/project/opencv-python
> Version: all
> Python version: all
> More information:
> 
> When you import `cv2` you get the following error:
> 
> ```shell
> pi@raspberrypi:~ $ python3
> Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
> [GCC 8.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cv2
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/cv2/__init__.py", line 3, in <module>
>     from .cv2 import *
> ImportError: /home/pi/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8
> ```
> 
> The workaround is:
> 
> ```shell
> pi@raspberrypi:~ $ LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3
> Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
> [GCC 8.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cv2
> >>> 
> ```
> 
> But this can be fixed by rebuilding all the opencv files (sorry @waveform80).

hi can you help me to know how to use the workaround in thony IDE or as of now it only works if i use it in terminal

**Comment by bennuttall** [comment]
Open Thonny from the command line the same way:

```bash
pi@raspberrypi:~ $ LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 thonny &
```

**Comment by JolleJolles** [comment]
I am also trying to get opencv installed on the standard python3 (3.7) on my raspberry pi. The provided solution above works, but would be interested to hear about another command that only needs to be run once.

**Comment by jfabdo** [comment]
I tried to set this in my python file so that I wouldn't have to run a separate script like so:

    import OS
    
    os.environ['LD_PRELOAD'] = '/usr/lib/arm-linux-gnueabihf/libatomic.so.1'

and that runs before I import cv2.

However, I still get the same error. It works if I export it from the terminal. Any ideas how to work this into a python program?

**Comment by rob-smallshire** [comment]
@jfabdo It's not sufficient to have the variable set in Python. It needs to be seen by the Linux dynamic linker *before* Python is loaded. I have speculatively tried a few things like loading `libatomic` from within Python using `ctypes`, but I didn't really expect this to work, and indeed it didn't.

**Comment by eoinoc** [comment]
> I am also trying to get opencv installed on the standard python3 (3.7) on my raspberry pi. The provided solution above works, but would be interested to hear about another command that only needs to be run once.
> 
> **Update:** I found installing a version of opencv < 4.0 works: `pip install opencv-contrib-python==3.4.3.18`

Installing the previous version worked for me to `import cv2`:

```
pip install opencv-contrib-python==4.1.0.25
```

Perhaps there is a bug in the latest version `4.1.1.26`.

**Comment by jfabdo** [comment]
My pi wasn't able to find 4.1.1.25, only 4.1.1.26 and 4.1.0 versions. I tried updating pip and have run into this issue: https://github.com/pypa/pip/issues/7209

**Comment by jfabdo** [comment]
> But this can be fixed by rebuilding all the opencv files

This didn't seem to fix it for me. Is there another step to this?

**Comment by FlantasticDan** [comment]
> Installing the previous version worked for me to `import cv2`:
> 
> ```
> pip install opencv-contrib-python==4.1.0.25
> ```
> 
> Perhaps there is a bug in the latest version `4.1.1.26`.

This also worked for me.  Thanks for the idea!

**Comment by dcshort** [comment]
Seems you can add "export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1" to the file .bashrc in home directory, follow this by "source .bashrc". After making this mod, launch Python3 and then import cv2 and you will get no error.  I got this from a very helpful page http://www.yoyojacky.com/, many, many thanks to this person.

**Comment by ptbw** [comment]
> > I am also trying to get opencv installed on the standard python3 (3.7) on my raspberry pi. The provided solution above works, but would be interested to hear about another command that only needs to be run once.
> > **Update:** I found installing a version of opencv < 4.0 works: `pip install opencv-contrib-python==3.4.3.18`
> 
> Installing the previous version worked for me to `import cv2`:
> 
> ```
> pip install opencv-contrib-python==4.1.0.25
> ```
> 
> Perhaps there is a bug in the latest version `4.1.1.26`.

Worked for me

**Comment by rob-smallshire** [comment]
> Seems you can add "export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1" to the file .bashrc in home directory, follow this by "source .bashrc". After making this mod, launch Python3 and then import cv2 and you will get no error. I got this from a very helpful page http://www.yoyojacky.com/, many, many thanks to this person.

@dcshortI  think that will load OpenCV into every single process started in that bash session!

**Comment by jbeale1** [comment]
Thanks, this solved the problem for me on my Pi4.  I guess the LD_PRELOAD workaround will load that shared library, which on my system is a link to /usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 before running *any* executable, not just Python/OpenCV but it's only a 30k file so I guess no big deal.

**Comment by ulriksenstian** [comment]
The LD_PRELOAD workaround is working for now, but I don't see it as a permanent solution...

**Comment by hexagene** [comment]
> Seems you can add "export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1" to the file .bashrc in home directory, follow this by "source .bashrc". After making this mod, launch Python3 and then import cv2 and you will get no error. I got this from a very helpful page http://www.yoyojacky.com/, many, many thanks to this person.

Thank you!! This worked as a permanent solution

**Comment by trickeydan** [comment]
> > Seems you can add "export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1" to the file .bashrc in home directory, follow this by "source .bashrc". After making this mod, launch Python3 and then import cv2 and you will get no error. I got this from a very helpful page [http://www.yoyojacky.com](http://www.yoyojacky.com/), many, many thanks to this person.
> 
> Thank you!! This worked as a permanent solution

Be careful. This solution is really dangerous and loads the `libatomic` library into *every* binary that you run...

**Comment by mcdsimon** [comment]
there is the one issue for me. the python script can run in terminal screen. but it is failed in thonny IDE. the error description as above. It is very strange. why are different return in the two environments?

**Comment by bennuttall** [comment]
Launch Thonny from the command line:

```bash
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 thonny &
```

**Comment by davidmathew** [comment]
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/issues/67#issuecomment-557679983
Zach-OP commented on Nov 23, 2019
Hey, this is because the latest version of openCV doesn't work with RPi. Instead of pip3 install opencv-python try pip3 install opencv-python==3.4.6.27
You will need to uninstall the latest version first. pip3 uninstall opencv-python

**Comment by stijojoseph** [comment]
> pip3 install opencv-python==3.4.6.27

still it was showing the same error

**Comment by aspate** [comment]
If anyone could help, I would be appreciated.  I have tried what I feel is all the solutions presented in this thread to no avail.  I have tried opencv version 3.4.6.27 and 3.4.3.18 (uninstalled previous versions), LD Preload... --usbcam, the import OS into my python script.  

My program runs in python 3.7 IDLE, but will not run from the terminal line, and I need to launch it from the line to add it as a start up program.

**Comment by bennuttall** [comment]
Open IDLE with the preload:

```bash
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 idle3 &
```

Where are you trying to add it as a startup program? Cron or something?

**Comment by aspate** [comment]
Yes, I am running a crontab 
`@reboot python 3 /path/to/script`
Where should I add the preload at?  The cron script or within the python script itself? or elsewhere?  Sorry, I am relatively new to Linux and the Pi, and have been trying to troubleshoot this for days...

**Comment by bennuttall** [comment]
```
@reboot LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3 /path/to/script
```

**Comment by yoyojacky** [comment]
> Seems you can add "export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1" to the file .bashrc in home directory, follow this by "source .bashrc". After making this mod, launch Python3 and then import cv2 and you will get no error. I got this from a very helpful page http://www.yoyojacky.com/, many, many thanks to this person.

you are welcome~

**Comment by stygarfield** [comment]
> Seems you can add "export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1" to the file .bashrc in home directory, follow this by "source .bashrc". After making this mod, launch Python3 and then import cv2 and you will get no error. I got this from a very helpful page http://www.yoyojacky.com/, many, many thanks to this person.

This worked for me as well, Raspberry Pi 4

**Comment by Vishnuvichuz** [comment]
> > I am also trying to get opencv installed on the standard python3 (3.7) on my raspberry pi. The provided solution above works, but would be interested to hear about another command that only needs to be run once.
> > **Update:** I found installing a version of opencv < 4.0 works: `pip install opencv-contrib-python==3.4.3.18`
> 
> Installing the previous version worked for me to `import cv2`:
> 
> ```
> pip install opencv-contrib-python==4.1.0.25
> ```
> 
> Perhaps there is a bug in the latest version `4.1.1.26`.

This Worked Fine. Fixed the Error. No more Import Error now. Thanks a lot :)

**Comment by jdang-dev** [comment]
Can I include the "PRELOAD" in my ~/.bashrc file? Or is there a way to do this automatically?

**Comment by piningforfjords** [comment]
This is a pain.

**Comment by bennuttall** [comment]
`rm -rf /etc/pip.conf` will make alleviate the pain

**Comment by bennuttall** [comment]
This should be fixed with the new builds
