### ISSUE TITLE
Missing package: asphodel

### ISSUE THREAD

**Issue by ecejeff** [piwheels/packages#61]
Package name: Asphodel
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/asphodel/
Link to piwheels page: https://www.piwheels.org/project/asphodel/
Version: all
Python version: all
More information:

I see on the project page that it failed builds for cp34m, cp35m but I don't know any more than this.

**Comment by bennuttall** [comment]
Thanks!

cp34 build says:

```
SyntaxError: can use starred expression only as assignment target
```

cp35 build says:

```
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ckpbjkgv/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja" failed with error code 1 in None
```

cp37 is likely pending - the builders were offline for a while so there's a backlog.

**Comment by ecejeff** [comment]
I understand what happened with cp34 (before PEP 0448), which I can address in a future release of the library. At least so there's no syntax errors in setup.py

I don't understand why cp35 build failed. It looks like it failed while pip was trying to install the build dependencies (setuptools wheel scikit-build cmake ninja). Is it possible to get more details?

I am curious whether the cp37 will succeed, so I will definitely wait for that to complete before I make any changes to the library.

**Comment by bennuttall** [comment]
The cp37 build kept timing out.

We have been experiencing issues with that packages that define build dependencies. This means that the builder tries to build and install all the dependencies (building from source not from piwheels). It's something we need to look into.

**Comment by ecejeff** [comment]
As far as cp37 timing out, I think ninja is spinning up too many compiler processes and running out of memory. Memory swapping slows the whole build down to the point where it can't finish before timing out.

On a B3+: `time python3 setup.py bdist_wheel` still running after 30 minutes with no progress

On a B3+: `time python3 setup.py bdist_wheel -- -- -j2` gives:
real    13m29.857s
user    25m25.538s
sys     0m13.582s

On a B3+: `time python3 setup.py bdist_wheel -- -- -j3` gives:
real    10m6.108s
user    26m49.148s
sys     0m15.033s

`-j4` and `-j5` don't finish in a reasonable amount of time

Is it possible to pass extra parameters to setup.py when building a piwheel? If not, I can change the defaults in setup.py, but ideally this change would only be for a pi, as I don't want it to slow down our CI builds. Do you know an easy way to detect whether setup.py is being run on a pi?

**Comment by bennuttall** [comment]
We don't run `python3 setup.py bdist_wheel` - we run `pip3 wheel <package>` - do the `-j2`/`-j3` flags work with the pip command?

**Comment by ecejeff** [comment]
I am running `time pip3 wheel asphodel-1.1.5/ --build-option="--" --build-option="--" --build-option="-j2"` and while that's a bit unwieldy it does seem to be working (top only shows 2 compiler processes).

**Comment by bennuttall** [comment]
@waveform80 what do you think?

**Comment by ecejeff** [comment]
Nope, that doesn't seem to work. Fails after building asphodel with a numpy build error.

`invalid command name '--'`

**Comment by bennuttall** [comment]
Maybe it can be done another way. env var?

**Comment by ecejeff** [comment]
I couldn't figure out a way to control ninja through the environment (and CMake was too involved), so I just changed the defaults to 2 build jobs on Linux and uploaded a new version as 1.1.6

**Comment by bennuttall** [comment]
Ok I've un-marked the skip, and the new version's in the queue now :+1: 

It'll try cp34 then cp35 then cp37 - you'll see progress on the project page

**Comment by bennuttall** [comment]
cp34 failed, cp35 failed, cp37 building now, and has been running for longer than the others took to fail...

**Comment by bennuttall** [comment]
Success! https://www.piwheels.org/project/asphodel/

Can you test the wheels work ok?

How come the ABI tag is `none`?

**Comment by ecejeff** [comment]
Looks like the wheel works. It wouldn't run on my very old image because of glibc 2.28 dependency, but updating to a recent version of raspbian solved that.

ABI tag is none because it uses scikit-build to build the C library, and the python code uses ctypes to bind to the C library, so a specific python ABI version isn't needed. The wheel built by cp37 should work with other cpython versions.

**Comment by bennuttall** [comment]
Great! Thanks for sorting it out :+1:

**Comment by waveform80** [comment]
> As far as cp37 timing out, I think ninja is spinning up too many compiler processes and running out of memory. Memory swapping slows the whole build down to the point where it can't finish before timing out.

Sadly so. I've had a quick browse through ninja's code to see how it determines its default parallelism and unfortunately it's the usual tale of "count the cores and ignore the memory" (so in the piwheels case it probably defaults to 6 (the default adds 2 to the core count) and the RAM consumed rapidly kills the build-node). It is sensible enough to limit its count in the case of configured CPU affinity, but I don't really want to limit our builders in that way as it penalizes those projects that can use the extra cores.

My personal rough rule of thumb for calculating job parallelism on C++ compiles is: min(num_cores, ram / 1Gb). In other words, assume each job is going to eat a gig of RAM (overkill, but I've seen some compiles that do this, usually those involving insane template usage), and limit the parallelism accordingly. In other words on a Pi3/3+ (which is what our builders currently run on): don't use parallelism with C++ builds :). Unfortunately we've no (sensible) way of enforcing this at the moment.

> On a B3+: `time python3 setup.py bdist_wheel` still running after 30 minutes with no progress
> 
> On a B3+: `time python3 setup.py bdist_wheel -- -- -j2` gives:
> real 13m29.857s
> user 25m25.538s
> sys 0m13.582s
> 
> On a B3+: `time python3 setup.py bdist_wheel -- -- -j3` gives:
> real 10m6.108s
> user 26m49.148s
> sys 0m15.033s
> 
> `-j4` and `-j5` don't finish in a reasonable amount of time
> 
> Is it possible to pass extra parameters to setup.py when building a piwheel? If not, I can change the defaults in setup.py, but ideally this change would only be for a pi, as I don't want it to slow down our CI builds. Do you know an easy way to detect whether setup.py is being run on a pi?

If `/proc/device-tree/model` exists and starts with "Raspberry Pi" you can be pretty sure you're on a Pi. That should be true on all our builders.

That said, I wonder if we should stick something in the environment to make it blindingly obvious to scripts that they're running on piwheels?

**Comment by waveform80** [comment]
> Looks like the wheel works. It wouldn't run on my very old image because of glibc 2.28 dependency, but updating to a recent version of raspbian solved that.
> 
> ABI tag is none because it uses scikit-build to build the C library, and the python code uses ctypes to bind to the C library, so a specific python ABI version isn't needed. The wheel built by cp37 should work with other cpython versions.

Wow, that sounds ... not sensible. Still, it also looks like you've discovered why :)
