### ISSUE TITLE
Missing package: lacbd

### ISSUE THREAD

**Issue by iomintz** [piwheels/packages#64]
Package name: lacbd
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/lacbd
Link to piwheels page: https://www.piwheels.org/project/lacbd/
Version: e.g. all
Python version: all supported (3.6+)
More information: This package requires rustc installed, which may be the source of the issue.

**Comment by bennuttall** [comment]
Thanks for the ticket - looks like you're right - the build log seems to boil down to:

```
ModuleNotFoundError: No module named 'setuptools_rust'
```

I will test this out on a Pi when I get chance, and we'll add the missing dependency if it doesn't cause any issues.

**Comment by iomintz** [comment]
`setuptools_rust` is listed in the `pyproject.toml`. That should cause `pip wheel .` to install setuptools_rust first, automatically. Unless that's not how it works on the build server?

**Comment by iomintz** [comment]
Also it's not just setuptools_rust that needs to be installed. It's also the full rust compiler.

**Comment by bennuttall** [comment]
If you can find the time, run this on a Pi 3: https://github.com/piwheels/piwheels/blob/master/deploy_slave.sh

Then see what else needs installing to make `pip3 wheel lacbd` work :)

PR welcome - or just let us know here.

Need to be sure it works on a Pi 3, builds within 3 hours and doesn't require anything else (USB swap, changing the number of cores used or anything like that).

If it's a pain to build, we could look at importing a built wheel instead. Are you the maintainer?

**Comment by iomintz** [comment]
I am the maintainer. I do have a Pi 3 laying around and will try this.

**Comment by bennuttall** [comment]
@iomintz any update?

**Comment by iomintz** [comment]
no sorry

**Comment by bennuttall** [comment]
Update: I installed cargo, setuptools_rust and conan - and now lacbd is building successfully on cp37m since version 0.1.4.

:partying_face:
