### ISSUE TITLE
Broken package: NPi.GPIO

### ISSUE THREAD

**Issue by Zoundream** [piwheels/packages#67]
Package name: NPi.GPIO
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/NPi.GPIO/
Link to piwheels page: https://www.piwheels.org/project/NPi.GPIO/
Version: all
Python version: 3.5
I am the maintainer: No

**Comment by bennuttall** [comment]
Doesn't look like the package supports Python 3.5. There are wheels for 3.6 and 3.7 on PyPI. And we only support Raspberry Pi anyway.
