### ISSUE TITLE
h5py cp37-armv7l mismatch sha256

### ISSUE THREAD

**Issue by cristhoper** [piwheels/packages#68]
Package name: h5py
Link to PyPI page: https://pypi.org/project/h5py/
Link to piwheels page:  https://www.piwheels.org/project/h5py/ 
Version: 2.10.0
Python version: 3.7
I am the maintainer: No
More information:

```bash
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    h5py from https://www.piwheels.org/simple/h5py/h5py-2.10.0-cp37-cp37m-linux_armv7l.whl#sha256=3734f3af6d58f38c84e1b965c02da9f0466356d832bb32ecfffcbe5aad886453 (from keras-applications>=1.0.8->tensorflow):
        Expected sha256 3734f3af6d58f38c84e1b965c02da9f0466356d832bb32ecfffcbe5aad886453
             Got        8a22a9e3c8cc050b30d09b5f05325f54d4820c0e6ff70a65d9033de7c168b80c

```

**Comment by bennuttall** [comment]
I've just downloaded this file and checked the hash, it's ok for me:

```
ben@gunter:~/Downloads $ sha256sum h5py-2.10.0-cp37-cp37m-linux_armv7l.whl 
3734f3af6d58f38c84e1b965c02da9f0466356d832bb32ecfffcbe5aad886453  h5py-2.10.0-cp37-cp37m-linux_armv7l.whl
```

Can you try using `wget` and checking yourself?

```bash
pi@raspberrypi:~ $ wget https://www.piwheels.org/simple/h5py/h5py-2.10.0-cp37-cp37m-linux_armv7l.whl
pi@raspberrypi:~ $ sha256sum h5py*whl
3734f3af6d58f38c84e1b965c02da9f0466356d832bb32ecfffcbe5aad886453
```

If that comes back correct (`3734f3...`) then your pip download may have broken up. Unlike wget, pip is pretty useless when it comes to noticing a failed download. If it successfully downloads with wget, and the hash comes back wrong, then I don't know what went wrong, but I would suggest unzipping the `.whl` file to see if it's a valid wheel.

**Comment by cristhoper** [comment]
```
pi@raspberrypi:~ $ sha256sum h5py-2.10.0-cp37-cp37m-linux_armv7l.whl 
3734f3af6d58f38c84e1b965c02da9f0466356d832bb32ecfffcbe5aad886453  h5py-2.10.0-cp37-cp37m-linux_armv7l.whl
```
Yiep, i have the same hash :(
i will check `pip`.

Thanks!

**Comment by bennuttall** [comment]
This could happen on a poor connection. One way to ensure you get the right file and are able to install it is to download the file with wget, verify the hash and directly install the file using pip:

```bash
pi@raspberrypi:~ $ wget https://www.piwheels.org/simple/h5py/h5py-2.10.0-cp37-cp37m-linux_armv7l.whl
pi@raspberrypi:~ $ sha256sum h5py*whl
3734f3af6d58f38c84e1b965c02da9f0466356d832bb32ecfffcbe5aad886453
pi@raspberrypi:~ $ sudo pip3 install h5py*whl
```
