### ISSUE TITLE
protobuf C++ implementation

### ISSUE THREAD

**Issue by dmitriykovalev** [piwheels/packages#7]
Package name: `protobuf` 
Link to PyPI page: https://pypi.org/project/protobuf
Link to piwheels page: https://www.piwheels.org/project/protobuf/
Version: `all`

All protobuf releases on piwheels are pure python (platform tag is `any`). Native implementation is much faster and would be nice to have.  Manual build using
 ```bash
python3 setup.py bdist_wheel --cpp_implementation
``` 
works fine on Raspberry Pi 3 and produces 
```
protobuf-3.6.1-cp35-cp35m-linux_armv7l.whl
``` 
file.

For example, gRPC library already has armv6l and amrv7l wheels —https://www.piwheels.org/simple/grpcio/

**Comment by bennuttall** [comment]
If the C++ implementation isn't what the maintainers provide on PyPI, I'm not sure we should on piwheels. If they/someone registered protobuf-cpp on PyPI and pushed an sdist targeting the C++ implementation, we could pick that up. I suggest you raise it with the maintainers, or pursue it yourself. What do you think?
