### ISSUE TITLE
Missing package: numpy-mkl

### ISSUE THREAD

**Issue by Niatios** [piwheels/packages#70]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
please do us a favour and edit your issue to fill in the template

**Comment by bennuttall** [comment]
There are no files on PyPi: https://pypi.org/project/numpy-mkl/#history
