### ISSUE TITLE
Missing package: Pillow 6.2.1

### ISSUE THREAD

**Issue by radarhere** [piwheels/packages#71]
Package name: Pillow
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/Pillow
Link to piwheels page: https://www.piwheels.org/project/Pillow
Version: 6.2.1
Python version: 3.5, 3.7
I am the maintainer: Yes
More information:

Hi. I'm one of the maintainers of Pillow. A user has reported that Raspberry Pi binary wheels are missing for Pillow 6.2.1, and true enough, https://www.piwheels.org/project/Pillow/ shows that Python 3.5 and 3.7 have failed builds.

However, 6.2.0 is successful for those two Python versions, and [the only difference between 6.2.0 and 6.2.1 is the addition of Python 3.8](https://github.com/python-pillow/Pillow/compare/6.2.1..6.2.0). So is this some sort of timeout during your build process that failed once and would succeed if you ran it again? Is it something more complicated? Is there anything that I can do to help? Thanks very much.

**Comment by bennuttall** [comment]
*This is a missing package, not a broken package.*

Ok, just looked into it. The failure was a "no distribution found". Looks like the build was attempted very soon after the sdist upload, and the files hadn't become available yet. Maybe something we could do about that to prevent this in future.

I've kicked off new builds which should get picked up soon. cp35m already going.

**Comment by bennuttall** [comment]
They both built successfully - thanks for the report :+1:

**Comment by radarhere** [comment]
Thanks very much
