### ISSUE TITLE
Missing package: scikit-learn v- 0.22.0 on python 3.5

### ISSUE THREAD

**Issue by sakethramanujam** [piwheels/packages#72]
Package name: scikit-learn
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/scikit-learn
Link to piwheels page: https://www.piwheels.org/project/scikit-learn
Version: 0.22.0
Python version: 3.5
I am the maintainer: No

**Comment by bennuttall** [comment]
Looks like the version of cython is to old to build this version:

```
 ValueError: Please install Cython with a version >= 0.28.5 in order to build a scikit-learn from source. The current version of Cython is 0.25.2 installed in ['/usr/lib/python3/dist-packages/Cython'].
```

We have 0.25.2 on the stretch builders. Not sure if we should upgrade it as it might cause other issues.

Any reason you're using stretch not buster? If you're stuck on stretch, you can use up to 0.21.3.

**Comment by sakethramanujam** [comment]
> Any reason you're using stretch not buster? If you're stuck on stretch, you can use up to 0.21.3.
We've been building a system using stretch, other members on the team aren't that techies, nor do they try to understand and I can't get an authorization to upgrade to another O.S. :-( 
I've found a way out of the situation. thanks :-D

**Comment by bennuttall** [comment]
Sorry for the delay but I've just worked through fixing the 0.22.x builds on Stretch and managed to get a few of them to succeed, including 0.22 (the one the issue is about). 0.23 and beyond no longer support Python 3.5.

**Comment by sakethramanujam** [comment]
Thanks!
