### ISSUE TITLE
Missing package: scipy

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#76]
Package name: scipy
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/scipy
Link to piwheels page: https://www.piwheels.org/project/scipy
Version: 1.4.x
Python version: all

**Comment by rob26r** [comment]
Newbie here - so not sure how to proceed.
What is the timeline for this be reviewed?  
Any suggestions on other ways to get scipy installed on my Raspberry PI 4 if it will take longer.  Thanks again.

**Comment by bennuttall** [comment]
Can't give an indication on timeline, but I'll take a look soon. It may be very quick.

The easiest way to get it working is to install an old version:

```bash
pip install scipy -i https://www.piwheels.org/simple
```

(this should only use piwheels, not PyPI too)

**Comment by rob26r** [comment]
I tried to install the package and got the error message below.  Hmmm - any suggestions or than quitting :)

```
pi@raspberrypi:~ $ pip install scipy -i https://www.piwheels.org/simple
Looking in indexes: https://www.piwheels.org/simple, https://www.piwheels.org/simple
Collecting scipy
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement scipy (from versions: )
No matching distribution found for scipy
```

**Comment by rob26r** [comment]
Will this get reviewed?

**Comment by bennuttall** [comment]
I spent some time last week trying to build this but hit more errors. What have you tried so far to get it to build?

**Comment by bennuttall** [comment]
I've uploaded one build by @topshed - will leave this open until I've made sure piwheels builders have the right dependencies.

**Comment by bennuttall** [comment]
All built now
