### ISSUE TITLE
Missing package: TA-Lib

### ISSUE THREAD

**Issue by NansSimpson** [piwheels/packages#80]
Package name: TA-Lib
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/TA-Lib
Link to piwheels page: https://www.piwheels.org/project/TA-Lib
Version: all
Python version: all
I am the maintainer: No
More information: Marked as deleted

**Comment by bennuttall** [comment]
Please fill out the issue template.

**Comment by bennuttall** [comment]
That's weird. piwheels thinks it's been deleted. Are you the maintainer? Did you delete releases and republish files with the same version? ping @waveform80

**Comment by NansSimpson** [comment]
Hi, no I just wanted to install it on my rpi and got error messages, then I
found out it was deleted.

Le mar. 28 janv. 2020 à 11:22, Ben Nuttall <notifications@github.com> a
écrit :

**Comment by bennuttall** [comment]
Ok can you edit your original comment so all the fields are completed? e.g. change "example" to the name of the package. It makes it easier for us to deal with it.

**Comment by bennuttall** [comment]
I marked as not deleted, it's attempted to build but failed. The build log from the latest version on buster is here: http://paste.debian.net/1133738/

**Comment by bennuttall** [comment]
Failed here:

```
talib/_ta_lib.c:526:28: fatal error: ta-lib/ta_defs.h: No such file or directory                                                                                                                                                                                                                                                                                                                 
    #include "ta-lib/ta_defs.h"   
```

**Comment by bennuttall** [comment]
The solution is here:

```bash
$ tar -xzf ta-lib-0.4.0-src.tar.gz
$ cd ta-lib/
$ ./configure --prefix=/usr
$ make
$ sudo make install
```

We can't do this on piwheels builders but we can build this offline and import the wheels.

TODO
