### ISSUE TITLE
Missing package: python-snappy

### ISSUE THREAD

**Issue by shivamMg** [piwheels/packages#81]
Package name: python-snappy
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/python-snappy
Link to piwheels page: https://www.piwheels.org/project/python-snappy
Version: all
Python version: all
I am the maintainer: No
More information: missing pre-built wheel https://www.piwheels.org/simple/python-snappy/

```bash
$ pip install python-snappy --index-url=https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement python-snappy (from versions: none)
ERROR: No matching distribution found for python-snappy
```

**Comment by bennuttall** [comment]
Thanks for filling out the template - really helpful. I'll take a look.

**Comment by bennuttall** [comment]
I've installled `libsnappy-dev` on the builders so that should do the trick. I'll check back in the morning.

**Comment by bennuttall** [comment]
Done - most of them built successfully, particularly the latest version. It even picked up the dependency required:

```
sudo apt install libsnappy1v5
sudo pip3 install python-snappy
```

**Comment by shivamMg** [comment]
Working now. Thanks.

**Comment by shivamMg** [comment]
Hmm I tried using the library and it seems to throw an error

```
>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.5/site-packages/snappy/snappy.py", line 48, in <module>
    from ._snappy import UncompressError, compress, decompress, \
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by bennuttall** [comment]
We don't really support Ubuntu. It should work in Raspbian.

Try:

```
sudo apt install libsnappy-dev
sudo pip install python-snappy --no-binary :all:
```
