### ISSUE TITLE
Broken package: PyQt5

### ISSUE THREAD

**Issue by altendky** [piwheels/packages#82]
Package name: PyQt5
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/PyQt5
Link to piwheels page: https://www.piwheels.org/project/PyQt5
Version: 5.14+ (earlier are not expected to work)
Python version: all
I am the maintainer: No
More information:

The build fails.  I'm not sure where to even look to see what the failure is.  I won't promise to help, but it could happen and I do for other reasons (pyqt5-tools) need to learn about the new PyQt5 5.14+ build process anyways.

**Comment by bennuttall** [comment]
There are no PyQt5 wheels on piwheels, so it's a "missing package" not a "broken package".

What's happening is you're running `pip install PyQt5` and getting the source from PyPI, which is failing to build.

Until very recently, there was no PyQt5 sdist on PyPI, only wheels., so we previously had nothing to build.

If we can figure out how to build it from source, we can provide it on piwheels. The missing package issue already exists at #3 so I'm going to close this and move the conversation there.
