### ISSUE TITLE
Missing package: pandas

### ISSUE THREAD

**Issue by topshed** [piwheels/packages#84]
Package name: pandas
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pandas/
Link to piwheels page: https://www.piwheels.org/project/pandas
Version: 1.0.x
Python version: 3.7
I am the maintainer: No
More information:

Showing as failed build. If I try to manually build on Buster it fails with libf77blas.so.3 error.

Installed libatlas-base-dev and it built successfully

**Comment by bennuttall** [comment]
Jessie and Stretch failed because pandas only supports Python >= 3.6. It's currently in the queue for Buster.

Unfortunately there's a large backlog for Buster builds due to reliability issues of Buster on the cloud Pis. I'm working on it...

**Comment by bennuttall** [comment]
I've uploaded one built by @topshed - will leave this open until I've made sure piwheels builders have the right dependencies.

**Comment by bennuttall** [comment]
Built fine now thanks @topshed
