### ISSUE TITLE
CherryPy 17.4.1 wants tempora>=1.8, when it was tempora 1.14 previously. Breaks on Python 3.5.

### ISSUE THREAD

**Issue by Jordan-Gillard** [piwheels/packages#87]
Package name: tempora
Link to PyPI page: https://pypi.org/project/tempora/1.14.1/
Link to piwheels page: https://www.piwheels.org/project/tempora/
Version: 1.14.1
Python version: 3.5
I am the maintainer: No
More information:
For some reason installs of CherryPy 17.4.1 throw this error:
```
Collecting tempora>=1.8 (from portend>=2.1.1->CherryPy==17.4.1->-r /opt/gastrofix-bridge/requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/tempora/tempora-2.1.0-py2.py3-none-any.whl
tempora requires Python '>=3.6' but the running Python is 3.5.3
```

Previously, CherryPy 17.4.1 would install tempora version 1.14.1, which is Python 3.5 compliant. Locally when I install CherryPy 17.4.1 from pypi, I get tempora version 1.14.1, but installs from piwheels get tempora>=1.8.

Any idea what this is about? Or how we can fix it?

**Comment by bennuttall** [comment]
tempora 2.x requires Python >= 3.6, as declared in Requires-Python on PyPI. piwheels doesn't support Requires-Python yet.

I've deleted the tempora 2.x wheels and marked the package as "skipped" so new releases won't get built. Once we add support for Requires-Python, I'll be able to undo this. See https://github.com/piwheels/piwheels/issues/208
