### ISSUE TITLE
Tensorflow hash mismatch

### ISSUE THREAD

**Issue by bertfw** [piwheels/packages#88]
Hello, installing Tensorflow today I run into this:

pi@raspberry:~ $ pip3 install tensorflow
Collecting tensorflow
  Downloading https://www.piwheels.org/simple/tensorflow/tensorflow-1.14.0-cp35-none-linux_armv7l.whl (100.7MB)
    66% |█████████████████████▎          | 67.1MB 54kB/s eta 0:10:18
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow from https://www.piwheels.org/simple/tensorflow/tensorflow-1.14.0-cp35-none-linux_armv7l.whl#sha256=cba22b6d9a3e7a92c07e142bd5256c9773fd20c18090cb1d222357d3b3028655:
        Expected sha256 cba22b6d9a3e7a92c07e142bd5256c9773fd20c18090cb1d222357d3b3028655
             Got        6d709494586332ecbcc043272ddef6e8ac904e24486b24774ae9f4c31005e1a0

**Comment by bennuttall** [comment]
The hash of the file is correct, so you must have got a corrupted file.

Try:

```
wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.14.0-cp35-none-linux_armv7l.whl
sha256sum tensorflow*whl
```

That should show the correct hash:

```
cba22b6d9a3e7a92c07e142bd5256c9773fd20c18090cb1d222357d3b3028655
``

If so, you can install this file:

```
pip3 install tensorflow*whl
```

**Comment by bertfw** [comment]
Thank you very much, that worked!

**Comment by bennuttall** [comment]
👍
