### ISSUE TITLE
Missing package: SharedArray

### ISSUE THREAD

**Issue by kpine** [piwheels/packages#89]
Package name: SharedArray
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/SharedArray/
Link to piwheels page: https://www.piwheels.org/project/SharedArray/
Version: 3.2.0
Python version: 3.7
I am the maintainer: No
More information:

v3.2.0 is missing a build for Python 3.7, it's listed as a failed build.

**Comment by bennuttall** [comment]
Here's the build log for the failed build on cp37m: http://paste.debian.net/1133567

It's complaining about pandoc, but that should be installed on the builders. I'll take a look.

**Comment by bennuttall** [comment]
Rebuilt and it's passed this time
