### ISSUE TITLE
Missing package: pcapy

### ISSUE THREAD

**Issue by DrSchottky** [piwheels/packages#91]
Package name: pcapy
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pcapy/
Link to piwheels page: https://www.piwheels.org/project/pcapy/
Version: all
Python version: all
I am the maintainer: No
More information:

There are no wheels for pcapy. A build for armv6 (compatible with all Raspberry Pi versions) could be useful

**Comment by bennuttall** [comment]
Thanks for filling out the issue template. That's really helpful. I'll take a look.

**Comment by bennuttall** [comment]
Looks like https://packages.debian.org/buster/libpcap0.8-dev is missing - I'll install it and see if that fixes things

**Comment by bennuttall** [comment]
Yes, that worked. I'll kick off the builders now and it should appear shortly.

**Comment by DrSchottky** [comment]
Working fine, thanks
