### ISSUE TITLE
azure-cognitiveservices-speech

### ISSUE THREAD

**Issue by Hareeshsuji** [piwheels/packages#94]
Package name: azure-cognitiveservices-speech
Link to PyPI page: https://pypi.org/project/azure-cognitiveservices-speech
Link to piwheels page: https://www.piwheels.org/project/azure-cognitiveservices-speech
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:
If i run this 

```
python3 -m pip install azure-cognitiveservices-speech
```

I get this error

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting azure-cognitiveservices-speech
  Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: )
No matching distribution found for azure-cognitiveservices-speech
```

**Comment by bennuttall** [comment]
There's no source distribution for this package, so there's nothing piwheels can build. They only provide wheels for other platforms. You'll have to request source distribution from the maintainers, or ask them to provide arm wheels directly to us.

**Comment by Hareeshsuji** [comment]
> There's no source distribution for this package, so there's nothing piwheels can build. They only provide wheels for other platforms. You'll have to request source distribution from the maintainers, or ask them to provide arm wheels directly to us.

Thank you
