### ISSUE TITLE
Missing packages: opencv-*

### ISSUE THREAD

**Issue by donkawechico** [piwheels/packages#95]
Package name: opencv-python-headless
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/opencv-python-headless/4.1.2.30/
Link to piwheels page: https://www.piwheels.org/project/opencv-python-headless/
Version: 4.1.2.30 and 4.1.2.32
Python version: 3.7.3
I am the maintainer: No

FWIW, this is on a fully-updated RPi 4 w/ Buster.

```
pi@raspberrypi ~ $ pip3 --version
pip 20.0.2 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
pi@raspberrypi ~ $
pi@raspberrypi ~ $
pi@raspberrypi ~ $
pi@raspberrypi ~ $ pip3 install opencv-python-headless==4.1.2.30
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.1.2.30 (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.6.27, 3.4.7.28, 4.0.1.24, 4.1.0.25, 4.1.1.26)
ERROR: No matching distribution found for opencv-python-headless==4.1.2.30
pi@raspberrypi ~ $ 
```

This is causing the [opencv integration](https://www.home-assistant.io/integrations/opencv/) on [Home Assistant](https://github.com/home-assistant/core) (which now has a [requirement of 4.1.2.30](https://github.com/home-assistant/core/pull/29061)) to fail on raspberry pi.

I've [submitted an issue in Home Assistant](https://github.com/home-assistant/core/issues/32733) to see if it can/should be addressed there.

**Comment by bennuttall** [comment]
@waveform80 builds these himself - looks like there are a couple of new versions released since he last built them - can't say when but we'll aim to do this soon.

**Comment by bennuttall** [comment]
The latest version is now available
