### ISSUE TITLE
Missing package: retworkx

### ISSUE THREAD

**Issue by mtreinish** [piwheels/packages#99]
Package name: retworkx
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/retworkx
Link to piwheels page: https://www.piwheels.org/project/retworkx
Version: 0.3.1 - 0.3.3
Python version: e.g. all
I am the maintainer: Yes
More information:

The retworkx package builds are missing the 3 latest versions. It looks like the 3 most recent builds have failed according the piwheels project page. If there is a build system problem I'll gladly help debug and fix it. There were minimal changes made to the package since the last successful build. Also, at least on my local spare Pi4 1GB I was able to build the latest version (0.3.3) package from sdist.

**Comment by bennuttall** [comment]
Build output from Buster: http://paste.debian.net/1137594/

The killer is `error: Can not find Rust compiler`

We don't have rust installed on the builders. Is there a Rust compiler in the Buster apt repo?

**Comment by mtreinish** [comment]
There is: https://packages.debian.org/buster/rustc but it's a stable release. The issue with python packages built with rust is that the primary library people use for the integration between languages, [PyO3](https://github.com/PyO3/pyo3), needs a nightly version of the compiler because they use a unstable rustlang feature (it's a high priority item for them, but is a lot of work to stop using that). Not having a nightly build of rust in the environment probably explains why other rust packages like: https://www.piwheels.org/project/orjson/ don't have recent releases either.

**Comment by bennuttall** [comment]
If we installed stock rustc from Debian and built wheels for retworkx, would those wheels be useful to most people?

**Comment by mtreinish** [comment]
We won't be able able to build wheels with the rustc from debian. If you try to build a package using PyO3 with rustc from the stable channel (which includes the debian package) it will error with something like:

```
  Caused by:
    process didn't exit successfully: `/tmp/pip-install-wovxb3vt/retworkx/target/release/build/pyo3-75688e79b69409f8/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Error: pyo3 requires a nightly or dev version of Rust.', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.8.5/build.rs:542:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
  cargo rustc --lib --manifest-path Cargo.toml --features pyo3/python3 pyo3/extension-module --release --verbose -- --crate-type cdylib
  error: cargo failed with code: 101
  
  ----------------------------------------
  ERROR: Failed building wheel for retworkx
Failed to build retworkx
ERROR: Could not build wheels for retworkx which use PEP 517 and cannot be installed directly
```

**Comment by mtreinish** [comment]
Fwiw, to fix this all we need to do is add something like:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh --default-toolchain nightly -y
```
to the build nodes. It will install the rust env at the version which works with PyO3.

**Comment by mtreinish** [comment]
@bennuttall an update here, retworkx 0.4.0 was just released https://pypi.org/project/retworkx/0.4.0/. This version now supports building with released rust >=1.39. There are debian packages for it in testing and unstable. Unfortunately the buster version of the package is too old though at 1.34.2:  https://packages.debian.org/buster/rustc Is there path for installing a package from testing or unstable in the build environment? If so we'll need to install rustc and cargo to fix this package.

**Comment by bennuttall** [comment]
No, sorry, that's not possible.

**Comment by mtreinish** [comment]
Well then this is still blocked until we can get a newer version of the rust compiler in the build environment (which will be a while because it won't be until bullseye).

My only other thought is to use an official build of rust (either via [rustup](https://rustup.rs/), [rust-init](https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init) or [standalone](https://static.rust-lang.org/dist/rust-1.45.0-arm-unknown-linux-gnueabi.tar.gz)) which would be simple to add as a step to https://github.com/piwheels/piwheels/blob/master/deploy_slave.sh which I'd gladly push a PR for that if it's an acceptable solution (which I'm assuming it's not).

**Comment by fungi** [comment]
Is there something blocking the rustc from sid/bullseye from being submitted to the buster-backports suite? Too many versioned (build-)depends not satisfyable on buster?

**Comment by bennuttall** [comment]
> My only other thought is to use an official build of rustc

I don't think so, because I assume that would require the user to have the same version of rust? Or does the user not need rust?

If you want to build a wheel and test it, see if it works, it's not out of the question that we import it. Just there's only two special cases we do that for currently (tensorflow and opencv). And if it requires anything other than an `apt install` to use then it's probably not worth it.

**Comment by bennuttall** [comment]
> Is there something blocking the rustc from sid/bullseye from being submitted to the buster-backports suite? Too many versioned (build-)depends not satisfyable on buster?

Debian is stable because it moves slowly, and if anything breaks in an upgrade, they don't proceed until everything's fixed.

**Comment by fungi** [comment]
> > Is there something blocking the rustc from sid/bullseye from being submitted to the buster-backports suite? Too many versioned (build-)depends not satisfyable on buster?
> 
> Debian is stable because it moves slowly, and if anything breaks in an upgrade, they don't proceed until everything's fixed.

When I asked about the buster-backports suite I was explicitly referring to https://backports.debian.org/ where packages from later releases are built for the stable release. Generally the maintainer of the rustc package would propose the version from bullseye for inclusion in buster-backports. That would then provide an optional newer version of rustc which users could optionally install instead of the version present in buster itself (by default, packages from backports are not installed unless explicitly requested by the user).

**Comment by mtreinish** [comment]
> > My only other thought is to use an official build of rustc
> 
> I don't think so, because I assume that would require the user to have the same version of rust? Or does the user not need rust?

Rust isn't required to be installed for the end user, It's just a build dependency and is only needed to compile the binary in the wheel, but it's statically linked against all the rust dependencies and there is no runtime dependency on anything after its built. So once the binary is built it should work fine for everyone regardless of whether rust is installed or not.

> 
> If you want to build a wheel and test it, see if it works, it's not out of the question that we import it. Just there's only two special cases we do that for currently (tensorflow and opencv). And if it requires anything other than an `apt install` to use then it's probably not worth it.

I built a wheel already on my local pi4 running rasbian https://blog.kortar.org/wp-content/uploads/2020/07/retworkx-0.4.0-cp37-cp37m-linux_armv7l.whl and have already confirmed that it works on a different raspberry pi 4 that doesn't have the rust compiler installed.

**Comment by bennuttall** [comment]
Update: I installed cargo and the cp37m builds for retworkx have succeeded!
